## Import libraries (with aliases if applicable)

In [3]:
import tweepy
import requests
import pandas as pd
import numpy as np
import json
import os
import re
import timeit
from datetime import datetime

## Gather data

In [4]:
# Import enhanced.csv provided by Project Details
df_enhanced = pd.read_csv('twitter-archive-enhanced.csv')

# Import image predictions tab delimited file using requests library to download from provided url in Project Details
# then write into my working directory. 
# requests library doc - http://docs.python-requests.org/en/master/
url = 'https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv'
r = requests.get(url)

folder_name = os.getcwd()

with open(os.path.join(folder_name, url.split('/')[-1]), mode='wb') as file: 
    file.write(r.content)

df_predictions = pd.read_csv('image-predictions.tsv',delimiter='\t')

# Write column names of dataframes into lists 
clmn_names_enhanced = list(df_enhanced.columns)
clmn_names_predictions = list(df_predictions.columns)

In [333]:
# Extract information with tweepy API using twitter_id
# How to use twitter API - https://stackoverflow.com/questions/28384588/twitter-api-get-tweets-with-specific-id
consumer_key = '1LYKqXj2fIBBc92AP3Zro0Guk'
consumer_secret = 'cqsEOww8AnqRaqnysWLw2vRRXyohMOa08w08uemKwMQa301eDH'
access_token = '1036607321940447233-HpfLYF2Lkc9270Kwon9O8JJFGZW3sR'
access_secret = 'FOisn4zlQZ9BtL6veGlEej2LCaWLoeXHlt3IknGMzJGTW'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth, wait_on_rate_limit= True, wait_on_rate_limit_notify=True)

In [334]:
# Sites used: 
# 1) How to dump a json file into a .txt file https://stackabuse.com/reading-and-writing-json-to-a-file-in-python/
# 2) How to use json Python library - https://docs.python.org/3.7/library/json.html#basic-usage
# 3) How to use try/exceptions - https://wiki.python.org/moin/HandlingExceptions
# 4) tweepy errors - http://docs.tweepy.org/en/v3.5.0/api.html#tweepy-error-exceptions
# 5) How to write to a file using Python - 


# Extract the tweet information of each tweet_id and place it in a text file in JSON format
failed_tweetIds = {} # empty dictionary where keys are tweet_ids and values are the error outputs from tweepy API
SuccessCount = 0 
tweet_ids = df_enhanced.tweet_id.values

with open('tweet_json.txt','w') as outfile: 
    for tweet_id in tweet_ids: 
        try: 
            SuccessCount +=1
            start = timeit.timeit()
            tweet = api.get_status(tweet_id,tweet_mode = 'extended')
            tweet = tweet._json
            json.dump(tweet,outfile)
            outfile.write("\n") # delimit by new line, json.dump does not do this. 
            end = timeit.timeit()
            print('Success Count:', SuccessCount, 'Tweet ID: ', tweet_id, 'Time:', end-start)   
        except tweepy.TweepError as e: 
            print('Failed to access Tweet ID:',tweet_id)
            failed_tweetIds[tweet_id] = e

Success Count: 1 Tweet ID:  892420643555336193 Time: 0.001189004076877609
Success Count: 2 Tweet ID:  892177421306343426 Time: -0.001037593901855871
Success Count: 3 Tweet ID:  891815181378084864 Time: 0.0037829888169653714
Success Count: 4 Tweet ID:  891689557279858688 Time: -0.009864316059974954
Success Count: 5 Tweet ID:  891327558926688256 Time: -0.0022088516561780125
Success Count: 6 Tweet ID:  891087950875897856 Time: -0.0003368026518728584
Success Count: 7 Tweet ID:  890971913173991426 Time: 0.0019483204232528806
Success Count: 8 Tweet ID:  890729181411237888 Time: 0.005938223883276805
Success Count: 9 Tweet ID:  890609185150312448 Time: 0.0008151984366122633
Success Count: 10 Tweet ID:  890240255349198849 Time: -0.008751205896260217
Success Count: 11 Tweet ID:  890006608113172480 Time: -0.003670847130706534
Success Count: 12 Tweet ID:  889880896479866881 Time: -6.72095047775656e-05
Success Count: 13 Tweet ID:  889665388333682689 Time: 0.008692303177667782
Success Count: 14 Tweet ID:  889638837579907072 Time: -0.009879796940367669
Success Count: 15 Tweet ID:  889531135344209921 Time: 0.010898511769482866
Success Count: 16 Tweet ID:  889278841981685760 Time: -0.0052959577878937125
Success Count: 17 Tweet ID:  888917238123831296 Time: -0.005776241450803354
Success Count: 18 Tweet ID:  888804989199671297 Time: 6.75870687700808e-05
Success Count: 19 Tweet ID:  888554962724278272 Time: 0.012238170864293352
Failed to access Tweet ID: 888202515573088257
Success Count: 21 Tweet ID:  888078434458587136 Time: 0.004661998507799581
Success Count: 22 Tweet ID:  887705289381826560 Time: -0.0013630691391881555
Success Count: 23 Tweet ID:  887517139158093824 Time: -0.0020143971778452396
Success Count: 24 Tweet ID:  887473957103951883 Time: 0.003540581528795883
Success Count: 25 Tweet ID:  887343217045368832 Time: -0.0004765078192576766
Success Count: 26 Tweet ID:  887101392804085760 Time: 0.0024101025774143636
Success Count: 27 Tweet ID:  886983233522544640 Time: 0.01951529865618795
Success Count: 28 Tweet ID:  886736880519319552 Time: -0.009720835165353492
Success Count: 29 Tweet ID:  886680336477933568 Time: 0.0032619264093227684
Success Count: 30 Tweet ID:  886366144734445568 Time: -0.0019098071206826717
Success Count: 31 Tweet ID:  886267009285017600 Time: -0.0012988802918698639
Success Count: 32 Tweet ID:  886258384151887873 Time: 0.014260874828323722
Success Count: 33 Tweet ID:  886054160059072513 Time: -0.01659130770713091
Success Count: 34 Tweet ID:  885984800019947520 Time: -0.004486045567318797
Success Count: 35 Tweet ID:  885528943205470208 Time: -0.0046468952496070415
Success Count: 36 Tweet ID:  885518971528720385 Time: -0.0018210754788015038
Success Count: 37 Tweet ID:  885311592912609280 Time: 0.005453031713841483
Success Count: 38 Tweet ID:  885167619883638784 Time: -0.001520143065135926
Success Count: 39 Tweet ID:  884925521741709313 Time: 0.0035300092422403395
Success Count: 40 Tweet ID:  884876753390489601 Time: 0.0016726859321352094
Success Count: 41 Tweet ID:  884562892145688576 Time: -0.0014676591963507235
Success Count: 42 Tweet ID:  884441805382717440 Time: -0.0011301013582851738
Success Count: 43 Tweet ID:  884247878851493888 Time: -0.0034299501276109368
Success Count: 44 Tweet ID:  884162670584377345 Time: 0.0082278779882472
Success Count: 45 Tweet ID:  883838122936631299 Time: 0.0325694230850786
Success Count: 46 Tweet ID:  883482846933004288 Time: 0.005339379684301093
Success Count: 47 Tweet ID:  883360690899218434 Time: -0.013096791110001504
Success Count: 48 Tweet ID:  883117836046086144 Time: -0.002871129574486986
Success Count: 49 Tweet ID:  882992080364220416 Time: 0.005962389142950997
Success Count: 50 Tweet ID:  882762694511734784 Time: -0.0033015724329743534
Success Count: 51 Tweet ID:  882627270321602560 Time: -0.0021412645583041012
Success Count: 52 Tweet ID:  882268110199369728 Time: 0.03235420162673108
Success Count: 53 Tweet ID:  882045870035918850 Time: -0.026907588820904493
Success Count: 54 Tweet ID:  881906580714921986 Time: 0.00305123592261225
Success Count: 55 Tweet ID:  881666595344535552 Time: -0.002166940103052184
Success Count: 56 Tweet ID:  881633300179243008 Time: 0.01123909023590386
Success Count: 57 Tweet ID:  881536004380872706 Time: -0.008752716210437939
Success Count: 58 Tweet ID:  881268444196462592 Time: -0.003497537225484848
Success Count: 59 Tweet ID:  880935762899988482 Time: 0.0029205927276052535
Success Count: 60 Tweet ID:  880872448815771648 Time: 0.0021695831674151123
Success Count: 61 Tweet ID:  880465832366813184 Time: 0.005415651161456481
Success Count: 62 Tweet ID:  880221127280381952 Time: -0.0013823258050251752
Success Count: 63 Tweet ID:  880095782870896641 Time: 0.010258511174470186
Success Count: 64 Tweet ID:  879862464715927552 Time: -0.003146008908515796
Success Count: 65 Tweet ID:  879674319642796034 Time: 0.012863068172009662
Success Count: 66 Tweet ID:  879492040517615616 Time: 0.011368978273821995
Success Count: 67 Tweet ID:  879415818425184262 Time: 0.003726729191839695
Success Count: 68 Tweet ID:  879376492567855104 Time: -0.016141985746799037
Success Count: 69 Tweet ID:  879130579576475649 Time: -0.006650342576904222
Success Count: 70 Tweet ID:  879050749262655488 Time: -0.004463390621822327
Success Count: 71 Tweet ID:  879008229531029506 Time: 0.0008231276297010481
Success Count: 72 Tweet ID:  878776093423087618 Time: -0.0034167348057962954
Success Count: 73 Tweet ID:  878604707211726852 Time: 0.0013392814726103097
Success Count: 74 Tweet ID:  878404777348136964 Time: 0.005957102956017479
Success Count: 75 Tweet ID:  878316110768087041 Time: -0.002254916587844491
Success Count: 76 Tweet ID:  878281511006478336 Time: -0.007068702805554494
Success Count: 77 Tweet ID:  878057613040115712 Time: 0.005163426714716479
Success Count: 78 Tweet ID:  877736472329191424 Time: 0.0021405094012152404
Success Count: 79 Tweet ID:  877611172832227328 Time: 0.003281938232248649
Success Count: 80 Tweet ID:  877556246731214848 Time: -0.004107708897208795
Success Count: 81 Tweet ID:  877316821321428993 Time: -0.00018916832050308585
Success Count: 82 Tweet ID:  877201837425926144 Time: 0.005135108105605468
Success Count: 83 Tweet ID:  876838120628539392 Time: -0.005244229163508862
Success Count: 84 Tweet ID:  876537666061221889 Time: 0.0023678134311921895
Success Count: 85 Tweet ID:  876484053909872640 Time: 0.013640508492244408
Success Count: 86 Tweet ID:  876120275196170240 Time: -0.0022239548852667212
Success Count: 87 Tweet ID:  875747767867523072 Time: -0.006404914573067799
Success Count: 88 Tweet ID:  875144289856114688 Time: -0.001189004076877609
Success Count: 89 Tweet ID:  875097192612077568 Time: 0.009417259600013494
Success Count: 90 Tweet ID:  875021211251597312 Time: 0.0025464094942435622
Success Count: 91 Tweet ID:  874680097055178752 Time: -0.005937468755291775
Success Count: 92 Tweet ID:  874434818259525634 Time: -0.00594199969782494
Success Count: 93 Tweet ID:  874296783580663808 Time: 0.015040580532513559
Success Count: 94 Tweet ID:  874057562936811520 Time: 0.012557982379803434
Success Count: 95 Tweet ID:  874012996292530176 Time: -0.004978411772754043
Failed to access Tweet ID: 873697596434513921
Success Count: 97 Tweet ID:  873580283840344065 Time: 0.008509176201187074
Success Count: 98 Tweet ID:  873337748698140672 Time: -0.00484248244902119
Success Count: 99 Tweet ID:  873213775632977920 Time: 4.53100074082613e-06
Success Count: 100 Tweet ID:  872967104147763200 Time: -0.0024021733552217484
Success Count: 101 Tweet ID:  872820683541237760 Time: 0.015546162147074938
Failed to access Tweet ID: 872668790621863937
Success Count: 103 Tweet ID:  872620804844003328 Time: -0.0047956623311620206
Success Count: 104 Tweet ID:  872486979161796608 Time: -0.018624206364620477
Success Count: 105 Tweet ID:  872261713294495745 Time: 0.004398446617415175
Success Count: 106 Tweet ID:  872122724285648897 Time: -0.008374002005439252
Success Count: 107 Tweet ID:  871879754684805121 Time: -0.013025805790675804
Success Count: 108 Tweet ID:  871762521631449091 Time: -0.0020918014051858336
Success Count: 109 Tweet ID:  871515927908634625 Time: 0.00048670254182070494
Success Count: 110 Tweet ID:  871166179821445120 Time: 0.0790919920837041

Success Count: 111 Tweet ID:  871102520638267392 Time: -0.018471285875421017
Success Count: 112 Tweet ID:  871032628920680449 Time: -0.009671371954027563
Success Count: 113 Tweet ID:  870804317367881728 Time: -0.0015050397778395563
Success Count: 114 Tweet ID:  870726314365509632 Time: -0.07196551925153472
Success Count: 115 Tweet ID:  870656317836468226 Time: -0.0016628688026685268
Success Count: 116 Tweet ID:  870374049280663552 Time: 0.020510225847829133
Success Count: 117 Tweet ID:  870308999962521604 Time: -0.02537876140559092
Success Count: 118 Tweet ID:  870063196459192321 Time: 0.02183553684153594
Failed to access Tweet ID: 869988702071779329
Success Count: 120 Tweet ID:  869772420881756160 Time: 0.03415337734622881
Success Count: 121 Tweet ID:  869702957897576449 Time: -0.02653114005806856
Success Count: 122 Tweet ID:  869596645499047938 Time: -0.014976014150306582
Success Count: 123 Tweet ID:  869227993411051520 Time: 0.018239828437799588
Success Count: 124 Tweet ID:  868880397819494401 Time: 0.007885033992351964
Success Count: 125 Tweet ID:  868639477480148993 Time: 0.01139276591129601
Success Count: 126 Tweet ID:  868622495443632128 Time: 0.001987211318919435
Success Count: 127 Tweet ID:  868552278524837888 Time: -0.0003628557897172868
Success Count: 128 Tweet ID:  867900495410671616 Time: -0.018019320821622387
Success Count: 129 Tweet ID:  867774946302451713 Time: -0.0024965687189251184
Success Count: 130 Tweet ID:  867421006826221569 Time: 0.002206586126703769
Success Count: 131 Tweet ID:  867072653475098625 Time: -0.0009643431112635881
Success Count: 132 Tweet ID:  867051520902168576 Time: -0.0007087204430717975
Failed to access Tweet ID: 866816280283807744
Success Count: 134 Tweet ID:  866720684873056260 Time: 0.005709409510018304
Success Count: 135 Tweet ID:  866686824827068416 Time: -0.0020812290895264596
Success Count: 136 Tweet ID:  866450705531457537 Time: -0.0017225267074536532
Success Count: 137 Tweet ID:  866334964761202691 Time: 0.019222672999603674
Success Count: 138 Tweet ID:  866094527597207552 Time: -0.009052893496118486
Success Count: 139 Tweet ID:  865718153858494464 Time: -0.0029213478846941143
Success Count: 140 Tweet ID:  865359393868664832 Time: -0.002313441742444411
Success Count: 141 Tweet ID:  865006731092295680 Time: 0.0002964014420285821
Success Count: 142 Tweet ID:  864873206498414592 Time: -0.002614751720102504
Success Count: 143 Tweet ID:  864279568663928832 Time: -0.0019007451774086803
Success Count: 144 Tweet ID:  864197398364647424 Time: 0.0019362378225196153
Success Count: 145 Tweet ID:  863907417377173506 Time: 0.014111352531472221
Success Count: 146 Tweet ID:  863553081350529029 Time: -0.012234394991537556
Success Count: 147 Tweet ID:  863471782782697472 Time: 0.014329972240375355
Success Count: 148 Tweet ID:  863432100342583297 Time: 0.02094746517832391
Success Count: 149 Tweet ID:  863427515083354112 Time: 0.026604768499964848
Success Count: 150 Tweet ID:  863079547188785154 Time: -0.0037629770231433213
Success Count: 151 Tweet ID:  863062471531167744 Time: -0.03346655669156462
Success Count: 152 Tweet ID:  862831371563274240 Time: 0.01252739827032201
Success Count: 153 Tweet ID:  862722525377298433 Time: 0.013648815249325708
Success Count: 154 Tweet ID:  862457590147678208 Time: -0.005307662824634463
Success Count: 155 Tweet ID:  862096992088072192 Time: -0.0060224245535209775
Failed to access Tweet ID: 861769973181624320
Success Count: 157 Tweet ID:  861383897657036800 Time: -0.02857385590323247
Success Count: 158 Tweet ID:  861288531465048066 Time: 0.015461206348845735
Success Count: 159 Tweet ID:  861005113778896900 Time: 0.0017886034620460123
Success Count: 160 Tweet ID:  860981674716409858 Time: -0.005009751039324328
Success Count: 161 Tweet ID:  860924035999428608 Time: -0.006004300637869164
Success Count: 162 Tweet ID:  860563773140209665 Time: 0.012870997394202277
Success Count: 163 Tweet ID:  860524505164394496 Time: -0.021043370885308832
Success Count: 164 Tweet ID:  860276583193509888 Time: 0.0018089928780682385
Success Count: 165 Tweet ID:  860184849394610176 Time: -0.002882079395931214
Success Count: 166 Tweet ID:  860177593139703809 Time: 0.00574905559187755
Success Count: 167 Tweet ID:  859924526012018688 Time: 0.006643168511800468
Success Count: 168 Tweet ID:  859851578198683649 Time: -0.005500606959685683
Success Count: 169 Tweet ID:  859607811541651456 Time: -0.005689397745300084
Success Count: 170 Tweet ID:  859196978902773760 Time: -0.009145400952547789
Success Count: 171 Tweet ID:  859074603037188101 Time: -0.006509504688438028
Success Count: 172 Tweet ID:  858860390427611136 Time: 0.00390343731851317
Success Count: 173 Tweet ID:  858843525470990336 Time: 0.0009843549341894686
Success Count: 174 Tweet ID:  858471635011153920 Time: -0.0030693598673678935
Success Count: 175 Tweet ID:  858107933456039936 Time: 0.0018833763897418976
Success Count: 176 Tweet ID:  857989990357356544 Time: -0.006809681945014745
Success Count: 177 Tweet ID:  857746408056729600 Time: 0.006749646476237103
Success Count: 178 Tweet ID:  857393404942143489 Time: -0.0028934068395756185
Success Count: 179 Tweet ID:  857263160327368704 Time: 0.007949222868774086
Success Count: 180 Tweet ID:  857214891891077121 Time: -0.002950799243990332
Success Count: 181 Tweet ID:  857062103051644929 Time: 0.004375036543933675
Success Count: 182 Tweet ID:  857029823797047296 Time: 0.01661698322277516
Success Count: 183 Tweet ID:  856602993587888130 Time: 0.0006339592800941318
Success Count: 184 Tweet ID:  856543823941562368 Time: -0.0031777257099747658
Success Count: 185 Tweet ID:  856526610513747968 Time: 0.002765784302027896
Success Count: 186 Tweet ID:  856330835276025856 Time: 0.003050103143323213
Success Count: 187 Tweet ID:  856288084350160898 Time: -0.010459006938617676
Success Count: 188 Tweet ID:  856282028240666624 Time: -0.0032868467387743294
Success Count: 189 Tweet ID:  855862651834028034 Time: 0.003419000277062878
Success Count: 190 Tweet ID:  855860136149123072 Time: -0.004240239999489859
Success Count: 191 Tweet ID:  855857698524602368 Time: -0.0021480610594153404
Success Count: 192 Tweet ID:  855851453814013952 Time: 0.01233860754291527
Success Count: 193 Tweet ID:  855818117272018944 Time: -0.0002514692605473101
Success Count: 194 Tweet ID:  855459453768019968 Time: 0.011973108630627394
Success Count: 195 Tweet ID:  855245323840757760 Time: 0.01036347879562527
Success Count: 196 Tweet ID:  855138241867124737 Time: 0.015389465843327343
Success Count: 197 Tweet ID:  854732716440526848 Time: 0.044542909279698506
Success Count: 198 Tweet ID:  854482394044301312 Time: -0.0033967229537665844
Success Count: 199 Tweet ID:  854365224396361728 Time: 0.0004417703312356025
Success Count: 200 Tweet ID:  854120357044912130 Time: 0.005477574479300529
Success Count: 201 Tweet ID:  854010172552949760 Time: 0.013265570014482364
Success Count: 202 Tweet ID:  853760880890318849 Time: -0.01885302076698281
Success Count: 203 Tweet ID:  853639147608842240 Time: -0.010088221926707774
Success Count: 204 Tweet ID:  853299958564483072 Time: -0.003342351206811145
Success Count: 205 Tweet ID:  852936405516943360 Time: 0.0006879534630570561
Success Count: 206 Tweet ID:  852912242202992640 Time: 0.018193385883932933
Success Count: 207 Tweet ID:  852672615818899456 Time: 0.0045098332047928125
Success Count: 208 Tweet ID:  852553447878664193 Time: 0.003401631547603756
Success Count: 209 Tweet ID:  852311364735569921 Time: -0.019265339738922194
Success Count: 210 Tweet ID:  852226086759018497 Time: 0.017360063560772687
Success Count: 211 Tweet ID:  852189679701164033 Time: -0.002938339050160721
Success Count: 212 Tweet ID:  851953902622658560 Time: 0.00033151652314700186
Success Count: 213 Tweet ID:  851861385021730816 Time: 0.008279606641735882
Success Count: 214 Tweet ID:  851591660324737024 Time: 0.007129871053621173
Success Count: 215 Tweet ID:  851464819735769094 Time: -0.004848146170843393
Success Count: 216 Tweet ID:  851224888060895234 Time: 0.013735281419940293
Success Count: 217 Tweet ID:  850753642995093505 Time: -0.003994056867668405
Success Count: 218 Tweet ID:  850380195714523136 Time: 0.0062055515591055155
Success Count: 219 Tweet ID:  850333567704068097 Time: 0.015079471457283944

Success Count: 220 Tweet ID:  850145622816686080 Time: -0.0018743144464679062
Success Count: 221 Tweet ID:  850019790995546112 Time: 0.005690152873285115
Success Count: 222 Tweet ID:  849776966551130114 Time: -0.01034762038034387
Success Count: 223 Tweet ID:  849668094696017920 Time: 0.013616720825666562
Success Count: 224 Tweet ID:  849412302885593088 Time: 0.012697687488980591
Success Count: 225 Tweet ID:  849336543269576704 Time: 0.010813555913046002
Success Count: 226 Tweet ID:  849051919805034497 Time: 0.016067602206021547
Success Count: 227 Tweet ID:  848690551926992896 Time: -0.02018965914612636
Success Count: 228 Tweet ID:  848324959059550208 Time: 0.02105016738642007
Success Count: 229 Tweet ID:  848213670039564288 Time: 0.011779409367591143
Success Count: 230 Tweet ID:  848212111729840128 Time: -0.001795399934053421
Success Count: 231 Tweet ID:  847978865427394560 Time: -0.005750188312958926
Success Count: 232 Tweet ID:  847971574464610304 Time: 0.023959810234373435
Success Count: 233 Tweet ID:  847962785489326080 Time: -0.0002703483623918146
Success Count: 234 Tweet ID:  847842811428974592 Time: -0.005036559334257618
Success Count: 235 Tweet ID:  847617282490613760 Time: 0.0035152835480403155
Success Count: 236 Tweet ID:  847606175596138505 Time: 0.012930655269883573
Success Count: 237 Tweet ID:  847251039262605312 Time: 0.003659519657958299
Success Count: 238 Tweet ID:  847157206088847362 Time: -0.02594777671038173
Success Count: 239 Tweet ID:  847116187444137987 Time: -0.00044516855268739164
Success Count: 240 Tweet ID:  846874817362120707 Time: -0.004562694579362869
Success Count: 241 Tweet ID:  846514051647705089 Time: 0.0003013100358657539
Success Count: 242 Tweet ID:  846505985330044928 Time: 0.025424448773264885
Success Count: 243 Tweet ID:  846153765933735936 Time: -0.0004923662636429071
Success Count: 244 Tweet ID:  846139713627017216 Time: -0.0009405554446857423
Success Count: 245 Tweet ID:  846042936437604353 Time: 0.005041467898990959
Success Count: 246 Tweet ID:  845812042753855489 Time: -0.013040531455771998
Success Count: 247 Tweet ID:  845677943972139009 Time: 0.0008824079122859985
Failed to access Tweet ID: 845459076796616705
Success Count: 249 Tweet ID:  845397057150107648 Time: -0.01174958041519858
Success Count: 250 Tweet ID:  845306882940190720 Time: 0.00046933378325775266
Success Count: 251 Tweet ID:  845098359547420673 Time: 0.017057620832929388
Success Count: 252 Tweet ID:  844979544864018432 Time: 0.047291702445363626
Success Count: 253 Tweet ID:  844973813909606400 Time: -0.03273706926847808
Success Count: 254 Tweet ID:  844704788403113984 Time: 0.01302278516232036
Success Count: 255 Tweet ID:  844580511645339650 Time: 0.025552448933012784
Success Count: 256 Tweet ID:  844223788422217728 Time: -0.008622450608527288
Success Count: 257 Tweet ID:  843981021012017153 Time: 0.02763971930835396
Success Count: 258 Tweet ID:  843856843873095681 Time: -0.022068504622438923
Success Count: 259 Tweet ID:  843604394117681152 Time: 0.013452472863718867
Success Count: 260 Tweet ID:  843235543001513987 Time: 0.0036410181783139706
Failed to access Tweet ID: 842892208864923648
Success Count: 262 Tweet ID:  842846295480000512 Time: -0.004560806672088802
Success Count: 263 Tweet ID:  842765311967449089 Time: 0.019702956633409485
Success Count: 264 Tweet ID:  842535590457499648 Time: -0.011705780954798684
Success Count: 265 Tweet ID:  842163532590374912 Time: 0.0028322386788204312
Success Count: 266 Tweet ID:  842115215311396866 Time: -0.018129952222807333
Success Count: 267 Tweet ID:  841833993020538882 Time: 0.011351609573466703
Success Count: 268 Tweet ID:  841680585030541313 Time: -0.006984879728406668
Success Count: 269 Tweet ID:  841439858740625411 Time: 0.007397576293442398
Success Count: 270 Tweet ID:  841320156043304961 Time: 0.02436722064157948
Success Count: 271 Tweet ID:  841314665196081154 Time: -0.012602914561284706
Success Count: 272 Tweet ID:  841077006473256960 Time: 0.017525821836898103
Success Count: 273 Tweet ID:  840761248237133825 Time: 0.013185900344979018
Success Count: 274 Tweet ID:  840728873075638272 Time: -0.013717535068280995
Success Count: 275 Tweet ID:  840698636975636481 Time: 0.03471899442956783
Success Count: 276 Tweet ID:  840696689258311684 Time: 0.01318665553117171
Success Count: 277 Tweet ID:  840632337062862849 Time: 0.010132398980204016
Success Count: 278 Tweet ID:  840370681858686976 Time: 0.017687049141386524
Success Count: 279 Tweet ID:  840268004936019968 Time: -0.0016949632263276726
Success Count: 280 Tweet ID:  839990271299457024 Time: 0.017196570814121515
Success Count: 281 Tweet ID:  839549326359670784 Time: 0.005742636683862656
Success Count: 282 Tweet ID:  839290600511926273 Time: 0.00780272125848569
Success Count: 283 Tweet ID:  839239871831150596 Time: 0.009771808632649481
Success Count: 284 Tweet ID:  838952994649550848 Time: 0.0013944084057584405
Success Count: 285 Tweet ID:  838921590096166913 Time: -0.010016103828093037
Success Count: 286 Tweet ID:  838916489579200512 Time: 0.015298846294172108
Success Count: 287 Tweet ID:  838831947270979586 Time: 0.0037848767242394388
Success Count: 288 Tweet ID:  838561493054533637 Time: 0.007185375521657988
Success Count: 289 Tweet ID:  838476387338051585 Time: -0.0017886034620460123
Success Count: 290 Tweet ID:  838201503651401729 Time: 0.03853860867093317
Success Count: 291 Tweet ID:  838150277551247360 Time: 0.014029794954694808
Success Count: 292 Tweet ID:  838085839343206401 Time: -0.003758446022402495
Success Count: 293 Tweet ID:  838083903487373313 Time: 0.008935465652029961
Success Count: 294 Tweet ID:  837820167694528512 Time: 0.006234247790416703
Success Count: 295 Tweet ID:  837482249356513284 Time: 0.006918802973814309
Success Count: 296 Tweet ID:  837471256429613056 Time: 0.009459171153139323
Success Count: 297 Tweet ID:  837366284874571778 Time: -0.004018222069134936
Success Count: 298 Tweet ID:  837110210464448512 Time: 0.018435793230310082
Failed to access Tweet ID: 837012587749474308
Success Count: 300 Tweet ID:  836989968035819520 Time: 0.0012633876176550984
Success Count: 301 Tweet ID:  836753516572119041 Time: -0.00933419170905836
Success Count: 302 Tweet ID:  836677758902222849 Time: -0.007698886358411983
Success Count: 303 Tweet ID:  836648853927522308 Time: 0.029001278104260564
Success Count: 304 Tweet ID:  836397794269200385 Time: -0.002004580048378557
Success Count: 305 Tweet ID:  836380477523124226 Time: 0.004715992632554844
Success Count: 306 Tweet ID:  836260088725786625 Time: 0.01774746217415668
Success Count: 307 Tweet ID:  836001077879255040 Time: 0.008972846233518794
Success Count: 308 Tweet ID:  835685285446955009 Time: 0.008189742249669507
Success Count: 309 Tweet ID:  835574547218894849 Time: 0.0017361196223646402
Success Count: 310 Tweet ID:  835536468978302976 Time: 0.012449994042981416
Success Count: 311 Tweet ID:  835309094223372289 Time: -0.005692795937648043
Success Count: 312 Tweet ID:  835297930240217089 Time: 0.013335800205823034
Success Count: 313 Tweet ID:  835264098648616962 Time: -0.003987637959653512
Success Count: 314 Tweet ID:  835246439529840640 Time: 0.009949271945515648
Success Count: 315 Tweet ID:  835172783151792128 Time: 0.012048247357597575
Success Count: 316 Tweet ID:  835152434251116546 Time: 0.014689052215544507
Success Count: 317 Tweet ID:  834931633769889797 Time: -0.024460860848193988
Success Count: 318 Tweet ID:  834786237630337024 Time: 0.013704319717362523
Success Count: 319 Tweet ID:  834574053763584002 Time: 0.010319301771232858
Success Count: 320 Tweet ID:  834477809192075265 Time: -0.001387234340654686
Success Count: 321 Tweet ID:  834458053273591808 Time: -0.0021843088616151363
Success Count: 322 Tweet ID:  834209720923721728 Time: -0.0018324028933420777
Success Count: 323 Tweet ID:  834167344700198914 Time: 0.0166974080784712
Success Count: 324 Tweet ID:  834089966724603904 Time: 0.01740650608553551
Success Count: 325 Tweet ID:  834086379323871233 Time: 0.009858274803264067
Success Count: 326 Tweet ID:  833863086058651648 Time: -0.006245575204957277
Success Count: 327 Tweet ID:  833826103416520705 Time: 0.0045551429502666
Success Count: 328 Tweet ID:  833732339549220864 Time: 0.015304132481105626

Success Count: 329 Tweet ID:  833722901757046785 Time: -0.0006305610586423427
Success Count: 330 Tweet ID:  833479644947025920 Time: -0.002031765936408192
Success Count: 331 Tweet ID:  833124694597443584 Time: -0.02399039431475103
Success Count: 332 Tweet ID:  832998151111966721 Time: 0.011402205447666347
Success Count: 333 Tweet ID:  832769181346996225 Time: 0.0164482043182943
Success Count: 334 Tweet ID:  832757312314028032 Time: 0.01673667653813027
Success Count: 335 Tweet ID:  832682457690300417 Time: -0.007761942426441237
Success Count: 336 Tweet ID:  832645525019123713 Time: 0.0026147517492063344
Success Count: 337 Tweet ID:  832636094638288896 Time: 0.003303460340248421
Success Count: 338 Tweet ID:  832397543355072512 Time: 0.003680286667076871
Success Count: 339 Tweet ID:  832369877331693569 Time: 0.00042402397957630455
Success Count: 340 Tweet ID:  832273440279240704 Time: -0.02214062269194983
Success Count: 341 Tweet ID:  832215909146226688 Time: 0.01399619021685794
Success Count: 342 Tweet ID:  832215726631055365 Time: 0.010050841316115111
Success Count: 343 Tweet ID:  832088576586297345 Time: 0.031651522527681664
Success Count: 344 Tweet ID:  832040443403784192 Time: -0.0029708110669162124
Success Count: 345 Tweet ID:  832032802820481025 Time: 0.022585413622437045
Success Count: 346 Tweet ID:  831939777352105988 Time: 0.0017497125372756273
Success Count: 347 Tweet ID:  831926988323639298 Time: 0.00021522145834751427
Success Count: 348 Tweet ID:  831911600680497154 Time: 0.00413149653468281
Success Count: 349 Tweet ID:  831670449226514432 Time: 0.01471472773118876
Success Count: 350 Tweet ID:  831650051525054464 Time: -0.016140475432621315
Success Count: 351 Tweet ID:  831552930092285952 Time: -0.005720359389670193
Success Count: 352 Tweet ID:  831322785565769729 Time: 0.014932969846995547
Success Count: 353 Tweet ID:  831315979191906304 Time: 0.006262943963520229
Success Count: 354 Tweet ID:  831309418084069378 Time: 0.0018592112173791975
Success Count: 355 Tweet ID:  831262627380748289 Time: 0.014515742339426652
Success Count: 356 Tweet ID:  830956169170665475 Time: 0.01833573411568068
Success Count: 357 Tweet ID:  830583320585068544 Time: -0.0055587545211892575
Success Count: 358 Tweet ID:  830173239259324417 Time: -0.004221360926749185
Success Count: 359 Tweet ID:  830097400375152640 Time: -0.0044248773192521185
Success Count: 360 Tweet ID:  829878982036299777 Time: 0.011600435740547255
Success Count: 361 Tweet ID:  829861396166877184 Time: -0.014731718954863027
Success Count: 362 Tweet ID:  829501995190984704 Time: 0.01775501383235678
Success Count: 363 Tweet ID:  829449946868879360 Time: 0.004977279051672667
Success Count: 364 Tweet ID:  829374341691346946 Time: -0.006587286421563476
Success Count: 365 Tweet ID:  829141528400556032 Time: -0.01828891402692534
Success Count: 366 Tweet ID:  829011960981237760 Time: 0.0055576217419002205
Success Count: 367 Tweet ID:  828801551087042563 Time: -0.00038097973447293043
Success Count: 368 Tweet ID:  828770345708580865 Time: -0.0005618412396870553
Success Count: 369 Tweet ID:  828708714936930305 Time: -0.002160898788133636
Success Count: 370 Tweet ID:  828650029636317184 Time: -0.004742423334391788
Success Count: 371 Tweet ID:  828409743546925057 Time: -0.0018954590195789933
Success Count: 372 Tweet ID:  828408677031882754 Time: 0.013520437525585294
Success Count: 373 Tweet ID:  828381636999917570 Time: -0.0376690385164693
Success Count: 374 Tweet ID:  828376505180889089 Time: 0.001807104970794171
Success Count: 375 Tweet ID:  828372645993398273 Time: 0.02224747822037898
Success Count: 376 Tweet ID:  828361771580813312 Time: -0.02260769094573334
Success Count: 377 Tweet ID:  828046555563323392 Time: 0.036785497853998095
Success Count: 378 Tweet ID:  828011680017821696 Time: 0.009814097749767825
Success Count: 379 Tweet ID:  827933404142436356 Time: -0.01505643900600262
Success Count: 380 Tweet ID:  827653905312006145 Time: -0.01687373867025599
Success Count: 381 Tweet ID:  827600520311402496 Time: -0.020850804343353957
Success Count: 382 Tweet ID:  827324948884643840 Time: 0.002312308963155374
Failed to access Tweet ID: 827228250799742977
Success Count: 384 Tweet ID:  827199976799354881 Time: 0.013399233896052465
Success Count: 385 Tweet ID:  826958653328592898 Time: 0.0037592012085951865
Success Count: 386 Tweet ID:  826848821049180160 Time: 0.012909510725876316
Success Count: 387 Tweet ID:  826615380357632002 Time: -0.003909101040335372
Success Count: 388 Tweet ID:  826598799820865537 Time: -0.001065534946974367
Success Count: 389 Tweet ID:  826598365270007810 Time: -7.174047641456127e-05
Success Count: 390 Tweet ID:  826476773533745153 Time: 0.018225102743599564
Success Count: 391 Tweet ID:  826240494070030336 Time: -0.02976512545137666
Success Count: 392 Tweet ID:  826204788643753985 Time: -0.00021673174342140555
Success Count: 393 Tweet ID:  826115272272650244 Time: -0.002017040242208168
Success Count: 394 Tweet ID:  825876512159186944 Time: -0.0009896410629153252
Success Count: 395 Tweet ID:  825829644528148480 Time: -0.0018441079591866583
Success Count: 396 Tweet ID:  825535076884762624 Time: 0.003509997419314459
Success Count: 397 Tweet ID:  825147591692263424 Time: -0.00109196561970748
Success Count: 398 Tweet ID:  825120256414846976 Time: -0.0041390481346752495
Success Count: 399 Tweet ID:  825026590719483904 Time: 0.0009552811679895967
Success Count: 400 Tweet ID:  824796380199809024 Time: 0.018723132729064673
Success Count: 401 Tweet ID:  824775126675836928 Time: 0.009022309386637062
Success Count: 402 Tweet ID:  824663926340194305 Time: -0.00313807962811552
Success Count: 403 Tweet ID:  824325613288833024 Time: 0.009396115085110068
Success Count: 404 Tweet ID:  824297048279236611 Time: -0.003276652074418962
Success Count: 405 Tweet ID:  824025158776213504 Time: 0.019598744169343263
Success Count: 406 Tweet ID:  823939628516474880 Time: 0.00039457264938391745
Success Count: 407 Tweet ID:  823719002937630720 Time: 0.006676773220533505
Success Count: 408 Tweet ID:  823699002998870016 Time: 0.011631019820924848
Success Count: 409 Tweet ID:  823581115634085888 Time: 0.009966640645870939
Success Count: 410 Tweet ID:  823333489516937216 Time: 0.0057909670867957175
Success Count: 411 Tweet ID:  823322678127919110 Time: 0.004719390883110464
Success Count: 412 Tweet ID:  823269594223824897 Time: 0.015617525088600814
Success Count: 413 Tweet ID:  822975315408461824 Time: 0.03681570434127934
Success Count: 414 Tweet ID:  822872901745569793 Time: -0.0010930983407888561
Success Count: 415 Tweet ID:  822859134160621569 Time: -0.002441819407977164
Success Count: 416 Tweet ID:  822647212903690241 Time: -0.0022103619703557342
Success Count: 417 Tweet ID:  822610361945911296 Time: 0.020125847921008244
Success Count: 418 Tweet ID:  822489057087389700 Time: 0.005983156064758077
Success Count: 419 Tweet ID:  822462944365645825 Time: -0.012175114767160267
Success Count: 420 Tweet ID:  822244816520155136 Time: 0.015596758079482242
Success Count: 421 Tweet ID:  822163064745328640 Time: 0.005696571752196178
Success Count: 422 Tweet ID:  821886076407029760 Time: -0.014000721159391105
Success Count: 423 Tweet ID:  821813639212650496 Time: 0.008859194203978404
Success Count: 424 Tweet ID:  821765923262631936 Time: -0.021622203290462494
Success Count: 425 Tweet ID:  821522889702862852 Time: 0.0005297468160279095
Success Count: 426 Tweet ID:  821421320206483457 Time: 0.019030484021641314
Success Count: 427 Tweet ID:  821407182352777218 Time: -0.010069720447063446
Success Count: 428 Tweet ID:  821153421864615936 Time: 0.018270034954184666
Success Count: 429 Tweet ID:  821149554670182400 Time: 0.030413055239478126
Success Count: 430 Tweet ID:  821107785811234820 Time: -0.0002809206198435277
Success Count: 431 Tweet ID:  821044531881721856 Time: 0.023482547228923067
Success Count: 432 Tweet ID:  820837357901512704 Time: -0.006357716891216114
Success Count: 433 Tweet ID:  820749716845686786 Time: 0.01473398442612961
Success Count: 434 Tweet ID:  820690176645140481 Time: 0.0016794824041426182
Success Count: 435 Tweet ID:  820494788566847489 Time: 0.014069063414353877
Success Count: 436 Tweet ID:  820446719150292993 Time: 0.0008544668671675026

Success Count: 437 Tweet ID:  820314633777061888 Time: -0.013114915025653318
Success Count: 438 Tweet ID:  820078625395449857 Time: 0.016121218766784295
Success Count: 439 Tweet ID:  820013781606658049 Time: 0.0011470925528556108
Success Count: 440 Tweet ID:  819952236453363712 Time: 0.01672572671668604
Success Count: 441 Tweet ID:  819924195358416896 Time: 0.0023859373468440026
Success Count: 442 Tweet ID:  819711362133872643 Time: 0.002012886863667518
Success Count: 443 Tweet ID:  819588359383371776 Time: -0.004538529377896339
Success Count: 444 Tweet ID:  819347104292290561 Time: 0.008318497537402436
Success Count: 445 Tweet ID:  819238181065359361 Time: -0.029877644701628014
Success Count: 446 Tweet ID:  819227688460238848 Time: 0.015777619584696367
Success Count: 447 Tweet ID:  819015337530290176 Time: -0.012657286279136315
Success Count: 448 Tweet ID:  819015331746349057 Time: 0.021895194717217237
Success Count: 449 Tweet ID:  819006400881917954 Time: -0.008693435927852988
Success Count: 450 Tweet ID:  819004803107983360 Time: 0.017773137718904763
Success Count: 451 Tweet ID:  818646164899774465 Time: -0.019275156839285046
Success Count: 452 Tweet ID:  818627210458333184 Time: -0.01941259653540328
Success Count: 453 Tweet ID:  818614493328580609 Time: 0.02559851383557543
Success Count: 454 Tweet ID:  818588835076603904 Time: -0.00831736478721723
Success Count: 455 Tweet ID:  818536468981415936 Time: -0.005769445007899776
Success Count: 456 Tweet ID:  818307523543449600 Time: 0.014975258993217722
Success Count: 457 Tweet ID:  818259473185828864 Time: 0.024202972708735615
Success Count: 458 Tweet ID:  818145370475810820 Time: 0.003960452129831538
Success Count: 459 Tweet ID:  817908911860748288 Time: -0.029392830096185207
Success Count: 460 Tweet ID:  817827839487737858 Time: 0.025127669709036127
Success Count: 461 Tweet ID:  817777686764523521 Time: -0.00995569079532288
Success Count: 462 Tweet ID:  817536400337801217 Time: 0.016519189637620002
Success Count: 463 Tweet ID:  817502432452313088 Time: 0.012205321254441515
Success Count: 464 Tweet ID:  817423860136083457 Time: -0.0006588796968571842
Success Count: 465 Tweet ID:  817415592588222464 Time: -0.008462356083327904
Success Count: 466 Tweet ID:  817181837579653120 Time: 0.026416355336550623
Success Count: 467 Tweet ID:  817171292965273600 Time: 0.0011946677695959806
Success Count: 468 Tweet ID:  817120970343411712 Time: 0.009250746195903048
Success Count: 469 Tweet ID:  817056546584727552 Time: 0.03962491056881845
Success Count: 470 Tweet ID:  816829038950027264 Time: -0.01634134876076132
Success Count: 471 Tweet ID:  816816676327063552 Time: 0.00012724497355520725
Success Count: 472 Tweet ID:  816697700272001025 Time: -0.03784423629986122
Success Count: 473 Tweet ID:  816450570814898180 Time: -0.0034884752531070262
Success Count: 474 Tweet ID:  816336735214911488 Time: 0.0018599663453642279
Success Count: 475 Tweet ID:  816091915477250048 Time: -1.2837786925956607e-05
Success Count: 476 Tweet ID:  816062466425819140 Time: 0.01145959782297723
Success Count: 477 Tweet ID:  816014286006976512 Time: 0.012356353865470737
Success Count: 478 Tweet ID:  815990720817401858 Time: -0.008102143328869715
Success Count: 479 Tweet ID:  815966073409433600 Time: -0.020066567638423294
Success Count: 480 Tweet ID:  815745968457060357 Time: 0.014701512409374118
Success Count: 481 Tweet ID:  815736392542261248 Time: -0.013300307560712099
Success Count: 482 Tweet ID:  815639385530101762 Time: 0.009827313100686297
Success Count: 483 Tweet ID:  815390420867969024 Time: 0.012160389072960243
Success Count: 484 Tweet ID:  814986499976527872 Time: 0.0063867906865198165
Success Count: 485 Tweet ID:  814638523311648768 Time: -0.013284449145430699
Success Count: 486 Tweet ID:  814578408554463233 Time: 0.024424990609986708
Success Count: 487 Tweet ID:  814530161257443328 Time: -8.344551315531135e-05
Success Count: 488 Tweet ID:  814153002265309185 Time: -0.00653102682554163
Success Count: 489 Tweet ID:  813944609378369540 Time: 0.01745747958193533
Success Count: 490 Tweet ID:  813910438903693312 Time: 0.00967665811185725
Success Count: 491 Tweet ID:  813812741911748608 Time: -0.0024357781221624464
Success Count: 492 Tweet ID:  813800681631023104 Time: -0.002610975905554369
Success Count: 493 Tweet ID:  813217897535406080 Time: -0.0032237906707450747
Success Count: 494 Tweet ID:  813202720496779264 Time: -0.004035968420794234
Success Count: 495 Tweet ID:  813187593374461952 Time: -0.00803078041644767
Success Count: 496 Tweet ID:  813172488309972993 Time: 0.027881749032530934
Success Count: 497 Tweet ID:  813157409116065792 Time: -0.009981743933167309
Success Count: 498 Tweet ID:  813142292504645637 Time: -0.007084561249939725
Success Count: 499 Tweet ID:  813130366689148928 Time: 0.011658960866043344
Success Count: 500 Tweet ID:  813127251579564032 Time: 0.008372869226150215
Success Count: 501 Tweet ID:  813112105746448384 Time: 0.023689839465077966
Success Count: 502 Tweet ID:  813096984823349248 Time: -0.014715860510477796
Success Count: 503 Tweet ID:  813081950185472002 Time: -0.006814212945755571
Success Count: 504 Tweet ID:  813066809284972545 Time: -0.015514445316512138
Success Count: 505 Tweet ID:  813051746834595840 Time: -7.551658200100064e-06
Success Count: 506 Tweet ID:  812781120811126785 Time: -0.004714482318377122
Success Count: 507 Tweet ID:  812747805718642688 Time: 0.01704742611036636
Success Count: 508 Tweet ID:  812709060537683968 Time: 0.004806989774806425
Success Count: 509 Tweet ID:  812503143955202048 Time: 0.016763484833063558
Success Count: 510 Tweet ID:  812466873996607488 Time: -0.006224808224942535
Success Count: 511 Tweet ID:  812372279581671427 Time: 0.011327444313792512
Success Count: 512 Tweet ID:  811985624773361665 Time: 0.019943476043408737
Success Count: 513 Tweet ID:  811744202451197953 Time: -0.019255900173448026
Success Count: 514 Tweet ID:  811647686436880384 Time: 0.0036179857270326465
Success Count: 515 Tweet ID:  811627233043480576 Time: 0.011890040739672258
Success Count: 516 Tweet ID:  811386762094317568 Time: -0.006008076452417299
Success Count: 517 Tweet ID:  810984652412424192 Time: 0.03755198826547712
Success Count: 518 Tweet ID:  810896069567610880 Time: 0.005348441627575085
Success Count: 519 Tweet ID:  810657578271330305 Time: 0.006259168148972094
Success Count: 520 Tweet ID:  810284430598270976 Time: 0.02757704077521339
Success Count: 521 Tweet ID:  810254108431155201 Time: -0.007221623323857784
Success Count: 522 Tweet ID:  809920764300447744 Time: 0.022751927084755152
Success Count: 523 Tweet ID:  809808892968534016 Time: 0.010657237173290923
Success Count: 524 Tweet ID:  809448704142938112 Time: 0.01765722021809779
Success Count: 525 Tweet ID:  809220051211603969 Time: 0.019537575979484245
Success Count: 526 Tweet ID:  809084759137812480 Time: -0.035568175168009475
Success Count: 527 Tweet ID:  808838249661788160 Time: 0.02000502185546793
Success Count: 528 Tweet ID:  808733504066486276 Time: -0.04073613282525912
Success Count: 529 Tweet ID:  808501579447930884 Time: 0.017018729937262833
Success Count: 530 Tweet ID:  808344865868283904 Time: 0.037900873576290905
Success Count: 531 Tweet ID:  808134635716833280 Time: -0.018661964510101825
Success Count: 532 Tweet ID:  808106460588765185 Time: 0.021894439560128376
Success Count: 533 Tweet ID:  808001312164028416 Time: 0.0018871522042900324
Success Count: 534 Tweet ID:  807621403335917568 Time: 0.020398839289555326
Success Count: 535 Tweet ID:  807106840509214720 Time: 1.3970508007332683e-05
Success Count: 536 Tweet ID:  807059379405148160 Time: -0.004808877682080492
Success Count: 537 Tweet ID:  807010152071229440 Time: -0.0027253830921836197
Success Count: 538 Tweet ID:  806629075125202948 Time: 0.01728454729891382
Success Count: 539 Tweet ID:  806620845233815552 Time: -0.000828036165330559
Success Count: 540 Tweet ID:  806576416489959424 Time: 0.0030602978949900717
Success Count: 541 Tweet ID:  806542213899489280 Time: 0.010539431765209883
Success Count: 542 Tweet ID:  806242860592926720 Time: 0.003325360070448369
Success Count: 543 Tweet ID:  806219024703037440 Time: 0.003339708171552047
Success Count: 544 Tweet ID:  805958939288408065 Time: 0.0037357911351136863

Success Count: 545 Tweet ID:  805932879469572096 Time: -0.024651539482874796
Success Count: 546 Tweet ID:  805826884734976000 Time: 0.022045849735150114
Success Count: 547 Tweet ID:  805823200554876929 Time: 0.0225291540264152
Success Count: 548 Tweet ID:  805520635690676224 Time: 0.002735577814746648
Success Count: 549 Tweet ID:  805487436403003392 Time: -0.019162637559929863
Success Count: 550 Tweet ID:  805207613751304193 Time: 0.013115670182742178
Success Count: 551 Tweet ID:  804738756058218496 Time: 0.018239073280710727
Success Count: 552 Tweet ID:  804475857670639616 Time: 0.010027431271737441
Success Count: 553 Tweet ID:  804413760345620481 Time: 0.010406523098936304
Success Count: 554 Tweet ID:  804026241225523202 Time: -0.0068085491948295385
Success Count: 555 Tweet ID:  803773340896923648 Time: 0.01076371519593522
Success Count: 556 Tweet ID:  803692223237865472 Time: -0.003259660879848525
Success Count: 557 Tweet ID:  803638050916102144 Time: 0.003322339412989095
Success Count: 558 Tweet ID:  803380650405482500 Time: 0.01127156225265935
Success Count: 559 Tweet ID:  803321560782307329 Time: -0.0015352463233284652
Success Count: 560 Tweet ID:  803276597545603072 Time: 0.00046895616105757654
Success Count: 561 Tweet ID:  802952499103731712 Time: -0.0001249794731847942
Success Count: 562 Tweet ID:  802624713319034886 Time: 0.00012044850154779851
Success Count: 563 Tweet ID:  802600418706604034 Time: 0.004502659110585228
Success Count: 564 Tweet ID:  802572683846291456 Time: -0.0133320243912749
Success Count: 565 Tweet ID:  802323869084381190 Time: -0.0022130050347186625
Success Count: 566 Tweet ID:  802265048156610565 Time: -0.0007868797983974218
Failed to access Tweet ID: 802247111496568832
Success Count: 568 Tweet ID:  802239329049477120 Time: -0.017977786890696734
Success Count: 569 Tweet ID:  802185808107208704 Time: 0.0005595757684204727
Success Count: 570 Tweet ID:  801958328846974976 Time: 0.01519840961555019
Success Count: 571 Tweet ID:  801854953262350336 Time: 0.016069490084191784
Success Count: 572 Tweet ID:  801538201127157760 Time: 0.01814769857446663
Success Count: 573 Tweet ID:  801285448605831168 Time: -0.0036957675183657557
Success Count: 574 Tweet ID:  801167903437357056 Time: 0.009529401315376163
Success Count: 575 Tweet ID:  801127390143516673 Time: 0.002413123205769807
Success Count: 576 Tweet ID:  801115127852503040 Time: -0.005353350192308426
Success Count: 577 Tweet ID:  800859414831898624 Time: 0.022871997993206605
Success Count: 578 Tweet ID:  800855607700029440 Time: -0.04359329189173877
Success Count: 579 Tweet ID:  800751577355128832 Time: -0.01948207151144743
Success Count: 580 Tweet ID:  800513324630806528 Time: 0.03912272717570886
Success Count: 581 Tweet ID:  800459316964663297 Time: 0.03392984910169616
Success Count: 582 Tweet ID:  800443802682937345 Time: 0.018425598536850885
Success Count: 583 Tweet ID:  800388270626521089 Time: -0.01022566159372218
Success Count: 584 Tweet ID:  800188575492947969 Time: 0.005398282344685867
Success Count: 585 Tweet ID:  800141422401830912 Time: 0.017269444040721282
Success Count: 586 Tweet ID:  800018252395122689 Time: 0.022036410198779777
Success Count: 587 Tweet ID:  799774291445383169 Time: -0.01216982858022675
Success Count: 588 Tweet ID:  799757965289017345 Time: -0.020029564620926976
Success Count: 589 Tweet ID:  799422933579902976 Time: -0.011719751462806016
Success Count: 590 Tweet ID:  799308762079035393 Time: 0.01658035779837519
Success Count: 591 Tweet ID:  799297110730567681 Time: -0.0052989784453529865
Success Count: 592 Tweet ID:  799063482566066176 Time: 0.01614915978279896
Success Count: 593 Tweet ID:  798933969379225600 Time: -0.002594739926280454
Success Count: 594 Tweet ID:  798925684722855936 Time: -0.014266538521042094
Success Count: 595 Tweet ID:  798705661114773508 Time: 0.0026993299543391913
Success Count: 596 Tweet ID:  798701998996647937 Time: 0.005710164696210995
Success Count: 597 Tweet ID:  798697898615730177 Time: -0.0033774663461372256
Success Count: 598 Tweet ID:  798694562394996736 Time: -0.001875069603556767
Success Count: 599 Tweet ID:  798686750113755136 Time: 0.010432576207676902
Success Count: 600 Tweet ID:  798682547630837760 Time: 0.01601058739470318
Success Count: 601 Tweet ID:  798673117451325440 Time: 0.005609350424492732
Success Count: 602 Tweet ID:  798665375516884993 Time: -0.004299142688978463
Success Count: 603 Tweet ID:  798644042770751489 Time: -0.005402813374530524
Success Count: 604 Tweet ID:  798628517273620480 Time: 0.0177825772552751
Success Count: 605 Tweet ID:  798585098161549313 Time: 0.022584658494452015
Success Count: 606 Tweet ID:  798576900688019456 Time: -0.008006237650988623
Success Count: 607 Tweet ID:  798340744599797760 Time: -0.021875560487387702
Success Count: 608 Tweet ID:  798209839306514432 Time: 0.0012728271540254354
Success Count: 609 Tweet ID:  797971864723324932 Time: 0.019531912228558213
Success Count: 610 Tweet ID:  797545162159308800 Time: -0.002603046683361754
Success Count: 611 Tweet ID:  797236660651966464 Time: 0.0166732429061085
Success Count: 612 Tweet ID:  797165961484890113 Time: 0.03359908776474185
Success Count: 613 Tweet ID:  796904159865868288 Time: -0.009468233096413314
Success Count: 614 Tweet ID:  796865951799083009 Time: 0.0005006730498280376
Success Count: 615 Tweet ID:  796759840936919040 Time: 0.027928946685278788
Success Count: 616 Tweet ID:  796563435802726400 Time: -0.00938176698400639
Success Count: 617 Tweet ID:  796484825502875648 Time: 0.016149537404999137
Success Count: 618 Tweet ID:  796387464403357696 Time: -0.014013558917213231
Success Count: 619 Tweet ID:  796177847564038144 Time: 3.133929567411542e-05
Success Count: 620 Tweet ID:  796149749086875649 Time: 0.009357601753436029
Success Count: 621 Tweet ID:  796125600683540480 Time: 0.008817282679956406
Success Count: 622 Tweet ID:  796116448414461957 Time: 0.00033227168023586273
Success Count: 623 Tweet ID:  796080075804475393 Time: 0.015950174361933023
Success Count: 624 Tweet ID:  796031486298386433 Time: 0.006097940844483674
Success Count: 625 Tweet ID:  795464331001561088 Time: -0.012923481233883649
Success Count: 626 Tweet ID:  795400264262053889 Time: 0.018549067637650296
Success Count: 627 Tweet ID:  795076730285391872 Time: -0.00333442201372236
Success Count: 628 Tweet ID:  794983741416415232 Time: -0.008814639586489648
Success Count: 629 Tweet ID:  794926597468000259 Time: 0.001780674239853397
Success Count: 630 Tweet ID:  794355576146903043 Time: -0.0004916111065540463
Success Count: 631 Tweet ID:  794332329137291264 Time: 0.0226001393457409
Success Count: 632 Tweet ID:  794205286408003585 Time: -0.010018746921559796
Success Count: 633 Tweet ID:  793962221541933056 Time: 0.0037603339296765625
Success Count: 634 Tweet ID:  793845145112371200 Time: 0.013286714616697282
Success Count: 635 Tweet ID:  793614319594401792 Time: -0.012028990691760555
Success Count: 636 Tweet ID:  793601777308463104 Time: 0.008703253057319671
Success Count: 637 Tweet ID:  793500921481273345 Time: -0.0005897822557017207
Success Count: 638 Tweet ID:  793286476301799424 Time: -0.002205830969614908
Success Count: 639 Tweet ID:  793271401113350145 Time: 0.011371621367288753
Success Count: 640 Tweet ID:  793256262322548741 Time: -0.014840462419670075
Success Count: 641 Tweet ID:  793241302385262592 Time: 0.019503216055454686
Success Count: 642 Tweet ID:  793226087023144960 Time: 0.0074126795516349375
Success Count: 643 Tweet ID:  793210959003287553 Time: 0.013596709002740681
Success Count: 644 Tweet ID:  793195938047070209 Time: -6.72095047775656e-05
Success Count: 645 Tweet ID:  793180763617361921 Time: -0.0031278849637601525
Success Count: 646 Tweet ID:  793165685325201412 Time: 0.00047499750507995486
Success Count: 647 Tweet ID:  793150605191548928 Time: 0.003620628791395575
Success Count: 648 Tweet ID:  793135492858580992 Time: 0.02432191086700186
Success Count: 649 Tweet ID:  793120401413079041 Time: 0.013913122296798974
Success Count: 650 Tweet ID:  792913359805018113 Time: -0.015582032414386049
Success Count: 651 Tweet ID:  792883833364439040 Time: -0.011342925135977566
Success Count: 652 Tweet ID:  792773781206999040 Time: -0.0126803187886253

Success Count: 653 Tweet ID:  792394556390137856 Time: 0.021263878443278372
Success Count: 654 Tweet ID:  792050063153438720 Time: 0.023313013138249516
Success Count: 655 Tweet ID:  791821351946420224 Time: -0.01549254558631219
Success Count: 656 Tweet ID:  791784077045166082 Time: 0.03401027398649603
Success Count: 657 Tweet ID:  791780927877898241 Time: -0.0247814274916891
Success Count: 658 Tweet ID:  791774931465953280 Time: 0.030435710126766935
Success Count: 659 Tweet ID:  791672322847637504 Time: -0.025021569366799667
Success Count: 660 Tweet ID:  791406955684368384 Time: -0.012293297739233822
Success Count: 661 Tweet ID:  791312159183634433 Time: 0.005192500451812521
Success Count: 662 Tweet ID:  791026214425268224 Time: 0.017336653516395018
Success Count: 663 Tweet ID:  790987426131050500 Time: 0.014686786715174094
Success Count: 664 Tweet ID:  790946055508652032 Time: -0.02112719396245666
Success Count: 665 Tweet ID:  790723298204217344 Time: 0.019421280856477097
Success Count: 666 Tweet ID:  790698755171364864 Time: 0.024073462263913825
Success Count: 667 Tweet ID:  790581949425475584 Time: 0.028204958769492805
Success Count: 668 Tweet ID:  790337589677002753 Time: 0.00235610842355527
Success Count: 669 Tweet ID:  790277117346975746 Time: -0.005434907769085839
Success Count: 670 Tweet ID:  790227638568808452 Time: -0.005302754259901121
Success Count: 671 Tweet ID:  789986466051088384 Time: -0.004845503106480464
Success Count: 672 Tweet ID:  789960241177853952 Time: 0.017995155620155856
Success Count: 673 Tweet ID:  789903600034189313 Time: -0.008979642705526203
Success Count: 674 Tweet ID:  789628658055020548 Time: -0.009753684716997668
Success Count: 675 Tweet ID:  789599242079838210 Time: 0.014712839823914692
Success Count: 676 Tweet ID:  789530877013393408 Time: 0.011037839314667508
Success Count: 677 Tweet ID:  789314372632018944 Time: 0.01771423500031233
Success Count: 678 Tweet ID:  789280767834746880 Time: 0.005223462183494121
Success Count: 679 Tweet ID:  789268448748703744 Time: 0.038799895031843334
Success Count: 680 Tweet ID:  789137962068021249 Time: -0.0008393636380787939
Success Count: 681 Tweet ID:  788908386943430656 Time: -0.010464670631336048
Success Count: 682 Tweet ID:  788765914992902144 Time: -0.007459499669494107
Success Count: 683 Tweet ID:  788552643979468800 Time: 0.02316726668504998
Success Count: 684 Tweet ID:  788412144018661376 Time: -0.0015242964145727456
Success Count: 685 Tweet ID:  788178268662984705 Time: 0.0036561214365065098
Success Count: 686 Tweet ID:  788150585577050112 Time: 0.004492086794925854
Success Count: 687 Tweet ID:  788070120937619456 Time: -0.020185883389785886
Success Count: 688 Tweet ID:  788039637453406209 Time: 0.006164395192172378
Success Count: 689 Tweet ID:  787810552592695296 Time: -0.014492332265945151
Success Count: 690 Tweet ID:  787717603741622272 Time: 0.006193091394379735
Success Count: 691 Tweet ID:  787397959788929025 Time: 0.004108086519408971
Success Count: 692 Tweet ID:  787322443945877504 Time: -0.007907311344752088
Success Count: 693 Tweet ID:  787111942498508800 Time: 0.0025758608535397798
Success Count: 694 Tweet ID:  786963064373534720 Time: 0.01629452867200598
Success Count: 695 Tweet ID:  786729988674449408 Time: -0.00867078106966801
Success Count: 696 Tweet ID:  786709082849828864 Time: 0.02780774308484979
Success Count: 697 Tweet ID:  786664955043049472 Time: 0.0020989754411857575
Success Count: 698 Tweet ID:  786595970293370880 Time: -0.03149407100863755
Success Count: 699 Tweet ID:  786363235746385920 Time: 0.02114040934247896
Success Count: 700 Tweet ID:  786286427768250368 Time: -0.022013755282387137
Success Count: 701 Tweet ID:  786233965241827333 Time: 0.0012679185892920941
Success Count: 702 Tweet ID:  786051337297522688 Time: -0.004725809762021527
Success Count: 703 Tweet ID:  786036967502913536 Time: 0.01024982679518871
Success Count: 704 Tweet ID:  785927819176054784 Time: 0.00669565235148184
Success Count: 705 Tweet ID:  785872687017132033 Time: 0.00942103541456163
Success Count: 706 Tweet ID:  785639753186217984 Time: 0.013692992273718119
Success Count: 707 Tweet ID:  785533386513321988 Time: 0.00852541220956482
Success Count: 708 Tweet ID:  785515384317313025 Time: -0.0139735353004653
Success Count: 709 Tweet ID:  785264754247995392 Time: 0.0012792460329364985
Success Count: 710 Tweet ID:  785170936622350336 Time: 0.01946281484561041
Success Count: 711 Tweet ID:  784826020293709826 Time: 0.011337261443259194
Success Count: 712 Tweet ID:  784517518371221505 Time: 0.0005595757393166423
Success Count: 713 Tweet ID:  784431430411685888 Time: 0.0021967690263409168
Success Count: 714 Tweet ID:  784183165795655680 Time: -0.01039859387674369
Success Count: 715 Tweet ID:  784057939640352768 Time: 0.010447301901876926
Success Count: 716 Tweet ID:  783839966405230592 Time: 0.007996042928425595
Success Count: 717 Tweet ID:  783821107061198850 Time: 0.004626883426681161
Success Count: 718 Tweet ID:  783695101801398276 Time: -0.01658790948567912
Success Count: 719 Tweet ID:  783466772167098368 Time: -0.0070943783794064075
Success Count: 720 Tweet ID:  783391753726550016 Time: 0.02027499259565957
Success Count: 721 Tweet ID:  783347506784731136 Time: 0.00959812116343528
Success Count: 722 Tweet ID:  783334639985389568 Time: 0.0035118853265885264
Success Count: 723 Tweet ID:  783085703974514689 Time: -0.012432625313522294
Success Count: 724 Tweet ID:  782969140009107456 Time: -0.0016455001023132354
Success Count: 725 Tweet ID:  782747134529531904 Time: 0.03252751153195277
Success Count: 726 Tweet ID:  782722598790725632 Time: -0.05575179305742495
Success Count: 727 Tweet ID:  782598640137187329 Time: -0.0010987620626110584
Success Count: 728 Tweet ID:  782305867769217024 Time: 0.007824998523574322
Success Count: 729 Tweet ID:  782021823840026624 Time: -0.0021488161582965404
Success Count: 730 Tweet ID:  781955203444699136 Time: 0.025003445422044024
Success Count: 731 Tweet ID:  781661882474196992 Time: -0.009610581357264891
Success Count: 732 Tweet ID:  781655249211752448 Time: 0.022495171666378155
Success Count: 733 Tweet ID:  781524693396357120 Time: -0.030723049625521526
Success Count: 734 Tweet ID:  781308096455073793 Time: 0.0015099483134690672
Success Count: 735 Tweet ID:  781251288990355457 Time: 0.0376354337495286
Success Count: 736 Tweet ID:  781163403222056960 Time: -0.00840836190036498
Success Count: 737 Tweet ID:  780931614150983680 Time: 0.010783349425764754
Success Count: 738 Tweet ID:  780858289093574656 Time: 0.007480266678612679
Success Count: 739 Tweet ID:  780800785462489090 Time: -0.004285549774067476
Success Count: 740 Tweet ID:  780601303617732608 Time: 0.006980348756769672
Success Count: 741 Tweet ID:  780543529827336192 Time: 0.029103225126164034
Success Count: 742 Tweet ID:  780496263422808064 Time: -0.0046959808096289635
Success Count: 743 Tweet ID:  780476555013349377 Time: -0.013664673635503277
Success Count: 744 Tweet ID:  780459368902959104 Time: 0.010594936233246699
Success Count: 745 Tweet ID:  780192070812196864 Time: 0.018869256717152894
Success Count: 746 Tweet ID:  780092040432480260 Time: 0.008960763603681698
Success Count: 747 Tweet ID:  780074436359819264 Time: 0.01380400123889558
Success Count: 748 Tweet ID:  779834332596887552 Time: -0.006326377624645829
Success Count: 749 Tweet ID:  779377524342161408 Time: -0.0015088155923876911
Success Count: 750 Tweet ID:  779124354206535695 Time: 0.010871703474549577
Success Count: 751 Tweet ID:  779123168116150273 Time: 0.0034144693054258823
Success Count: 752 Tweet ID:  779056095788752897 Time: 0.006929375260369852
Success Count: 753 Tweet ID:  778990705243029504 Time: -0.0053639224788639694
Success Count: 754 Tweet ID:  778774459159379968 Time: -0.02987877748091705
Success Count: 755 Tweet ID:  778764940568104960 Time: -0.004278753302060068
Success Count: 756 Tweet ID:  778748913645780993 Time: 0.010129378264537081
Success Count: 757 Tweet ID:  778650543019483137 Time: 0.030723804811714217
Success Count: 758 Tweet ID:  778624900596654080 Time: -0.004796417488250881
Success Count: 759 Tweet ID:  778408200802557953 Time: -0.0005814754695165902
Success Count: 760 Tweet ID:  778396591732486144 Time: 0.010431443486595526

Success Count: 761 Tweet ID:  778383385161035776 Time: -0.02001181829837151
Success Count: 762 Tweet ID:  778286810187399168 Time: 0.014509323460515589
Success Count: 763 Tweet ID:  778039087836069888 Time: 0.008229765895521268
Success Count: 764 Tweet ID:  778027034220126208 Time: -0.01194592277170159
Success Count: 765 Tweet ID:  777953400541634568 Time: 0.018318365386221558
Success Count: 766 Tweet ID:  777885040357281792 Time: 0.006526495824800804
Success Count: 767 Tweet ID:  777684233540206592 Time: 0.027465654275147244
Success Count: 768 Tweet ID:  777641927919427584 Time: -2.001182292588055e-05
Success Count: 769 Tweet ID:  777621514455814149 Time: -0.010137685050722212
Success Count: 770 Tweet ID:  777189768882946048 Time: 0.010658747516572475
Success Count: 771 Tweet ID:  776819012571455488 Time: -0.0342428642034065
Success Count: 772 Tweet ID:  776813020089548800 Time: 0.02305776806315407
Success Count: 773 Tweet ID:  776477788987613185 Time: -0.00658955195103772
Success Count: 774 Tweet ID:  776249906839351296 Time: 0.016044192132540047
Success Count: 775 Tweet ID:  776218204058357768 Time: -0.011886642489116639
Success Count: 776 Tweet ID:  776201521193218049 Time: 0.013482301845215261
Success Count: 777 Tweet ID:  776113305656188928 Time: -0.0031210884917527437
Success Count: 778 Tweet ID:  776088319444877312 Time: 0.0017565090383868665
Success Count: 779 Tweet ID:  775898661951791106 Time: 0.02808941886178218
Success Count: 780 Tweet ID:  775842724423557120 Time: 0.0072722192271612585
Success Count: 781 Tweet ID:  775733305207554048 Time: -0.003085973410634324
Success Count: 782 Tweet ID:  775729183532220416 Time: 0.022804410924436525
Success Count: 783 Tweet ID:  775364825476165632 Time: -0.01084300730144605
Success Count: 784 Tweet ID:  775350846108426240 Time: -0.00954714766703546
Failed to access Tweet ID: 775096608509886464
Success Count: 786 Tweet ID:  775085132600442880 Time: -0.01057907784706913
Success Count: 787 Tweet ID:  774757898236878852 Time: 0.012206076411530375
Success Count: 788 Tweet ID:  774639387460112384 Time: -0.0001415930746588856
Success Count: 789 Tweet ID:  774314403806253056 Time: 0.016052876511821523
Success Count: 790 Tweet ID:  773985732834758656 Time: -0.0016213349008467048
Success Count: 791 Tweet ID:  773922284943896577 Time: -8.835404878482223e-05
Success Count: 792 Tweet ID:  773704687002451968 Time: 0.012633876205654815
Success Count: 793 Tweet ID:  773670353721753600 Time: -0.0022673767525702715
Success Count: 794 Tweet ID:  773547596996571136 Time: -0.01356839036452584
Success Count: 795 Tweet ID:  773336787167145985 Time: 0.030970365507528186
Success Count: 796 Tweet ID:  773308824254029826 Time: -0.005745279777329415
Success Count: 797 Tweet ID:  773247561583001600 Time: 0.005956725392024964
Success Count: 798 Tweet ID:  773191612633579521 Time: 0.009393849584739655
Success Count: 799 Tweet ID:  772877495989305348 Time: 0.016690234071575105
Success Count: 800 Tweet ID:  772826264096874500 Time: 0.01653844627435319
Success Count: 801 Tweet ID:  772615324260794368 Time: -0.0077611872693523765
Success Count: 802 Tweet ID:  772581559778025472 Time: 0.01346644340083003
Success Count: 803 Tweet ID:  772193107915964416 Time: 0.016594705928582698
Success Count: 804 Tweet ID:  772152991789019136 Time: -0.0008133105002343655
Success Count: 805 Tweet ID:  772117678702071809 Time: -0.008268656732980162
Success Count: 806 Tweet ID:  772114945936949249 Time: -0.005792855023173615
Success Count: 807 Tweet ID:  772102971039580160 Time: 0.02924066476407461
Success Count: 808 Tweet ID:  771908950375665664 Time: 0.01594715367536992
Success Count: 809 Tweet ID:  771770456517009408 Time: 0.01767232347629033
Success Count: 810 Tweet ID:  771500966810099713 Time: -0.021858569292817265
Success Count: 811 Tweet ID:  771380798096281600 Time: 0.018495073512895033
Success Count: 812 Tweet ID:  771171053431250945 Time: 0.010627785843098536
Success Count: 813 Tweet ID:  771136648247640064 Time: 0.025906620314344764
Success Count: 814 Tweet ID:  771102124360998913 Time: -0.015399282972794026
Success Count: 815 Tweet ID:  771014301343748096 Time: 0.002351577451918274
Failed to access Tweet ID: 771004394259247104
Success Count: 817 Tweet ID:  770787852854652928 Time: -0.008084019442321733
Success Count: 818 Tweet ID:  770772759874076672 Time: 0.012935186241520569
Failed to access Tweet ID: 770743923962707968
Success Count: 820 Tweet ID:  770655142660169732 Time: 0.0061753450718242675
Success Count: 821 Tweet ID:  770414278348247044 Time: 0.0144749635073822
Success Count: 822 Tweet ID:  770293558247038976 Time: 0.014823093602899462
Success Count: 823 Tweet ID:  770093767776997377 Time: -0.0030300913495011628
Success Count: 824 Tweet ID:  770069151037685760 Time: -0.012662572407862172
Success Count: 825 Tweet ID:  769940425801170949 Time: 0.02082135298405774
Success Count: 826 Tweet ID:  769695466921623552 Time: 0.012432247720425949
Success Count: 827 Tweet ID:  769335591808995329 Time: 0.011106936755822971
Success Count: 828 Tweet ID:  769212283578875904 Time: -0.007468939205864444
Success Count: 829 Tweet ID:  768970937022709760 Time: 0.015053040755447
Success Count: 830 Tweet ID:  768909767477751808 Time: -0.009229224058799446
Success Count: 831 Tweet ID:  768855141948723200 Time: 0.019138472358463332
Success Count: 832 Tweet ID:  768609597686943744 Time: -0.002444462472340092
Success Count: 833 Tweet ID:  768596291618299904 Time: 0.017824111215304583
Success Count: 834 Tweet ID:  768554158521745409 Time: 0.027943294786382467
Success Count: 835 Tweet ID:  768473857036525572 Time: -0.012210607383167371
Success Count: 836 Tweet ID:  768193404517830656 Time: -0.008194650814402848
Success Count: 837 Tweet ID:  767884188863397888 Time: 0.022120988433016464
Success Count: 838 Tweet ID:  767754930266464257 Time: 0.017179202055558562
Success Count: 839 Tweet ID:  767500508068192258 Time: 0.014229157997760922
Success Count: 840 Tweet ID:  767191397493538821 Time: -0.00541149772470817
Success Count: 841 Tweet ID:  767122157629476866 Time: -0.03591101913480088
Success Count: 842 Tweet ID:  766864461642756096 Time: 0.010142216051463038
Success Count: 843 Tweet ID:  766793450729734144 Time: 0.011797910847235471
Success Count: 844 Tweet ID:  766714921925144576 Time: -0.015636781725334004
Success Count: 845 Tweet ID:  766693177336135680 Time: 0.0035488883149810135
Success Count: 846 Tweet ID:  766423258543644672 Time: 0.0020936892833560705
Success Count: 847 Tweet ID:  766313316352462849 Time: 0.011000458733178675
Success Count: 848 Tweet ID:  766078092750233600 Time: 0.016863921511685476
Success Count: 849 Tweet ID:  766069199026450432 Time: 0.015131200110772625
Success Count: 850 Tweet ID:  766008592277377025 Time: 0.002582657296443358
Success Count: 851 Tweet ID:  765719909049503744 Time: -0.019066354259848595
Success Count: 852 Tweet ID:  765669560888528897 Time: 0.02511747504468076
Success Count: 853 Tweet ID:  765395769549590528 Time: -0.022528398840222508
Success Count: 854 Tweet ID:  765371061932261376 Time: 0.0171727831766475
Success Count: 855 Tweet ID:  765222098633691136 Time: -0.018310813757125288
Success Count: 856 Tweet ID:  764857477905154048 Time: 0.0009658534545451403
Success Count: 857 Tweet ID:  764259802650378240 Time: 0.028061477816663682
Success Count: 858 Tweet ID:  763956972077010945 Time: 0.005359013885026798
Success Count: 859 Tweet ID:  763837565564780549 Time: -0.03426514146849513
Success Count: 860 Tweet ID:  763183847194451968 Time: 0.004475473251659423
Success Count: 861 Tweet ID:  763167063695355904 Time: 0.0005584429891314358
Success Count: 862 Tweet ID:  763103485927849985 Time: 0.024434430175460875
Success Count: 863 Tweet ID:  762699858130116608 Time: 0.0017534883809275925
Success Count: 864 Tweet ID:  762471784394268675 Time: 0.000865794310811907
Success Count: 865 Tweet ID:  762464539388485633 Time: 0.007128738303435966
Success Count: 866 Tweet ID:  762316489655476224 Time: -0.0010062546643894166
Success Count: 867 Tweet ID:  762035686371364864 Time: -0.011838689621072263
Success Count: 868 Tweet ID:  761976711479193600 Time: 0.01566963130608201
Success Count: 869 Tweet ID:  761750502866649088 Time: 0.009968151018256322

Success Count: 870 Tweet ID:  761745352076779520 Time: 0.02391336770961061
Success Count: 871 Tweet ID:  761672994376806400 Time: -0.007200478750746697
Success Count: 872 Tweet ID:  761599872357261312 Time: 0.01649426924996078
Success Count: 873 Tweet ID:  761371037149827077 Time: 0.018315344728762284
Success Count: 874 Tweet ID:  761334018830917632 Time: -0.012065993709256873
Success Count: 875 Tweet ID:  761292947749015552 Time: 0.010542452422669157
Success Count: 876 Tweet ID:  761227390836215808 Time: -0.0022156480990815908
Success Count: 877 Tweet ID:  761004547850530816 Time: -0.0028465867799241096
Success Count: 878 Tweet ID:  760893934457552897 Time: 0.010541697265580297
Success Count: 879 Tweet ID:  760656994973933572 Time: -0.012895540188765153
Success Count: 880 Tweet ID:  760641137271070720 Time: 0.01588523032842204
Success Count: 881 Tweet ID:  760539183865880579 Time: 0.00640151635161601
Success Count: 882 Tweet ID:  760521673607086080 Time: 0.011920624790946022
Success Count: 883 Tweet ID:  760290219849637889 Time: -0.004373526229755953
Success Count: 884 Tweet ID:  760252756032651264 Time: 0.0059438876050990075
Success Count: 885 Tweet ID:  760190180481531904 Time: 0.015286763722542673
Success Count: 886 Tweet ID:  760153949710192640 Time: -0.004928193433443084
Success Count: 887 Tweet ID:  759943073749200896 Time: -0.010625142778735608
Success Count: 888 Tweet ID:  759923798737051648 Time: 0.01956476180930622
Success Count: 889 Tweet ID:  759846353224826880 Time: 0.0012932165700476617
Success Count: 890 Tweet ID:  759793422261743616 Time: -0.006554059276822954
Success Count: 891 Tweet ID:  759566828574212096 Time: 0.0136159656685777
Success Count: 892 Tweet ID:  759557299618865152 Time: 0.0003031979431398213
Success Count: 893 Tweet ID:  759447681597108224 Time: 0.0021775123896077275
Success Count: 894 Tweet ID:  759446261539934208 Time: -0.005555356270633638

Rate limit reached. Sleeping for: 443

Success Count: 895 Tweet ID:  759197388317847553 Time: 0.01819451863411814
Success Count: 896 Tweet ID:  759159934323924993 Time: 0.039734786783810705
Success Count: 897 Tweet ID:  759099523532779520 Time: -0.003819614212261513
Success Count: 898 Tweet ID:  759047813560868866 Time: 0.0010496765025891364
Success Count: 899 Tweet ID:  758854675097526272 Time: -0.004265537951141596
Success Count: 900 Tweet ID:  758828659922702336 Time: 0.0006354695942718536
Success Count: 901 Tweet ID:  758740312047005698 Time: 0.036561592016369104
Success Count: 902 Tweet ID:  758474966123810816 Time: -0.03430780820781365
Success Count: 903 Tweet ID:  758467244762497024 Time: 0.007082673313561827
Success Count: 904 Tweet ID:  758405701903519748 Time: 0.0018093704420607537
Success Count: 905 Tweet ID:  758355060040593408 Time: -0.020689577067969367
Success Count: 906 Tweet ID:  758099635764359168 Time: 0.03925903409253806
Success Count: 907 Tweet ID:  758041019896193024 Time: -0.0332762555917725
Success Count: 908 Tweet ID:  757741869644341248 Time: 0.03463932473096065
Success Count: 909 Tweet ID:  757729163776290825 Time: -0.013436614448437467
Success Count: 910 Tweet ID:  757725642876129280 Time: 0.034547194838523865
Success Count: 911 Tweet ID:  757611664640446465 Time: 0.026648567902157083
Success Count: 912 Tweet ID:  757597904299253760 Time: 0.0021578781597781926
Success Count: 913 Tweet ID:  757596066325864448 Time: -0.008863347582519054
Success Count: 914 Tweet ID:  757400162377592832 Time: 0.02601989477989264
Success Count: 915 Tweet ID:  757393109802180609 Time: -0.0002495813532732427
Success Count: 916 Tweet ID:  757354760399941633 Time: 0.02456771640572697
Success Count: 917 Tweet ID:  756998049151549440 Time: 0.024659091111971065
Success Count: 918 Tweet ID:  756939218950160384 Time: 0.005152854428160936
Success Count: 919 Tweet ID:  756651752796094464 Time: 0.0036055255332030356
Success Count: 920 Tweet ID:  756526248105566208 Time: 0.01995480348705314
Success Count: 921 Tweet ID:  756303284449767430 Time: -0.002222066977992654
Success Count: 922 Tweet ID:  756288534030475264 Time: -0.014064154878724366
Success Count: 923 Tweet ID:  756275833623502848 Time: 0.008864102768711746
Success Count: 924 Tweet ID:  755955933503782912 Time: -0.004665019165258855
Success Count: 925 Tweet ID:  755206590534418437 Time: 0.021833648905158043
Success Count: 926 Tweet ID:  755110668769038337 Time: -0.01414986586314626
Success Count: 927 Tweet ID:  754874841593970688 Time: 0.01140031754039228
Success Count: 928 Tweet ID:  754856583969079297 Time: 0.0015424203302245587
Success Count: 929 Tweet ID:  754747087846248448 Time: 0.02493019460234791
Success Count: 930 Tweet ID:  754482103782404096 Time: -0.01621599172358401
Success Count: 931 Tweet ID:  754449512966619136 Time: -0.0014703022607136518
Success Count: 932 Tweet ID:  754120377874386944 Time: -0.003858505078824237
Failed to access Tweet ID: 754011816964026368
Success Count: 934 Tweet ID:  753655901052166144 Time: 0.01698965614195913
Success Count: 935 Tweet ID:  753420520834629632 Time: -0.0017025148845277727
Success Count: 936 Tweet ID:  753398408988139520 Time: -0.008693435927852988
Success Count: 937 Tweet ID:  753375668877008896 Time: 0.007471959834219888
Success Count: 938 Tweet ID:  753298634498793472 Time: 0.01854453669511713
Success Count: 939 Tweet ID:  753294487569522689 Time: 6.56991614960134e-05
Success Count: 940 Tweet ID:  753039830821511168 Time: -0.007403617608360946
Success Count: 941 Tweet ID:  753026973505581056 Time: 0.021549330063862726
Success Count: 942 Tweet ID:  752932432744185856 Time: -0.02403306102496572
Success Count: 943 Tweet ID:  752917284578922496 Time: -0.002853005629731342
Success Count: 944 Tweet ID:  752701944171524096 Time: 0.031947168812621385
Success Count: 945 Tweet ID:  752682090207055872 Time: -0.00999911269173026
Success Count: 946 Tweet ID:  752660715232722944 Time: -0.008198049035854638
Success Count: 947 Tweet ID:  752568224206688256 Time: 0.029219520220067352
Success Count: 948 Tweet ID:  752519690950500352 Time: 0.009271890739910305
Success Count: 949 Tweet ID:  752334515931054080 Time: -0.0217437845421955
Success Count: 950 Tweet ID:  752309394570878976 Time: 0.020362213923363015
Success Count: 951 Tweet ID:  752173152931807232 Time: -0.012853628635639325
Success Count: 952 Tweet ID:  751950017322246144 Time: 0.03739680227590725
Success Count: 953 Tweet ID:  751937170840121344 Time: -0.005932182568358257
Success Count: 954 Tweet ID:  751830394383790080 Time: -0.025839788373559713
Success Count: 955 Tweet ID:  751793661361422336 Time: 0.027687672118190676
Success Count: 956 Tweet ID:  751598357617971201 Time: 0.0025131822912953794
Success Count: 957 Tweet ID:  751583847268179968 Time: 0.018031403451459482
Success Count: 958 Tweet ID:  751538714308972544 Time: -0.0009273400937672704
Success Count: 959 Tweet ID:  751456908746354688 Time: -0.010098416620166972
Success Count: 960 Tweet ID:  751251247299190784 Time: 0.021012409211834893
Success Count: 961 Tweet ID:  751205363882532864 Time: 0.01648671762086451
Success Count: 962 Tweet ID:  751132876104687617 Time: -0.01496279879938811
Success Count: 963 Tweet ID:  750868782890057730 Time: -0.019015380792552605
Success Count: 964 Tweet ID:  750719632563142656 Time: -0.0009364020370412618
Success Count: 965 Tweet ID:  750506206503038976 Time: -0.0066412806045264006
Success Count: 966 Tweet ID:  750429297815552001 Time: 0.0012671634030994028
Success Count: 967 Tweet ID:  750383411068534784 Time: 0.001616426307009533
Success Count: 968 Tweet ID:  750381685133418496 Time: 0.023962075705640018
Success Count: 969 Tweet ID:  750147208377409536 Time: -0.009137094166362658
Success Count: 970 Tweet ID:  750132105863102464 Time: 0.018844713951693848
Success Count: 971 Tweet ID:  750117059602808832 Time: 0.009385165205458179
Success Count: 972 Tweet ID:  750101899009982464 Time: 0.005490789859322831
Success Count: 973 Tweet ID:  750086836815486976 Time: 0.015278456907253712
Success Count: 974 Tweet ID:  750071704093859840 Time: -0.006234247732209042
Success Count: 975 Tweet ID:  750056684286914561 Time: -0.012345403956715018
Success Count: 976 Tweet ID:  750041628174217216 Time: -0.0019860785687342286
Success Count: 977 Tweet ID:  750026558547456000 Time: 0.020540432393318042
Success Count: 978 Tweet ID:  750011400160841729 Time: -0.007429293153109029
Success Count: 979 Tweet ID:  749996283729883136 Time: 0.009167678246740252
Success Count: 980 Tweet ID:  749981277374128128 Time: 0.01875598230981268
Success Count: 981 Tweet ID:  749774190421639168 Time: -0.004840972105739638
Success Count: 982 Tweet ID:  749417653287129088 Time: 0.020502674247836694
Success Count: 983 Tweet ID:  749403093750648834 Time: -0.026937795337289572
Success Count: 984 Tweet ID:  749395845976588288 Time: 0.03129848383832723
Success Count: 985 Tweet ID:  749317047558017024 Time: 0.0029700559098273516
Success Count: 986 Tweet ID:  749075273010798592 Time: -0.0032268113282043487
Success Count: 987 Tweet ID:  749064354620928000 Time: 0.03007285436615348
Success Count: 988 Tweet ID:  749036806121881602 Time: -0.020267818559659645
Success Count: 989 Tweet ID:  748977405889503236 Time: 0.012353333178907633
Success Count: 990 Tweet ID:  748932637671223296 Time: 0.025870750076137483
Success Count: 991 Tweet ID:  748705597323898880 Time: -0.00437126075848937
Success Count: 992 Tweet ID:  748699167502000129 Time: 0.03516567332553677
Success Count: 993 Tweet ID:  748692773788876800 Time: -0.005873657471965998
Success Count: 994 Tweet ID:  748575535303884801 Time: -0.010114275006344542
Success Count: 995 Tweet ID:  748568946752774144 Time: 0.01630887677310966
Success Count: 996 Tweet ID:  748346686624440324 Time: 0.008971713512437418
Success Count: 997 Tweet ID:  748337862848962560 Time: -0.0010130511072929949
Success Count: 998 Tweet ID:  748324050481647620 Time: -0.009418014786206186
Success Count: 999 Tweet ID:  748307329658011649 Time: 0.00138610161957331
Success Count: 1000 Tweet ID:  748220828303695873 Time: -0.0065438645833637565
Success Count: 1001 Tweet ID:  747963614829678593 Time: 0.01467621442861855
Success Count: 1002 Tweet ID:  747933425676525569 Time: 0.021742651762906462

Success Count: 1003 Tweet ID:  747885874273214464 Time: -0.017158812639536336
Success Count: 1004 Tweet ID:  747844099428986880 Time: 0.02099579563946463
Success Count: 1005 Tweet ID:  747816857231626240 Time: -0.010349508316721767
Success Count: 1006 Tweet ID:  747651430853525504 Time: 0.01859890841296874
Success Count: 1007 Tweet ID:  747648653817413632 Time: 0.02011603079154156
Success Count: 1008 Tweet ID:  747600769478692864 Time: 0.003902682161424309
Success Count: 1009 Tweet ID:  747594051852075008 Time: -0.007428915560012683
Success Count: 1010 Tweet ID:  747512671126323200 Time: 0.00019332172814756632
Success Count: 1011 Tweet ID:  747461612269887489 Time: 0.015551448304904625
Success Count: 1012 Tweet ID:  747439450712596480 Time: 0.004130363784497604
Success Count: 1013 Tweet ID:  747242308580548608 Time: 0.008725530380615965
Success Count: 1014 Tweet ID:  747219827526344708 Time: -0.0021903501183260232
Success Count: 1015 Tweet ID:  747204161125646336 Time: 0.0022050758125260472
Success Count: 1016 Tweet ID:  747103485104099331 Time: 0.015704368823207915
Success Count: 1017 Tweet ID:  746906459439529985 Time: -0.017746329453075305
Success Count: 1018 Tweet ID:  746872823977771008 Time: 0.0036470594932325184
Success Count: 1019 Tweet ID:  746818907684614144 Time: -0.0022798369463998824
Success Count: 1020 Tweet ID:  746790600704425984 Time: 0.013275387173052877
Success Count: 1021 Tweet ID:  746757706116112384 Time: 0.0011633285321295261
Success Count: 1022 Tweet ID:  746726898085036033 Time: -0.0066495874198153615
Success Count: 1023 Tweet ID:  746542875601690625 Time: -0.007357552647590637
Success Count: 1024 Tweet ID:  746521445350707200 Time: -0.018029515544185415
Success Count: 1025 Tweet ID:  746507379341139972 Time: 0.02778773123282008
Success Count: 1026 Tweet ID:  746369468511756288 Time: -0.002884344896301627
Success Count: 1027 Tweet ID:  746131877086527488 Time: 0.008545801567379385
Success Count: 1028 Tweet ID:  746056683365994496 Time: 0.001051186816766858
Success Count: 1029 Tweet ID:  745789745784041472 Time: 0.009965130331693217
Success Count: 1030 Tweet ID:  745712589599014916 Time: -0.010047443123767152
Success Count: 1031 Tweet ID:  745433870967832576 Time: 0.006826295517385006
Success Count: 1032 Tweet ID:  745422732645535745 Time: -0.00038097973447293043
Success Count: 1033 Tweet ID:  745314880350101504 Time: 0.001501263934187591
Success Count: 1034 Tweet ID:  745074613265149952 Time: 0.012872130115283653
Success Count: 1035 Tweet ID:  745057283344719872 Time: 0.023791786457877606
Success Count: 1036 Tweet ID:  744995568523612160 Time: 0.009072527755051851
Success Count: 1037 Tweet ID:  744971049620602880 Time: -0.0046521814074367285
Success Count: 1038 Tweet ID:  744709971296780288 Time: 0.014790621615247801
Success Count: 1039 Tweet ID:  744334592493166593 Time: -0.011301013611955568
Success Count: 1040 Tweet ID:  744234799360020481 Time: 0.01767156829009764
Success Count: 1041 Tweet ID:  744223424764059648 Time: 0.017906423978274688
Success Count: 1042 Tweet ID:  743980027717509120 Time: 0.005775863828603178
Success Count: 1043 Tweet ID:  743895849529389061 Time: -0.027224757272051647
Success Count: 1044 Tweet ID:  743835915802583040 Time: 0.03115877870004624
Success Count: 1045 Tweet ID:  743609206067040256 Time: -0.003774682030780241
Success Count: 1046 Tweet ID:  743595368194129920 Time: -0.0007056997856125236
Success Count: 1047 Tweet ID:  743545585370791937 Time: 0.00740248485817574
Success Count: 1048 Tweet ID:  743510151680958465 Time: -0.005806447967188433
Success Count: 1049 Tweet ID:  743253157753532416 Time: 0.022272776201134548
Success Count: 1050 Tweet ID:  743222593470234624 Time: 0.010042156965937465
Success Count: 1051 Tweet ID:  743210557239623680 Time: 0.011544176057213917
Success Count: 1052 Tweet ID:  742534281772302336 Time: -0.00831396653666161
Success Count: 1053 Tweet ID:  742528092657332225 Time: 0.015915814437903464
Success Count: 1054 Tweet ID:  742465774154047488 Time: 0.0005505137960426509
Success Count: 1055 Tweet ID:  742423170473463808 Time: -0.028477572603151202
Success Count: 1056 Tweet ID:  742385895052087300 Time: -0.009396870213095099
Success Count: 1057 Tweet ID:  742161199639494656 Time: 0.03624970972305164
Success Count: 1058 Tweet ID:  742150209887731712 Time: 0.026655741996364668
Success Count: 1059 Tweet ID:  741793263812808706 Time: 0.0019664443389046937
Success Count: 1060 Tweet ID:  741743634094141440 Time: -0.015474044106667861
Success Count: 1061 Tweet ID:  741438259667034112 Time: -0.0009564138599671423
Success Count: 1062 Tweet ID:  741303864243200000 Time: 0.03134001779835671
Success Count: 1063 Tweet ID:  741099773336379392 Time: 0.011913073190953583
Success Count: 1064 Tweet ID:  741067306818797568 Time: -0.00605225347680971
Success Count: 1065 Tweet ID:  740995100998766593 Time: 0.005328429804649204
Success Count: 1066 Tweet ID:  740711788199743490 Time: -0.004990116780390963
Success Count: 1067 Tweet ID:  740699697422163968 Time: 0.0033389530144631863
Success Count: 1068 Tweet ID:  740676976021798912 Time: -0.0005833633767906576
Success Count: 1069 Tweet ID:  740373189193256964 Time: 0.030073987058131024
Success Count: 1070 Tweet ID:  740365076218183684 Time: -0.029592948296340182
Success Count: 1071 Tweet ID:  740359016048689152 Time: 0.010936269885860384
Success Count: 1072 Tweet ID:  740214038584557568 Time: 0.002816757798427716
Success Count: 1073 Tweet ID:  739979191639244800 Time: 0.025640047795604914
Success Count: 1074 Tweet ID:  739932936087216128 Time: 0.0024036836985033005
Success Count: 1075 Tweet ID:  739844404073074688 Time: 0.006583133043022826
Success Count: 1076 Tweet ID:  739623569819336705 Time: -0.006278424814809114
Success Count: 1077 Tweet ID:  739606147276148736 Time: 0.0015329807938542217
Success Count: 1078 Tweet ID:  739544079319588864 Time: 0.023630936775589362
Success Count: 1079 Tweet ID:  739485634323156992 Time: 0.01997481530997902
Success Count: 1080 Tweet ID:  739238157791694849 Time: -0.007723806687863544
Success Count: 1081 Tweet ID:  738891149612572673 Time: 0.012178512959508225
Success Count: 1082 Tweet ID:  738885046782832640 Time: 0.02200016236747615
Success Count: 1083 Tweet ID:  738883359779196928 Time: -0.017026659130351618
Success Count: 1084 Tweet ID:  738537504001953792 Time: 0.034598923521116376
Success Count: 1085 Tweet ID:  738402415918125056 Time: -0.005110942904138938
Success Count: 1086 Tweet ID:  738184450748633089 Time: -0.01662113663041964
Success Count: 1087 Tweet ID:  738166403467907072 Time: -0.012840035720728338
Success Count: 1088 Tweet ID:  738156290900254721 Time: 0.02588094479870051
Success Count: 1089 Tweet ID:  737826014890496000 Time: 0.005578388751018792
Success Count: 1090 Tweet ID:  737800304142471168 Time: -0.016336817789124325
Success Count: 1091 Tweet ID:  737678689543020544 Time: 0.007767228584270924
Success Count: 1092 Tweet ID:  737445876994609152 Time: 0.002607955248095095
Success Count: 1093 Tweet ID:  737322739594330112 Time: 0.0017500901594758034
Success Count: 1094 Tweet ID:  737310737551491075 Time: -0.00820862129330635
Success Count: 1095 Tweet ID:  736736130620620800 Time: 0.02849267586134374
Success Count: 1096 Tweet ID:  736392552031657984 Time: -0.0035001803189516068
Success Count: 1097 Tweet ID:  736365877722001409 Time: -0.02793045702856034
Success Count: 1098 Tweet ID:  736225175608430592 Time: 0.0030319792858790606
Success Count: 1099 Tweet ID:  736010884653420544 Time: -0.000992284156382084
Success Count: 1100 Tweet ID:  735991953473572864 Time: -0.0008121777791529894
Success Count: 1101 Tweet ID:  735648611367784448 Time: -0.0003896640846505761
Success Count: 1102 Tweet ID:  735635087207878657 Time: 0.013739057234488428
Success Count: 1103 Tweet ID:  735274964362878976 Time: 0.01055226955213584
Success Count: 1104 Tweet ID:  735256018284875776 Time: 0.014904273673892021
Success Count: 1105 Tweet ID:  735137028879360001 Time: 0.013754915649769828
Success Count: 1106 Tweet ID:  734912297295085568 Time: 0.0011199066357221454
Success Count: 1107 Tweet ID:  734787690684657664 Time: -0.0012263846292626113
Success Count: 1108 Tweet ID:  734776360183431168 Time: -0.008483123034238815

Success Count: 1109 Tweet ID:  734559631394082816 Time: -0.0043150011042598635
Success Count: 1110 Tweet ID:  733828123016450049 Time: -0.0025569817807991058
Success Count: 1111 Tweet ID:  733822306246479872 Time: 0.004129608627408743
Success Count: 1112 Tweet ID:  733482008106668032 Time: 0.022516316239489242
Success Count: 1113 Tweet ID:  733460102733135873 Time: 0.005410742567619309
Success Count: 1114 Tweet ID:  733109485275860992 Time: 0.0010481661884114146
Success Count: 1115 Tweet ID:  732732193018155009 Time: 0.00989716566982679
Success Count: 1116 Tweet ID:  732726085725589504 Time: -0.021908032475039363
Success Count: 1117 Tweet ID:  732585889486888962 Time: 0.03056068962905556
Success Count: 1118 Tweet ID:  732375214819057664 Time: -0.030128358805086464
Success Count: 1119 Tweet ID:  732005617171337216 Time: -0.0061575987201649696
Success Count: 1120 Tweet ID:  731285275100512256 Time: 0.009265471890103072
Success Count: 1121 Tweet ID:  731156023742988288 Time: 0.02072846793453209
Success Count: 1122 Tweet ID:  730924654643314689 Time: -0.011698229325702414
Success Count: 1123 Tweet ID:  730573383004487680 Time: 0.0051086774037685245
Success Count: 1124 Tweet ID:  730427201120833536 Time: -0.0071906616212800145
Success Count: 1125 Tweet ID:  730211855403241472 Time: 0.007933364424388856
Success Count: 1126 Tweet ID:  730196704625098752 Time: -0.002665347623405978
Success Count: 1127 Tweet ID:  729854734790754305 Time: -0.0024550347588956356
Success Count: 1128 Tweet ID:  729838605770891264 Time: -0.002669878624146804
Success Count: 1129 Tweet ID:  729823566028484608 Time: 0.03188222480821423
Success Count: 1130 Tweet ID:  729463711119904772 Time: -0.0291311661421787
Success Count: 1131 Tweet ID:  729113531270991872 Time: 0.013888579473132268
Success Count: 1132 Tweet ID:  728986383096946689 Time: -0.0005384311662055552
Success Count: 1133 Tweet ID:  728760639972315136 Time: -0.002895672310842201
Success Count: 1134 Tweet ID:  728751179681943552 Time: -0.0002382539096288383
Success Count: 1135 Tweet ID:  728653952833728512 Time: 0.01639572047861293
Success Count: 1136 Tweet ID:  728409960103686147 Time: 0.017371391033520922
Success Count: 1137 Tweet ID:  728387165835677696 Time: -0.014642987283878028
Success Count: 1138 Tweet ID:  728046963732717569 Time: 0.007467051298590377
Success Count: 1139 Tweet ID:  728035342121635841 Time: -0.006771168642444536
Success Count: 1140 Tweet ID:  728015554473250816 Time: 0.008222591830417514
Success Count: 1141 Tweet ID:  727685679342333952 Time: -0.0023145744926296175
Success Count: 1142 Tweet ID:  727644517743104000 Time: -0.0027722032100427896
Success Count: 1143 Tweet ID:  727524757080539137 Time: 0.005024099140428007
Success Count: 1144 Tweet ID:  727314416056803329 Time: -0.0025358372076880187
Success Count: 1145 Tweet ID:  727286334147182592 Time: 0.007299782708287239
Success Count: 1146 Tweet ID:  727175381690781696 Time: 0.024827870045555755
Success Count: 1147 Tweet ID:  727155742655025152 Time: 0.0007959417416714132
Success Count: 1148 Tweet ID:  726935089318363137 Time: 0.005854400806128979
Success Count: 1149 Tweet ID:  726887082820554753 Time: 0.01971919264178723
Success Count: 1150 Tweet ID:  726828223124897792 Time: -0.0003469973453320563
Success Count: 1151 Tweet ID:  726224900189511680 Time: 0.0038675670803058892
Success Count: 1152 Tweet ID:  725842289046749185 Time: 0.006014872953528538
Success Count: 1153 Tweet ID:  725786712245440512 Time: 0.0245182532526087
Success Count: 1154 Tweet ID:  725729321944506368 Time: 0.0005240830942057073
Success Count: 1155 Tweet ID:  725458796924002305 Time: -0.002710657427087426
Success Count: 1156 Tweet ID:  724983749226668032 Time: -0.00585515596321784
Success Count: 1157 Tweet ID:  724771698126512129 Time: 0.025534702552249655
Success Count: 1158 Tweet ID:  724405726123311104 Time: -0.012286123674130067
Success Count: 1159 Tweet ID:  724049859469295616 Time: 0.015579011756926775
Success Count: 1160 Tweet ID:  724046343203856385 Time: 0.03622101357905194
Success Count: 1161 Tweet ID:  724004602748780546 Time: 0.0035084871051367372
Success Count: 1162 Tweet ID:  723912936180330496 Time: 0.0008654167468193918
Success Count: 1163 Tweet ID:  723688335806480385 Time: -0.01131007558433339
Success Count: 1164 Tweet ID:  723673163800948736 Time: 0.023377579607767984
Success Count: 1165 Tweet ID:  723179728551723008 Time: -0.005982400936773047
Success Count: 1166 Tweet ID:  722974582966214656 Time: -0.00513661841978319
Success Count: 1167 Tweet ID:  722613351520608256 Time: -4.568736767396331e-05
Success Count: 1168 Tweet ID:  721503162398597120 Time: -0.00019520960631780326
Success Count: 1169 Tweet ID:  721001180231503872 Time: -0.0034012539545074105
Success Count: 1170 Tweet ID:  720785406564900865 Time: 0.016009454644517973
Success Count: 1171 Tweet ID:  720775346191278080 Time: -0.0037482513289432973
Success Count: 1172 Tweet ID:  720415127506415616 Time: -0.005202317610383034
Success Count: 1173 Tweet ID:  720389942216527872 Time: 0.004869668307946995
Success Count: 1174 Tweet ID:  720340705894408192 Time: 0.028502493019914255
Success Count: 1175 Tweet ID:  720059472081784833 Time: -0.021216303226538002
Success Count: 1176 Tweet ID:  720043174954147842 Time: -0.0012120365572627634
Success Count: 1177 Tweet ID:  719991154352222208 Time: -0.02141189042595215
Success Count: 1178 Tweet ID:  719704490224398336 Time: -0.008955099910963327
Success Count: 1179 Tweet ID:  719551379208073216 Time: 0.017227532458491623
Success Count: 1180 Tweet ID:  719367763014393856 Time: 0.008493317756801844
Success Count: 1181 Tweet ID:  719339463458033665 Time: 0.01334108630544506
Success Count: 1182 Tweet ID:  719332531645071360 Time: 0.004209278296912089
Success Count: 1183 Tweet ID:  718971898235854848 Time: 0.0028851000824943185
Success Count: 1184 Tweet ID:  718939241951195136 Time: 0.010050463781226426
Success Count: 1185 Tweet ID:  718631497683582976 Time: -0.014548969484167174
Success Count: 1186 Tweet ID:  718613305783398402 Time: -0.0012724495900329202
Success Count: 1187 Tweet ID:  718540630683709445 Time: 0.005652394727803767
Success Count: 1188 Tweet ID:  718460005985447936 Time: -0.021272940444760025
Success Count: 1189 Tweet ID:  718454725339934721 Time: 0.02541916264453903
Success Count: 1190 Tweet ID:  718246886998687744 Time: 0.0029609939083456993
Success Count: 1191 Tweet ID:  718234618122661888 Time: -0.0011822076339740306
Success Count: 1192 Tweet ID:  717841801130979328 Time: -0.021958628407446668
Success Count: 1193 Tweet ID:  717790033953034240 Time: 0.040898492879932746
Success Count: 1194 Tweet ID:  717537687239008257 Time: 0.0010138062643818557
Success Count: 1195 Tweet ID:  717428917016076293 Time: 0.0013800603046547621
Success Count: 1196 Tweet ID:  717421804990701568 Time: -0.010182239697314799
Success Count: 1197 Tweet ID:  717047459982213120 Time: 0.029864051815820858
Success Count: 1198 Tweet ID:  717009362452090881 Time: 0.05441893043462187
Success Count: 1199 Tweet ID:  716802964044845056 Time: -0.014985076122684404
Success Count: 1200 Tweet ID:  716791146589110272 Time: -0.0021831761114299297
Success Count: 1201 Tweet ID:  716730379797970944 Time: 0.0012682961532846093
Success Count: 1202 Tweet ID:  716447146686459905 Time: 0.0018172996351495385
Success Count: 1203 Tweet ID:  716439118184652801 Time: 0.021837047184817493
Success Count: 1204 Tweet ID:  716285507865542656 Time: -0.006410200730897486
Success Count: 1205 Tweet ID:  716080869887381504 Time: 0.007392667728709057
Success Count: 1206 Tweet ID:  715928423106027520 Time: 0.004168499493971467
Success Count: 1207 Tweet ID:  715758151270801409 Time: 0.004813408653717488
Success Count: 1208 Tweet ID:  715733265223708672 Time: 0.025567929755197838
Success Count: 1209 Tweet ID:  715704790270025728 Time: -0.009266604611184448
Success Count: 1210 Tweet ID:  715696743237730304 Time: 0.010336292965803295
Success Count: 1211 Tweet ID:  715680795826982913 Time: -0.00674662584788166
Success Count: 1212 Tweet ID:  715360349751484417 Time: 0.008980397891718894
Success Count: 1213 Tweet ID:  715342466308784130 Time: 0.01776936190435663
Success Count: 1214 Tweet ID:  715220193576927233 Time: 0.009947761602234095

Success Count: 1215 Tweet ID:  715200624753819648 Time: -0.019609316455898806
Success Count: 1216 Tweet ID:  715009755312439296 Time: -0.004478871473111212
Success Count: 1217 Tweet ID:  714982300363173890 Time: 0.007425517338560894
Success Count: 1218 Tweet ID:  714962719905021952 Time: 0.018746920337434858
Success Count: 1219 Tweet ID:  714957620017307648 Time: 0.010806004283949733
Success Count: 1220 Tweet ID:  714631576617938945 Time: 0.028729419398587197
Success Count: 1221 Tweet ID:  714606013974974464 Time: -0.011526052170665935
Success Count: 1222 Tweet ID:  714485234495041536 Time: -0.018211887392681092
Success Count: 1223 Tweet ID:  714258258790387713 Time: 0.03008191630942747
Success Count: 1224 Tweet ID:  714251586676113411 Time: -0.020678249595221132
Success Count: 1225 Tweet ID:  714214115368108032 Time: -0.009806546120671555
Success Count: 1226 Tweet ID:  714141408463036416 Time: 0.014020732982316986
Success Count: 1227 Tweet ID:  713919462244790272 Time: -0.0070660597702953964
Success Count: 1228 Tweet ID:  713909862279876608 Time: 0.021999029588187113
Success Count: 1229 Tweet ID:  713900603437621249 Time: -0.01488426185096614
Success Count: 1230 Tweet ID:  713761197720473600 Time: -0.004622352455044165
Success Count: 1231 Tweet ID:  713411074226274305 Time: -0.006778720242436975
Success Count: 1232 Tweet ID:  713177543487135744 Time: 0.01017544325441122
Success Count: 1233 Tweet ID:  713175907180089344 Time: -0.004195685382001102
Success Count: 1234 Tweet ID:  712809025985978368 Time: -0.003641018207417801
Success Count: 1235 Tweet ID:  712717840512598017 Time: -0.0008895819773897529
Success Count: 1236 Tweet ID:  712668654853337088 Time: 0.03354320573271252
Success Count: 1237 Tweet ID:  712438159032893441 Time: -0.005103768809931353
Success Count: 1238 Tweet ID:  712309440758808576 Time: -0.030339049291796982
Success Count: 1239 Tweet ID:  712097430750289920 Time: 0.02400209938059561
Success Count: 1240 Tweet ID:  712092745624633345 Time: 0.004871933808317408
Success Count: 1241 Tweet ID:  712085617388212225 Time: -0.0056561705423519015
Success Count: 1242 Tweet ID:  712065007010385924 Time: -0.013926337618613616
Success Count: 1243 Tweet ID:  711998809858043904 Time: -0.013944839127361774
Success Count: 1244 Tweet ID:  711968124745228288 Time: 0.03606922578183003
Success Count: 1245 Tweet ID:  711743778164514816 Time: -0.00034737493842840195
Success Count: 1246 Tweet ID:  711732680602345472 Time: 0.011729946185369045
Success Count: 1247 Tweet ID:  711694788429553666 Time: 0.00042289128759875894
Success Count: 1248 Tweet ID:  711652651650457602 Time: 0.021713955589802936
Success Count: 1249 Tweet ID:  711363825979756544 Time: 0.012877038709120825
Success Count: 1250 Tweet ID:  711306686208872448 Time: 0.004932346870191395
Success Count: 1251 Tweet ID:  711008018775851008 Time: 0.014559919305611402
Success Count: 1252 Tweet ID:  710997087345876993 Time: 0.011641214514384046
Success Count: 1253 Tweet ID:  710844581445812225 Time: -0.001250927452929318
Success Count: 1254 Tweet ID:  710833117892898816 Time: 0.009902074263663962
Success Count: 1255 Tweet ID:  710658690886586372 Time: -0.005602176388492808
Success Count: 1256 Tweet ID:  710609963652087808 Time: 0.013337688083993271
Success Count: 1257 Tweet ID:  710588934686908417 Time: -0.006109645881224424
Success Count: 1258 Tweet ID:  710296729921429505 Time: -0.004514364147325978
Success Count: 1259 Tweet ID:  710283270106132480 Time: 0.03533369707292877
Success Count: 1260 Tweet ID:  710272297844797440 Time: -0.007038873911369592
Success Count: 1261 Tweet ID:  710269109699739648 Time: 0.009407442499650642
Success Count: 1262 Tweet ID:  710153181850935296 Time: -0.006823274859925732
Success Count: 1263 Tweet ID:  710140971284037632 Time: 0.01354158209869638
Success Count: 1264 Tweet ID:  710117014656950272 Time: -0.039989654236705974
Success Count: 1265 Tweet ID:  709918798883774466 Time: -0.0006879534630570561
Success Count: 1266 Tweet ID:  709901256215666688 Time: 0.00044441339559853077
Success Count: 1267 Tweet ID:  709852847387627521 Time: -0.004191909567452967
Success Count: 1268 Tweet ID:  709566166965075968 Time: 0.015466870041564107
Success Count: 1269 Tweet ID:  709556954897764353 Time: -0.001344945194432512
Success Count: 1270 Tweet ID:  709519240576036864 Time: -0.022187065216712654
Success Count: 1271 Tweet ID:  709449600415961088 Time: 0.004035213263705373
Success Count: 1272 Tweet ID:  709409458133323776 Time: 0.0011988212063442916
Success Count: 1273 Tweet ID:  709225125749587968 Time: 0.01389839660259895
Success Count: 1274 Tweet ID:  709207347839836162 Time: 0.0002541123249102384
Success Count: 1275 Tweet ID:  709198395643068416 Time: -0.004484157572733238
Success Count: 1276 Tweet ID:  709179584944730112 Time: -0.00972347822971642
Success Count: 1277 Tweet ID:  709158332880297985 Time: 0.02383898416883312
Success Count: 1278 Tweet ID:  709042156699303936 Time: 0.010506582213565707
Success Count: 1279 Tweet ID:  708853462201716736 Time: 0.031480100500630215
Success Count: 1280 Tweet ID:  708845821941387268 Time: -0.005803427338832989
Success Count: 1281 Tweet ID:  708834316713893888 Time: 0.007986980985151604
Success Count: 1282 Tweet ID:  708810915978854401 Time: 0.02603235494461842
Success Count: 1283 Tweet ID:  708738143638450176 Time: -0.0008461601100862026
Success Count: 1284 Tweet ID:  708711088997666817 Time: 0.026546620909357443
Success Count: 1285 Tweet ID:  708479650088034305 Time: -0.00788616674253717
Success Count: 1286 Tweet ID:  708469915515297792 Time: 0.02267187979305163
Success Count: 1287 Tweet ID:  708400866336894977 Time: -0.041902859637048095
Success Count: 1288 Tweet ID:  708356463048204288 Time: 0.010585496725980192
Success Count: 1289 Tweet ID:  708349470027751425 Time: 0.018535097158746794
Success Count: 1290 Tweet ID:  708149363256774660 Time: 0.0013464555668178946
Success Count: 1291 Tweet ID:  708130923141795840 Time: -0.0063218466530088335
Success Count: 1292 Tweet ID:  708119489313951744 Time: 0.05270357776316814
Success Count: 1293 Tweet ID:  708109389455101952 Time: -0.013675623515155166
Success Count: 1294 Tweet ID:  708026248782585858 Time: 0.007986225828062743
Success Count: 1295 Tweet ID:  707995814724026368 Time: 0.003547000407706946
Success Count: 1296 Tweet ID:  707983188426153984 Time: -0.010483927326276898
Success Count: 1297 Tweet ID:  707969809498152960 Time: -0.007996798114618286
Success Count: 1298 Tweet ID:  707776935007539200 Time: 0.008865990705089644
Success Count: 1299 Tweet ID:  707741517457260545 Time: -0.003301572462078184
Success Count: 1300 Tweet ID:  707738799544082433 Time: 0.00031867873622104526
Success Count: 1301 Tweet ID:  707693576495472641 Time: -0.0008110450289677829
Success Count: 1302 Tweet ID:  707629649552134146 Time: -0.0014982432767283171
Success Count: 1303 Tweet ID:  707610948723478529 Time: 0.01908938674023375
Success Count: 1304 Tweet ID:  707420581654872064 Time: 0.005296335410093889
Success Count: 1305 Tweet ID:  707411934438625280 Time: 0.01230009421124123
Success Count: 1306 Tweet ID:  707387676719185920 Time: 0.008379665727261454
Success Count: 1307 Tweet ID:  707377100785885184 Time: 0.0025886986404657364
Success Count: 1308 Tweet ID:  707315916783140866 Time: 0.0030557668942492455
Success Count: 1309 Tweet ID:  707297311098011648 Time: -0.028846847300883383
Success Count: 1310 Tweet ID:  707059547140169728 Time: -0.021852905600098893
Success Count: 1311 Tweet ID:  707038192327901184 Time: 0.028834764700150117
Success Count: 1312 Tweet ID:  707021089608753152 Time: 0.005590848944848403
Success Count: 1313 Tweet ID:  707014260413456384 Time: -0.008321895758854225
Success Count: 1314 Tweet ID:  706904523814649856 Time: -0.01724867706070654
Success Count: 1315 Tweet ID:  706901761596989440 Time: 0.022316198039334267
Success Count: 1316 Tweet ID:  706681918348251136 Time: 0.005054683279013261
Success Count: 1317 Tweet ID:  706644897839910912 Time: -0.0037924283533357084
Success Count: 1318 Tweet ID:  706593038911545345 Time: -0.01657884754240513
Success Count: 1319 Tweet ID:  706538006853918722 Time: 0.025112944043939933
Success Count: 1320 Tweet ID:  706516534877929472 Time: -0.001345322816632688

Success Count: 1321 Tweet ID:  706346369204748288 Time: 0.010429177986225113
Success Count: 1322 Tweet ID:  706310011488698368 Time: 0.021221211791271344
Success Count: 1323 Tweet ID:  706291001778950144 Time: 0.036722064163768664
Success Count: 1324 Tweet ID:  706265994973601792 Time: -0.011214169877348468
Success Count: 1325 Tweet ID:  706169069255446529 Time: -0.012013887462671846
Success Count: 1326 Tweet ID:  706166467411222528 Time: 0.037913333741016686
Success Count: 1327 Tweet ID:  706153300320784384 Time: -0.024454441969282925
Success Count: 1328 Tweet ID:  705975130514706432 Time: 0.01556692912708968
Success Count: 1329 Tweet ID:  705970349788291072 Time: -0.003467708273092285
Success Count: 1330 Tweet ID:  705898680587526145 Time: -0.0116408369212877
Success Count: 1331 Tweet ID:  705786532653883392 Time: 0.013611434667836875
Success Count: 1332 Tweet ID:  705591895322394625 Time: -0.00956640430376865
Success Count: 1333 Tweet ID:  705475953783398401 Time: -0.0009919065632857382
Success Count: 1334 Tweet ID:  705442520700944385 Time: -0.0015322256076615304
Success Count: 1335 Tweet ID:  705428427625635840 Time: 0.01916301515302621
Success Count: 1336 Tweet ID:  705239209544720384 Time: 0.01591694715898484
Success Count: 1337 Tweet ID:  705223444686888960 Time: -0.013812685618177056
Success Count: 1338 Tweet ID:  705102439679201280 Time: 0.014642609719885513
Success Count: 1339 Tweet ID:  705066031337840642 Time: 0.00039306230610236526
Success Count: 1340 Tweet ID:  704871453724954624 Time: 0.012324637005804107
Success Count: 1341 Tweet ID:  704859558691414016 Time: 0.01607666414929554
Success Count: 1342 Tweet ID:  704847917308362754 Time: -0.0034998026967514306
Success Count: 1343 Tweet ID:  704819833553219584 Time: -0.022705106995999813
Success Count: 1344 Tweet ID:  704761120771465216 Time: 0.0021322025859262794
Success Count: 1345 Tweet ID:  704499785726889984 Time: 0.025170714041450992
Success Count: 1346 Tweet ID:  704491224099647488 Time: 0.0015484616160392761
Success Count: 1347 Tweet ID:  704480331685040129 Time: -0.01227668413775973
Success Count: 1348 Tweet ID:  704364645503647744 Time: 0.010645532165654004
Success Count: 1349 Tweet ID:  704347321748819968 Time: 0.0007555405609309673
Success Count: 1350 Tweet ID:  704134088924532736 Time: 0.015333583811298013
Success Count: 1351 Tweet ID:  704113298707505153 Time: 0.0005293692229315639
Success Count: 1352 Tweet ID:  704054845121142784 Time: -0.0009730274614412338
Success Count: 1353 Tweet ID:  703774238772166656 Time: 0.03090579909621738
Success Count: 1354 Tweet ID:  703769065844768768 Time: 0.009155595675110817
Success Count: 1355 Tweet ID:  703631701117943808 Time: -0.02211305921082385
Success Count: 1356 Tweet ID:  703611486317502464 Time: 0.009021554229548201
Success Count: 1357 Tweet ID:  703425003149250560 Time: 0.012973699573194608
Success Count: 1358 Tweet ID:  703407252292673536 Time: 0.02952045269194059
Success Count: 1359 Tweet ID:  703382836347330562 Time: 0.022170451615238562
Success Count: 1360 Tweet ID:  703356393781329922 Time: -0.01621183831593953
Success Count: 1361 Tweet ID:  703268521220972544 Time: -0.0018101255991496146
Success Count: 1362 Tweet ID:  703079050210877440 Time: 0.006144005834357813
Success Count: 1363 Tweet ID:  703041949650034688 Time: 0.01685863541206345
Success Count: 1364 Tweet ID:  702932127499816960 Time: -0.00749688025098294
Success Count: 1365 Tweet ID:  702899151802126337 Time: -0.0020933117193635553
Success Count: 1366 Tweet ID:  702684942141153280 Time: -0.0009764257119968534
Success Count: 1367 Tweet ID:  702671118226825216 Time: 0.0022768162889406085
Success Count: 1368 Tweet ID:  702598099714314240 Time: 0.00276465158094652
Success Count: 1369 Tweet ID:  702539513671897089 Time: 0.005772465607151389
Success Count: 1370 Tweet ID:  702332542343577600 Time: 0.009981743933167309
Success Count: 1371 Tweet ID:  702321140488925184 Time: 0.007939028146211058
Success Count: 1372 Tweet ID:  702276748847800320 Time: 0.0062727610929869115
Success Count: 1373 Tweet ID:  702217446468493312 Time: -0.007136667496524751
Success Count: 1374 Tweet ID:  701981390485725185 Time: 0.020653706800658256
Success Count: 1375 Tweet ID:  701952816642965504 Time: 0.012136601435486227
Success Count: 1376 Tweet ID:  701889187134500865 Time: 0.0006079061713535339
Success Count: 1377 Tweet ID:  701805642395348998 Time: -0.02540745760779828
Success Count: 1378 Tweet ID:  701601587219795968 Time: 0.0015775354113429785
Success Count: 1379 Tweet ID:  701570477911896070 Time: 0.03369952444336377
Success Count: 1380 Tweet ID:  701545186879471618 Time: -0.025339870539028198
Success Count: 1381 Tweet ID:  701214700881756160 Time: -0.006760218762792647
Success Count: 1382 Tweet ID:  700890391244103680 Time: 0.003056899644434452
Success Count: 1383 Tweet ID:  700864154249383937 Time: 0.015306020359275863
Success Count: 1384 Tweet ID:  700847567345688576 Time: -0.004958022385835648
Success Count: 1385 Tweet ID:  700796979434098688 Time: -0.007277882948983461
Success Count: 1386 Tweet ID:  700747788515020802 Time: 0.020678627188317478
Success Count: 1387 Tweet ID:  700518061187723268 Time: -0.022202546009793878
Success Count: 1388 Tweet ID:  700505138482569216 Time: 0.03623422887176275
Success Count: 1389 Tweet ID:  700462010979500032 Time: -0.005146813084138557
Success Count: 1390 Tweet ID:  700167517596164096 Time: -9.552811388857663e-05
Success Count: 1391 Tweet ID:  700151421916807169 Time: 0.026667447004001588
Success Count: 1392 Tweet ID:  700143752053182464 Time: -0.008404963678913191
Success Count: 1393 Tweet ID:  700062718104104960 Time: -0.010657992359483615
Success Count: 1394 Tweet ID:  700029284593901568 Time: 0.029212346154963598
Success Count: 1395 Tweet ID:  700002074055016451 Time: -0.012049002514686435
Success Count: 1396 Tweet ID:  699801817392291840 Time: 0.0036149650695733726
Success Count: 1397 Tweet ID:  699788877217865730 Time: 0.021090568567160517
Success Count: 1398 Tweet ID:  699779630832685056 Time: -0.010672340460587293
Success Count: 1399 Tweet ID:  699775878809702401 Time: 0.010884163697483018
Success Count: 1400 Tweet ID:  699691744225525762 Time: -0.011210394062800333
Success Count: 1401 Tweet ID:  699446877801091073 Time: 0.0005086022720206529
Success Count: 1402 Tweet ID:  699434518667751424 Time: -0.0010485437524039298
Success Count: 1403 Tweet ID:  699423671849451520 Time: 0.022070014907512814
Success Count: 1404 Tweet ID:  699413908797464576 Time: 0.007982072420418262
Success Count: 1405 Tweet ID:  699370870310113280 Time: 0.014501771802315488
Success Count: 1406 Tweet ID:  699323444782047232 Time: 0.006103227002313361
Success Count: 1407 Tweet ID:  699088579889332224 Time: -0.009685342462034896
Success Count: 1408 Tweet ID:  699079609774645248 Time: 0.008260727539891377
Success Count: 1409 Tweet ID:  699072405256409088 Time: -0.02843339557875879
Success Count: 1410 Tweet ID:  699060279947165696 Time: 0.02409385162172839
Success Count: 1411 Tweet ID:  699036661657767936 Time: -0.02241210371721536
Success Count: 1412 Tweet ID:  698989035503689728 Time: 0.012062972993589938
Success Count: 1413 Tweet ID:  698953797952008193 Time: 0.005052795313531533
Success Count: 1414 Tweet ID:  698907974262222848 Time: 0.013322207261808217
Success Count: 1415 Tweet ID:  698710712454139905 Time: 0.021129081898834556
Success Count: 1416 Tweet ID:  698703483621523456 Time: 0.023331514646997675
Success Count: 1417 Tweet ID:  698635131305795584 Time: -0.016384393034968525
Success Count: 1418 Tweet ID:  698549713696649216 Time: 0.0009145023650489748
Success Count: 1419 Tweet ID:  698355670425473025 Time: 0.003340085764648393
Success Count: 1420 Tweet ID:  698342080612007937 Time: 0.02737088131834753
Success Count: 1421 Tweet ID:  698262614669991936 Time: -0.016607543686404824
Success Count: 1422 Tweet ID:  698195409219559425 Time: 0.0182738107687328
Success Count: 1423 Tweet ID:  698178924120031232 Time: 0.0021597660379484296
Success Count: 1424 Tweet ID:  697995514407682048 Time: 0.013884048472391441
Success Count: 1425 Tweet ID:  697990423684476929 Time: -0.013857995363650844
Success Count: 1426 Tweet ID:  697943111201378304 Time: 0.036506465141428635

Success Count: 1427 Tweet ID:  697881462549430272 Time: -0.006243687297683209
Success Count: 1428 Tweet ID:  697630435728322560 Time: -0.002494680811651051
Success Count: 1429 Tweet ID:  697616773278015490 Time: 0.025552071281708777
Success Count: 1430 Tweet ID:  697596423848730625 Time: 0.03685950383078307
Success Count: 1431 Tweet ID:  697575480820686848 Time: 0.01687789201969281
Success Count: 1432 Tweet ID:  697516214579523584 Time: -0.022783643915317953
Success Count: 1433 Tweet ID:  697482927769255936 Time: 0.005793987773358822
Success Count: 1434 Tweet ID:  697463031882764288 Time: -0.0005391863523982465
Success Count: 1435 Tweet ID:  697270446429966336 Time: -0.003981219109846279
Success Count: 1436 Tweet ID:  697259378236399616 Time: 0.0018626094097271562
Success Count: 1437 Tweet ID:  697255105972801536 Time: 0.0135532871063333
Success Count: 1438 Tweet ID:  697242256848379904 Time: 0.0017682140751276165
Success Count: 1439 Tweet ID:  696900204696625153 Time: 0.027283282397547737
Success Count: 1440 Tweet ID:  696894894812565505 Time: 0.0010976293997373432
Success Count: 1441 Tweet ID:  696886256886657024 Time: -1.887907274067402e-05
Success Count: 1442 Tweet ID:  696877980375769088 Time: 0.01030910704866983
Success Count: 1443 Tweet ID:  696754882863349760 Time: 0.019528514007106423
Success Count: 1444 Tweet ID:  696744641916489729 Time: 0.01752355636563152
Success Count: 1445 Tweet ID:  696713835009417216 Time: -0.012890254060039297
Success Count: 1446 Tweet ID:  696518437233913856 Time: 0.015226728224661201
Success Count: 1447 Tweet ID:  696490539101908992 Time: 0.027574020146857947
Success Count: 1448 Tweet ID:  696488710901260288 Time: -0.0007404372736345977
Success Count: 1449 Tweet ID:  696405997980676096 Time: 0.012220424512634054
Success Count: 1450 Tweet ID:  696100768806522880 Time: -0.010213578963885084
Success Count: 1451 Tweet ID:  695816827381944320 Time: -0.001040236937114969
Success Count: 1452 Tweet ID:  695794761660297217 Time: -0.005067521007731557
Success Count: 1453 Tweet ID:  695767669421768709 Time: -0.0032305870845448226
Success Count: 1454 Tweet ID:  695629776980148225 Time: 0.021583689987892285
Success Count: 1455 Tweet ID:  695446424020918272 Time: -0.008705140964593738
Success Count: 1456 Tweet ID:  695409464418041856 Time: -0.011694075947161764
Success Count: 1457 Tweet ID:  695314793360662529 Time: 0.019560230837669224
Success Count: 1458 Tweet ID:  695095422348574720 Time: 0.004517384804785252
Success Count: 1459 Tweet ID:  695074328191332352 Time: 0.00017746328376233578
Success Count: 1460 Tweet ID:  695064344191721472 Time: 0.030729846126632765
Success Count: 1461 Tweet ID:  695051054296211456 Time: 0.017615686228964478
Success Count: 1462 Tweet ID:  694925794720792577 Time: 0.019989541033282876
Success Count: 1463 Tweet ID:  694905863685980160 Time: 0.0007536526536568999
Success Count: 1464 Tweet ID:  694669722378485760 Time: -0.012784908816684037
Success Count: 1465 Tweet ID:  694356675654983680 Time: 0.03401102917268872
Success Count: 1466 Tweet ID:  694352839993344000 Time: 0.03521853475831449
Success Count: 1467 Tweet ID:  694342028726001664 Time: -0.009056291717570275
Success Count: 1468 Tweet ID:  694329668942569472 Time: -0.0009152574930340052
Success Count: 1469 Tweet ID:  694206574471057408 Time: -0.001839199336245656
Success Count: 1470 Tweet ID:  694183373896572928 Time: -0.005004842474590987
Success Count: 1471 Tweet ID:  694001791655137281 Time: 0.0013423021591734141
Success Count: 1472 Tweet ID:  693993230313091072 Time: 0.023562972113722935
Success Count: 1473 Tweet ID:  693942351086120961 Time: 0.009317200514487922
Success Count: 1474 Tweet ID:  693647888581312512 Time: -0.0072325732035096735
Success Count: 1475 Tweet ID:  693644216740769793 Time: 0.015003200009232387
Success Count: 1476 Tweet ID:  693642232151285760 Time: 0.027633300400339067
Success Count: 1477 Tweet ID:  693629975228977152 Time: -0.006785516714444384
Success Count: 1478 Tweet ID:  693622659251335168 Time: -0.012178512959508225
Success Count: 1479 Tweet ID:  693590843962331137 Time: -0.02694119358784519
Success Count: 1480 Tweet ID:  693582294167244802 Time: 0.030948465777328238
Success Count: 1481 Tweet ID:  693486665285931008 Time: -0.007915995665825903
Success Count: 1482 Tweet ID:  693280720173801472 Time: -0.008139523910358548
Success Count: 1483 Tweet ID:  693267061318012928 Time: -0.001452178374165669
Success Count: 1484 Tweet ID:  693262851218264065 Time: 0.01161251837038435
Success Count: 1485 Tweet ID:  693231807727280129 Time: -0.01110618156963028
Success Count: 1486 Tweet ID:  693155686491000832 Time: 0.017835061065852642
Success Count: 1487 Tweet ID:  693109034023534592 Time: 0.011057851137593389
Success Count: 1488 Tweet ID:  693095443459342336 Time: -0.0027820203395094723
Success Count: 1489 Tweet ID:  692919143163629568 Time: 0.023690217087278143
Success Count: 1490 Tweet ID:  692905862751522816 Time: 0.0071604551339987665
Success Count: 1491 Tweet ID:  692901601640583168 Time: -0.027397689555073157
Success Count: 1492 Tweet ID:  692894228850999298 Time: 0.01017204497475177
Success Count: 1493 Tweet ID:  692828166163931137 Time: 0.0134898534452077
Success Count: 1494 Tweet ID:  692752401762250755 Time: 0.004833420505747199
Success Count: 1495 Tweet ID:  692568918515392513 Time: -0.021542533620959148
Success Count: 1496 Tweet ID:  692535307825213440 Time: 0.01113374502165243
Success Count: 1497 Tweet ID:  692530551048294401 Time: 0.017253585625439882
Success Count: 1498 Tweet ID:  692423280028966913 Time: 0.006053008633898571
Success Count: 1499 Tweet ID:  692417313023332352 Time: -0.009780115418834612
Success Count: 1500 Tweet ID:  692187005137076224 Time: -0.000275256868917495
Success Count: 1501 Tweet ID:  692158366030913536 Time: 0.005092063802294433
Success Count: 1502 Tweet ID:  692142790915014657 Time: -0.0070683252706658095
Success Count: 1503 Tweet ID:  692041934689402880 Time: -0.0019966508261859417
Success Count: 1504 Tweet ID:  692017291282812928 Time: 0.028882717539090663
Success Count: 1505 Tweet ID:  691820333922455552 Time: -0.007782331813359633
Success Count: 1506 Tweet ID:  691793053716221953 Time: 0.003286091610789299
Success Count: 1507 Tweet ID:  691756958957883396 Time: -0.02092330000596121
Success Count: 1508 Tweet ID:  691675652215414786 Time: 0.02688606668380089
Success Count: 1509 Tweet ID:  691483041324204033 Time: 0.0201730455737561
Success Count: 1510 Tweet ID:  691459709405118465 Time: 0.006231604696949944
Success Count: 1511 Tweet ID:  691444869282295808 Time: -0.0064917583076749
Success Count: 1512 Tweet ID:  691416866452082688 Time: -0.006273138656979427
Success Count: 1513 Tweet ID:  691321916024623104 Time: 0.022132693469757214
Success Count: 1514 Tweet ID:  691096613310316544 Time: 0.00819200772093609
Success Count: 1515 Tweet ID:  691090071332753408 Time: 0.021198556874878705
Success Count: 1516 Tweet ID:  690989312272396288 Time: 0.023105343367205933
Success Count: 1517 Tweet ID:  690959652130045952 Time: 0.026710491278208792
Success Count: 1518 Tweet ID:  690938899477221376 Time: -0.013978821429191157
Success Count: 1519 Tweet ID:  690932576555528194 Time: 0.009251878916984424
Success Count: 1520 Tweet ID:  690735892932222976 Time: -0.007204254623502493
Success Count: 1521 Tweet ID:  690728923253055490 Time: 0.01850866642780602
Success Count: 1522 Tweet ID:  690690673629138944 Time: 0.016571673448197544
Success Count: 1523 Tweet ID:  690649993829576704 Time: -0.020099794783163816
Success Count: 1524 Tweet ID:  690607260360429569 Time: 0.0035787172382697463
Success Count: 1525 Tweet ID:  690597161306841088 Time: -0.008116113836877048
Success Count: 1526 Tweet ID:  690400367696297985 Time: 0.024541285703890026
Success Count: 1527 Tweet ID:  690374419777196032 Time: 0.004518139932770282
Success Count: 1528 Tweet ID:  690360449368465409 Time: -0.001247529173269868
Success Count: 1529 Tweet ID:  690348396616552449 Time: 0.021719241747632623
Success Count: 1530 Tweet ID:  690248561355657216 Time: -0.019491511018713936
Success Count: 1531 Tweet ID:  690021994562220032 Time: 0.021949566435068846
Success Count: 1532 Tweet ID:  690015576308211712 Time: -0.02297772080055438

Success Count: 1533 Tweet ID:  690005060500217858 Time: 0.0207194059912581
Success Count: 1534 Tweet ID:  689999384604450816 Time: -0.001835045957705006
Success Count: 1535 Tweet ID:  689993469801164801 Time: -0.00121732268598862
Success Count: 1536 Tweet ID:  689977555533848577 Time: -0.0036712246655952185
Success Count: 1537 Tweet ID:  689905486972461056 Time: 0.0034567584516480565
Success Count: 1538 Tweet ID:  689877686181715968 Time: 0.02306305425008759
Success Count: 1539 Tweet ID:  689835978131935233 Time: -0.006069999828469008
Success Count: 1540 Tweet ID:  689661964914655233 Time: 0.0018493940879125148
Success Count: 1541 Tweet ID:  689659372465688576 Time: -0.007735511724604294
Success Count: 1542 Tweet ID:  689623661272240129 Time: 0.022181023901794106
Success Count: 1543 Tweet ID:  689599056876867584 Time: -0.010332894686143845
Success Count: 1544 Tweet ID:  689557536375177216 Time: 0.024779162020422518
Success Count: 1545 Tweet ID:  689517482558820352 Time: -0.021272185258567333
Success Count: 1546 Tweet ID:  689289219123089408 Time: 0.015584297885652632
Success Count: 1547 Tweet ID:  689283819090870273 Time: -0.004769609222421423
Success Count: 1548 Tweet ID:  689280876073582592 Time: -0.0022564269020222127
Success Count: 1549 Tweet ID:  689275259254616065 Time: 0.014212921960279346
Success Count: 1550 Tweet ID:  689255633275777024 Time: 0.008246757060987875
Success Count: 1551 Tweet ID:  689154315265683456 Time: 0.029261809366289526
Success Count: 1552 Tweet ID:  689143371370250240 Time: -0.010714251984609291
Success Count: 1553 Tweet ID:  688916208532455424 Time: 0.006248973484616727
Success Count: 1554 Tweet ID:  688908934925697024 Time: -0.001051186816766858
Success Count: 1555 Tweet ID:  688898160958271489 Time: -0.028191743418574333
Success Count: 1556 Tweet ID:  688894073864884227 Time: 0.02884382664342411
Success Count: 1557 Tweet ID:  688828561667567616 Time: 0.038006218761438504
Success Count: 1558 Tweet ID:  688804835492233216 Time: 0.0027129229274578393
Success Count: 1559 Tweet ID:  688789766343622656 Time: 0.0017289455863647163
Success Count: 1560 Tweet ID:  688547210804498433 Time: 0.014072839258005843
Success Count: 1561 Tweet ID:  688519176466644993 Time: 0.006633351411437616
Success Count: 1562 Tweet ID:  688385280030670848 Time: -0.010994417476467788
Success Count: 1563 Tweet ID:  688211956440801280 Time: 0.013036755670327693
Success Count: 1564 Tweet ID:  688179443353796608 Time: -0.017705173057038337
Success Count: 1565 Tweet ID:  688116655151435777 Time: 0.030215957725886256
Success Count: 1566 Tweet ID:  688064179421470721 Time: -0.037457970494870096
Success Count: 1567 Tweet ID:  687841446767013888 Time: 0.01974260271526873
Success Count: 1568 Tweet ID:  687826841265172480 Time: -0.025527906109346077
Success Count: 1569 Tweet ID:  687818504314159109 Time: -0.0005614636756945401
Success Count: 1570 Tweet ID:  687807801670897665 Time: -0.00024165213108062744
Success Count: 1571 Tweet ID:  687732144991551489 Time: 0.0013415469729807228
Success Count: 1572 Tweet ID:  687704180304273409 Time: 0.018121267843525857
Success Count: 1573 Tweet ID:  687664829264453632 Time: 0.006940325140021741
Success Count: 1574 Tweet ID:  687494652870668288 Time: -0.017230930738151073
Success Count: 1575 Tweet ID:  687480748861947905 Time: -0.002551318029873073
Success Count: 1576 Tweet ID:  687476254459715584 Time: 0.044432655529817566
Success Count: 1577 Tweet ID:  687460506001633280 Time: -0.014054337749257684
Success Count: 1578 Tweet ID:  687399393394311168 Time: 0.019681056903209537
Success Count: 1579 Tweet ID:  687317306314240000 Time: -0.014059246343094856
Success Count: 1580 Tweet ID:  687312378585812992 Time: -0.00614589371252805
Success Count: 1581 Tweet ID:  687127927494963200 Time: 0.021463619108544663
Success Count: 1582 Tweet ID:  687124485711986689 Time: 0.029139095364371315
Success Count: 1583 Tweet ID:  687109925361856513 Time: 0.0016583378601353616
Success Count: 1584 Tweet ID:  687102708889812993 Time: 0.027635188336716965
Success Count: 1585 Tweet ID:  687096057537363968 Time: -0.006841398775577545
Success Count: 1586 Tweet ID:  686947101016735744 Time: 0.026777700782986358
Success Count: 1587 Tweet ID:  686760001961103360 Time: 0.029518187133362517
Success Count: 1588 Tweet ID:  686749460672679938 Time: -0.005345798534108326
Success Count: 1589 Tweet ID:  686730991906516992 Time: 0.002072544739348814
Success Count: 1590 Tweet ID:  686683045143953408 Time: 0.0062225427536759526
Success Count: 1591 Tweet ID:  686618349602762752 Time: 0.017855828074971214
Success Count: 1592 Tweet ID:  686606069955735556 Time: 0.017153904103906825
Success Count: 1593 Tweet ID:  686394059078897668 Time: 0.0022175360354594886
Success Count: 1594 Tweet ID:  686386521809772549 Time: 0.012429982249159366
Success Count: 1595 Tweet ID:  686377065986265092 Time: 0.004385231266496703
Success Count: 1596 Tweet ID:  686358356425093120 Time: 0.017165609111543745
Success Count: 1597 Tweet ID:  686286779679375361 Time: -0.010518287221202627
Success Count: 1598 Tweet ID:  686050296934563840 Time: -0.01599284104304388
Success Count: 1599 Tweet ID:  686035780142297088 Time: 0.0051996745460201055
Success Count: 1600 Tweet ID:  686034024800862208 Time: -0.03160998853854835
Success Count: 1601 Tweet ID:  686007916130873345 Time: 0.0024799551465548575
Success Count: 1602 Tweet ID:  686003207160610816 Time: -0.003999720589490607
Success Count: 1603 Tweet ID:  685973236358713344 Time: -0.0031611121085006744
Success Count: 1604 Tweet ID:  685943807276412928 Time: 0.0004999178927391768
Success Count: 1605 Tweet ID:  685906723014619143 Time: 0.013370160100748762
Success Count: 1606 Tweet ID:  685681090388975616 Time: 0.007464030641131103
Success Count: 1607 Tweet ID:  685667379192414208 Time: -0.0010051218851003796
Success Count: 1608 Tweet ID:  685663452032069632 Time: -0.007971877726959065
Success Count: 1609 Tweet ID:  685641971164143616 Time: 0.007453080761479214
Success Count: 1610 Tweet ID:  685547936038666240 Time: -0.0019358602585271
Success Count: 1611 Tweet ID:  685532292383666176 Time: 0.003389926510863006
Success Count: 1612 Tweet ID:  685325112850124800 Time: -0.014112485281657428
Success Count: 1613 Tweet ID:  685321586178670592 Time: -0.0019781493465416133
Success Count: 1614 Tweet ID:  685315239903100929 Time: -0.0038366053777281195
Success Count: 1615 Tweet ID:  685307451701334016 Time: -0.0038992839108686894
Success Count: 1616 Tweet ID:  685268753634967552 Time: 0.003761466679861769
Success Count: 1617 Tweet ID:  685198997565345792 Time: 0.0028541383799165487
Success Count: 1618 Tweet ID:  685169283572338688 Time: 6.3811254221946e-05
Success Count: 1619 Tweet ID:  684969860808454144 Time: -0.0017757656460162252
Success Count: 1620 Tweet ID:  684959798585110529 Time: -0.0018093704129569232
Success Count: 1621 Tweet ID:  684940049151070208 Time: -0.0040438976138830185
Success Count: 1622 Tweet ID:  684926975086034944 Time: 0.00033189408713951707
Success Count: 1623 Tweet ID:  684914660081053696 Time: 0.024017580173676834
Success Count: 1624 Tweet ID:  684902183876321280 Time: -0.002118609641911462
Success Count: 1625 Tweet ID:  684880619965411328 Time: -0.011366712802555412
Success Count: 1626 Tweet ID:  684830982659280897 Time: -0.0021416421222966164
Success Count: 1627 Tweet ID:  684800227459624960 Time: -0.003214728698367253
Success Count: 1628 Tweet ID:  684594889858887680 Time: -0.0033253600995521992
Success Count: 1629 Tweet ID:  684588130326986752 Time: 0.002566043724073097
Success Count: 1630 Tweet ID:  684567543613382656 Time: 0.0014310338301584125
Success Count: 1631 Tweet ID:  684538444857667585 Time: -0.0011754111328627914
Success Count: 1632 Tweet ID:  684481074559381504 Time: 0.001232048380188644
Success Count: 1633 Tweet ID:  684460069371654144 Time: -0.004856075393036008
Success Count: 1634 Tweet ID:  684241637099323392 Time: -0.0028175129555165768
Success Count: 1635 Tweet ID:  684225744407494656 Time: 0.004039366613142192
Success Count: 1636 Tweet ID:  684222868335505415 Time: -0.004311225289711729
Success Count: 1637 Tweet ID:  684200372118904832 Time: -0.0009518829174339771
Success Count: 1638 Tweet ID:  684195085588783105 Time: 0.005261220299871638

Success Count: 1639 Tweet ID:  684188786104872960 Time: -0.003586268867366016
Success Count: 1640 Tweet ID:  684177701129875456 Time: 0.002468627702910453
Success Count: 1641 Tweet ID:  684147889187209216 Time: -0.0027140556776430458
Success Count: 1642 Tweet ID:  684122891630342144 Time: -0.0014419836516026407
Success Count: 1643 Tweet ID:  684097758874210310 Time: 0.0008374757308047265
Success Count: 1644 Tweet ID:  683857920510050305 Time: 0.00221073956345208
Success Count: 1645 Tweet ID:  683852578183077888 Time: -0.0052770787151530385
Success Count: 1646 Tweet ID:  683849932751646720 Time: 0.0004976524214725941
Success Count: 1647 Tweet ID:  683834909291606017 Time: 0.00784689825377427
Success Count: 1648 Tweet ID:  683828599284170753 Time: -0.008321895758854225
Success Count: 1649 Tweet ID:  683773439333797890 Time: -0.0022568044951185584
Success Count: 1650 Tweet ID:  683742671509258241 Time: 0.0032834485173225403
Success Count: 1651 Tweet ID:  683515932363329536 Time: 0.012810206797439605
Success Count: 1652 Tweet ID:  683498322573824003 Time: -0.014502904523396865
Success Count: 1653 Tweet ID:  683481228088049664 Time: -0.004948582849465311
Success Count: 1654 Tweet ID:  683462770029932544 Time: 0.00259587264736183
Success Count: 1655 Tweet ID:  683449695444799489 Time: -0.00039834846393205225
Success Count: 1656 Tweet ID:  683391852557561860 Time: 0.0026430703001096845
Success Count: 1657 Tweet ID:  683357973142474752 Time: -0.003176215395797044
Success Count: 1658 Tweet ID:  683142553609318400 Time: -0.003188675589626655
Success Count: 1659 Tweet ID:  683111407806746624 Time: 0.0035862688964698464
Success Count: 1660 Tweet ID:  683098815881154561 Time: -0.00410393308266066
Success Count: 1661 Tweet ID:  683078886620553216 Time: 0.003017253562575206
Success Count: 1662 Tweet ID:  683030066213818368 Time: -0.0010734641400631517
Success Count: 1663 Tweet ID:  682962037429899265 Time: 0.0030210294062271714
Success Count: 1664 Tweet ID:  682808988178739200 Time: 0.001047788595315069
Success Count: 1665 Tweet ID:  682788441537560576 Time: -0.0011606854386627674
Success Count: 1666 Tweet ID:  682750546109968385 Time: -0.0014593523810617626
Success Count: 1667 Tweet ID:  682697186228989953 Time: 0.0022926747042220086
Success Count: 1668 Tweet ID:  682662431982772225 Time: -0.0031037197331897914
Success Count: 1669 Tweet ID:  682638830361513985 Time: 0.00046857859706506133
Success Count: 1670 Tweet ID:  682429480204398592 Time: -0.0015843318833503872
Success Count: 1671 Tweet ID:  682406705142087680 Time: -0.0009322486876044422
Success Count: 1672 Tweet ID:  682393905736888321 Time: 0.0018837540119420737
Success Count: 1673 Tweet ID:  682389078323662849 Time: -3.8135709473863244e-05
Success Count: 1674 Tweet ID:  682303737705140231 Time: 0.0051872143521904945
Success Count: 1675 Tweet ID:  682259524040966145 Time: -0.001047033438226208
Success Count: 1676 Tweet ID:  682242692827447297 Time: 0.0023266570642590523
Success Count: 1677 Tweet ID:  682088079302213632 Time: 0.014775895950151607
Success Count: 1678 Tweet ID:  682059653698686977 Time: -0.002050645009148866
Success Count: 1679 Tweet ID:  682047327939461121 Time: -0.0012097710568923503
Success Count: 1680 Tweet ID:  682032003584274432 Time: 0.0009877531556412578
Success Count: 1681 Tweet ID:  682003177596559360 Time: -0.00013328625936992466
Success Count: 1682 Tweet ID:  681981167097122816 Time: -0.0032143511343747377
Success Count: 1683 Tweet ID:  681891461017812993 Time: -0.003449584386544302
Success Count: 1684 Tweet ID:  681694085539872773 Time: 0.002213005063822493
Success Count: 1685 Tweet ID:  681679526984871937 Time: 0.00206952408188954
Success Count: 1686 Tweet ID:  681654059175129088 Time: 0.0013215351500548422
Success Count: 1687 Tweet ID:  681610798867845120 Time: -0.007029811968095601
Success Count: 1688 Tweet ID:  681579835668455424 Time: -0.0001672685903031379
Success Count: 1689 Tweet ID:  681523177663676416 Time: 0.007223511260235682
Success Count: 1690 Tweet ID:  681340665377193984 Time: -0.006679416314000264
Success Count: 1691 Tweet ID:  681339448655802368 Time: -0.0026298550073988736
Success Count: 1692 Tweet ID:  681320187870711809 Time: -0.0004289325443096459
Success Count: 1693 Tweet ID:  681302363064414209 Time: -0.0019804148469120264
Success Count: 1694 Tweet ID:  681297372102656000 Time: 0.0005399415094871074
Success Count: 1695 Tweet ID:  681281657291280384 Time: -0.0018584560020826757
Success Count: 1696 Tweet ID:  681261549936340994 Time: 0.00018765797722153366
Success Count: 1697 Tweet ID:  681242418453299201 Time: 0.0004901007632724941
Success Count: 1698 Tweet ID:  681231109724700672 Time: 0.000317168451147154
Success Count: 1699 Tweet ID:  681193455364796417 Time: -0.002643825486302376
Success Count: 1700 Tweet ID:  680970795137544192 Time: 0.0017470695020165294
Success Count: 1701 Tweet ID:  680959110691590145 Time: -0.003442787885433063
Success Count: 1702 Tweet ID:  680940246314430465 Time: 0.0002620415179990232
Success Count: 1703 Tweet ID:  680934982542561280 Time: -0.001276980561669916
Success Count: 1704 Tweet ID:  680913438424612864 Time: 0.0011504907452035695
Success Count: 1705 Tweet ID:  680889648562991104 Time: -0.0017980429693125188
Success Count: 1706 Tweet ID:  680836378243002368 Time: 0.002714810805628076
Success Count: 1707 Tweet ID:  680805554198020098 Time: 0.003317808441352099
Success Count: 1708 Tweet ID:  680801747103793152 Time: -0.0019804148469120264
Success Count: 1709 Tweet ID:  680798457301471234 Time: 0.0033755783806554973
Success Count: 1710 Tweet ID:  680609293079592961 Time: 0.034206238779006526
Success Count: 1711 Tweet ID:  680583894916304897 Time: 0.008904503978556022
Success Count: 1712 Tweet ID:  680497766108381184 Time: -0.005106034339405596
Success Count: 1713 Tweet ID:  680494726643068929 Time: -0.009981743962271139
Success Count: 1714 Tweet ID:  680473011644985345 Time: 0.030423249932937324
Success Count: 1715 Tweet ID:  680440374763077632 Time: -0.002130314678652212
Success Count: 1716 Tweet ID:  680221482581123072 Time: 0.03958224382949993
Success Count: 1717 Tweet ID:  680206703334408192 Time: -0.0036738677881658077
Success Count: 1718 Tweet ID:  680191257256136705 Time: 0.00011025380808860064
Success Count: 1719 Tweet ID:  680176173301628928 Time: -0.006354318669764325
Success Count: 1720 Tweet ID:  680161097740095489 Time: 0.0013256885576993227
Success Count: 1721 Tweet ID:  680145970311643136 Time: -0.004883638815954328
Success Count: 1722 Tweet ID:  680130881361686529 Time: 0.01797476623323746
Success Count: 1723 Tweet ID:  680115823365742593 Time: 0.02796066354494542
Success Count: 1724 Tweet ID:  680100725817409536 Time: -0.02589113952126354
Success Count: 1725 Tweet ID:  680085611152338944 Time: 0.030535769241396338
Success Count: 1726 Tweet ID:  680070545539371008 Time: 0.002213005063822493
Success Count: 1727 Tweet ID:  680055455951884288 Time: -0.012741486949380487
Success Count: 1728 Tweet ID:  679877062409191424 Time: -0.005246494663879275
Success Count: 1729 Tweet ID:  679872969355714560 Time: 0.004790376202436164
Success Count: 1730 Tweet ID:  679862121895714818 Time: -0.006099451187765226
Success Count: 1731 Tweet ID:  679854723806179328 Time: -0.002365925523918122
Success Count: 1732 Tweet ID:  679844490799091713 Time: 0.0035975963401142508
Success Count: 1733 Tweet ID:  679828447187857408 Time: 0.026855860167415813
Success Count: 1734 Tweet ID:  679777920601223168 Time: 0.007433068938553333
Success Count: 1735 Tweet ID:  679736210798047232 Time: 0.0018305150151718408
Success Count: 1736 Tweet ID:  679729593985699840 Time: 0.0016160487430170178
Success Count: 1737 Tweet ID:  679722016581222400 Time: 0.013498915388481691
Success Count: 1738 Tweet ID:  679530280114372609 Time: 0.0013347505300771445
Success Count: 1739 Tweet ID:  679527802031484928 Time: -0.031265256606275216
Success Count: 1740 Tweet ID:  679511351870550016 Time: 0.026672733132727444
Success Count: 1741 Tweet ID:  679503373272485890 Time: -0.01067007496021688
Success Count: 1742 Tweet ID:  679475951516934144 Time: 0.005369586200686172
Success Count: 1743 Tweet ID:  679462823135686656 Time: 0.008406096458202228
Success Count: 1744 Tweet ID:  679405845277462528 Time: -0.0056520171638112515

Success Count: 1745 Tweet ID:  679158373988876288 Time: 0.02398699609329924
Success Count: 1746 Tweet ID:  679148763231985668 Time: 0.014803459402173758
Success Count: 1747 Tweet ID:  679132435750195208 Time: -0.026088614598847926
Success Count: 1748 Tweet ID:  679111216690831360 Time: 0.022281460580416024
Success Count: 1749 Tweet ID:  679062614270468097 Time: 0.023584116657730192
Success Count: 1750 Tweet ID:  679047485189439488 Time: -0.009924351557856426
Success Count: 1751 Tweet ID:  679001094530465792 Time: -0.019705222104676068
Success Count: 1752 Tweet ID:  678991772295516161 Time: 0.013508732517948374
Success Count: 1753 Tweet ID:  678969228704284672 Time: -0.006518189038615674
Success Count: 1754 Tweet ID:  678800283649069056 Time: -0.0024467279436066747
Success Count: 1755 Tweet ID:  678798276842360832 Time: 0.005020323296776041
Success Count: 1756 Tweet ID:  678774928607469569 Time: -0.008630379801616073
Success Count: 1757 Tweet ID:  678767140346941444 Time: 0.01596716552739963
Success Count: 1758 Tweet ID:  678764513869611008 Time: -0.011581179103814065
Success Count: 1759 Tweet ID:  678755239630127104 Time: 0.01733816385967657
Success Count: 1760 Tweet ID:  678740035362037760 Time: 0.0034359914425294846
Success Count: 1761 Tweet ID:  678708137298427904 Time: 0.006195734458742663
Success Count: 1762 Tweet ID:  678675843183484930 Time: 0.014033570769242942
Success Count: 1763 Tweet ID:  678643457146150913 Time: 0.0069373044825624675
Success Count: 1764 Tweet ID:  678446151570427904 Time: -0.019333681964781135
Success Count: 1765 Tweet ID:  678424312106393600 Time: -0.004759036935865879
Success Count: 1766 Tweet ID:  678410210315247616 Time: 0.020446414593607187
Success Count: 1767 Tweet ID:  678399652199309312 Time: -0.007690957136219367
Success Count: 1768 Tweet ID:  678396796259975168 Time: 0.04211657075211406
Success Count: 1769 Tweet ID:  678389028614488064 Time: -0.0031682862027082592
Success Count: 1770 Tweet ID:  678380236862578688 Time: 3.0206574592739344e-06
Success Count: 1771 Tweet ID:  678341075375947776 Time: 0.01275545745738782
Success Count: 1772 Tweet ID:  678334497360859136 Time: 0.01941259644809179
Success Count: 1773 Tweet ID:  678278586130948096 Time: 0.010108988906722516
Success Count: 1774 Tweet ID:  678255464182861824 Time: 0.005692418373655528
Success Count: 1775 Tweet ID:  678023323247357953 Time: -0.01114884827984497
Success Count: 1776 Tweet ID:  678021115718029313 Time: 0.01921059042797424
Success Count: 1777 Tweet ID:  677961670166224897 Time: -0.004220983333652839
Success Count: 1778 Tweet ID:  677918531514703872 Time: 0.006040926033165306
Success Count: 1779 Tweet ID:  677895101218201600 Time: 0.017320417508017272
Success Count: 1780 Tweet ID:  677716515794329600 Time: -0.023015856539132074
Success Count: 1781 Tweet ID:  677700003327029250 Time: 0.014654314698418602
Success Count: 1782 Tweet ID:  677698403548192770 Time: -0.000891847419552505
Success Count: 1783 Tweet ID:  677687604918272002 Time: 0.025117852637777105
Success Count: 1784 Tweet ID:  677673981332312066 Time: 0.017319284786935896
Success Count: 1785 Tweet ID:  677662372920729601 Time: -0.05199523491319269
Success Count: 1786 Tweet ID:  677644091929329666 Time: 0.01923626594361849
Success Count: 1787 Tweet ID:  677573743309385728 Time: -0.009901319077471271
Success Count: 1788 Tweet ID:  677565715327688705 Time: -0.0007087204430717975
Success Count: 1789 Tweet ID:  677557565589463040 Time: -0.004510210739681497
Success Count: 1790 Tweet ID:  677547928504967168 Time: -0.0015869749477133155
Success Count: 1791 Tweet ID:  677530072887205888 Time: 0.006540088768815622
Success Count: 1792 Tweet ID:  677335745548390400 Time: 0.012867599172750488
Success Count: 1793 Tweet ID:  677334615166730240 Time: 0.00570978710311465
Success Count: 1794 Tweet ID:  677331501395156992 Time: 0.007440998189849779

Rate limit reached. Sleeping for: 490

Success Count: 1795 Tweet ID:  677328882937298944 Time: 0.004440735763637349
Success Count: 1796 Tweet ID:  677314812125323265 Time: 0.015141017240239307
Success Count: 1797 Tweet ID:  677301033169788928 Time: 0.013409428589511663
Success Count: 1798 Tweet ID:  677269281705472000 Time: -0.007696998422034085
Success Count: 1799 Tweet ID:  677228873407442944 Time: 0.015178020228631794
Success Count: 1800 Tweet ID:  677187300187611136 Time: 0.0019634236523415893
Success Count: 1801 Tweet ID:  676975532580409345 Time: -0.006816855981014669
Success Count: 1802 Tweet ID:  676957860086095872 Time: 0.0028730174526572227
Success Count: 1803 Tweet ID:  676949632774234114 Time: 0.0217755013727583
Success Count: 1804 Tweet ID:  676948236477857792 Time: 0.014490444358671084
Success Count: 1805 Tweet ID:  676946864479084545 Time: 0.004604606132488698
Success Count: 1806 Tweet ID:  676942428000112642 Time: 0.008072314434684813
Success Count: 1807 Tweet ID:  676936541936185344 Time: 0.005605197045952082
Success Count: 1808 Tweet ID:  676916996760600576 Time: -0.024173521349439397
Success Count: 1809 Tweet ID:  676897532954456065 Time: 0.0028137371700722724
Success Count: 1810 Tweet ID:  676864501615042560 Time: -0.0013049215776845813
Success Count: 1811 Tweet ID:  676821958043033607 Time: 3.700295928865671e-05
Success Count: 1812 Tweet ID:  676819651066732545 Time: -0.002650621987413615
Success Count: 1813 Tweet ID:  676811746707918848 Time: -0.0007004136277828366
Success Count: 1814 Tweet ID:  676776431406465024 Time: 0.014200461795553565
Success Count: 1815 Tweet ID:  676617503762681856 Time: -0.006119085417594761
Success Count: 1816 Tweet ID:  676613908052996102 Time: 0.010085578833241016
Success Count: 1817 Tweet ID:  676606785097199616 Time: 0.005879698757780716
Success Count: 1818 Tweet ID:  676603393314578432 Time: -0.01317495049443096
Success Count: 1819 Tweet ID:  676593408224403456 Time: 0.002221311820903793
Success Count: 1820 Tweet ID:  676590572941893632 Time: 0.025717074400745332
Success Count: 1821 Tweet ID:  676588346097852417 Time: -0.02423431194620207
Success Count: 1822 Tweet ID:  676582956622721024 Time: 0.01593356076045893
Success Count: 1823 Tweet ID:  676575501977128964 Time: -0.017468807054683566
Success Count: 1824 Tweet ID:  676533798876651520 Time: 0.009984386997530237
Success Count: 1825 Tweet ID:  676496375194980353 Time: -0.01598793250741437
Success Count: 1826 Tweet ID:  676470639084101634 Time: 0.02342477726051584
Success Count: 1827 Tweet ID:  676440007570247681 Time: -0.009082344855414703
Success Count: 1828 Tweet ID:  676430933382295552 Time: 0.002241701236926019
Success Count: 1829 Tweet ID:  676263575653122048 Time: 0.020928963727783412
Success Count: 1830 Tweet ID:  676237365392908289 Time: 0.00018350459868088365
Success Count: 1831 Tweet ID:  676219687039057920 Time: 0.00832076303777285
Success Count: 1832 Tweet ID:  676215927814406144 Time: -0.007744951260974631
Success Count: 1833 Tweet ID:  676191832485810177 Time: 0.02081115826149471
Success Count: 1834 Tweet ID:  676146341966438401 Time: 0.008717978751519695
Success Count: 1835 Tweet ID:  676121918416756736 Time: -0.006057539634639397
Success Count: 1836 Tweet ID:  676101918813499392 Time: 0.0014857831120025367
Success Count: 1837 Tweet ID:  676098748976615425 Time: 0.033075004670536146
Success Count: 1838 Tweet ID:  676089483918516224 Time: 0.0035334074636921287
Success Count: 1839 Tweet ID:  675898130735476737 Time: -0.0066276876896154135
Success Count: 1840 Tweet ID:  675891555769696257 Time: 0.013427930069155991
Success Count: 1841 Tweet ID:  675888385639251968 Time: -0.012161521794041619
Success Count: 1842 Tweet ID:  675878199931371520 Time: -0.006014495331328362
Success Count: 1843 Tweet ID:  675870721063669760 Time: 0.005941622133832425
Success Count: 1844 Tweet ID:  675853064436391936 Time: -0.002510161662939936
Success Count: 1845 Tweet ID:  675849018447167488 Time: -0.00186147668864578
Success Count: 1846 Tweet ID:  675845657354215424 Time: -0.001047788595315069
Success Count: 1847 Tweet ID:  675822767435051008 Time: 0.004917243582895026
Success Count: 1848 Tweet ID:  675820929667219457 Time: 0.00966495304601267
Success Count: 1849 Tweet ID:  675798442703122432 Time: 0.0080149220302701
Success Count: 1850 Tweet ID:  675781562965868544 Time: 0.009897543262923136
Success Count: 1851 Tweet ID:  675740360753160193 Time: 0.0015579011815134436
Success Count: 1852 Tweet ID:  675710890956750848 Time: 0.014516875060508028
Success Count: 1853 Tweet ID:  675707330206547968 Time: 0.0227504167414736
Success Count: 1854 Tweet ID:  675706639471788032 Time: -0.004023130633868277
Success Count: 1855 Tweet ID:  675534494439489536 Time: -0.013048083113972098
Success Count: 1856 Tweet ID:  675531475945709568 Time: -0.0024671173887327313
Success Count: 1857 Tweet ID:  675522403582218240 Time: 0.0005928029422648251
Success Count: 1858 Tweet ID:  675517828909424640 Time: 0.0030980560113675892
Success Count: 1859 Tweet ID:  675501075957489664 Time: 0.016666823968989775
Success Count: 1860 Tweet ID:  675497103322386432 Time: -0.007725694595137611
Success Count: 1861 Tweet ID:  675489971617296384 Time: 0.012609333440195769
Success Count: 1862 Tweet ID:  675483430902214656 Time: 0.009215631114784628
Success Count: 1863 Tweet ID:  675432746517426176 Time: 0.014008650410687551
Success Count: 1864 Tweet ID:  675372240448454658 Time: 0.02031161802005954
Success Count: 1865 Tweet ID:  675362609739206656 Time: -0.006908985844347626
Success Count: 1866 Tweet ID:  675354435921575936 Time: 0.01678349668509327
Success Count: 1867 Tweet ID:  675349384339542016 Time: 0.004181337280897424
Success Count: 1868 Tweet ID:  675334060156301312 Time: 0.01847204103250988
Success Count: 1869 Tweet ID:  675166823650848770 Time: -0.004009160154964775
Success Count: 1870 Tweet ID:  675153376133427200 Time: 0.007155546569265425
Success Count: 1871 Tweet ID:  675149409102012420 Time: 0.0036236494488548487
Success Count: 1872 Tweet ID:  675147105808306176 Time: -0.021249530400382355
Success Count: 1873 Tweet ID:  675146535592706048 Time: 0.039276780415093526
Success Count: 1874 Tweet ID:  675145476954566656 Time: -0.03061996988253668
Success Count: 1875 Tweet ID:  675135153782571009 Time: 0.007269576191902161
Success Count: 1876 Tweet ID:  675113801096802304 Time: -0.010398971469840035
Success Count: 1877 Tweet ID:  675111688094527488 Time: -0.012460566300433129
Success Count: 1878 Tweet ID:  675109292475830276 Time: -0.009705354284960777
Success Count: 1879 Tweet ID:  675047298674663426 Time: 0.00247391386074014
Success Count: 1880 Tweet ID:  675015141583413248 Time: -0.0033419736428186297
Success Count: 1881 Tweet ID:  675006312288268288 Time: -0.0018210754788015038
Success Count: 1882 Tweet ID:  675003128568291329 Time: 0.0036240269837435335
Success Count: 1883 Tweet ID:  674999807681908736 Time: 0.02126161297201179
Success Count: 1884 Tweet ID:  674805413498527744 Time: -0.001359670888632536
Success Count: 1885 Tweet ID:  674800520222154752 Time: -0.01044692427967675
Success Count: 1886 Tweet ID:  674793399141146624 Time: 0.023713627102551982
Success Count: 1887 Tweet ID:  674790488185167872 Time: -0.00146463856799528
Success Count: 1888 Tweet ID:  674788554665512960 Time: -0.020439618092495948
Success Count: 1889 Tweet ID:  674781762103414784 Time: -0.0005720359331462532
Success Count: 1890 Tweet ID:  674774481756377088 Time: 0.02709826748468913
Success Count: 1891 Tweet ID:  674767892831932416 Time: -0.011634795635472983
Success Count: 1892 Tweet ID:  674764817387900928 Time: -0.0008790097199380398
Success Count: 1893 Tweet ID:  674754018082705410 Time: 0.008990970149170607
Success Count: 1894 Tweet ID:  674752233200820224 Time: -0.013779458415228873
Success Count: 1895 Tweet ID:  674743008475090944 Time: 0.01936992976698093
Success Count: 1896 Tweet ID:  674742531037511680 Time: 0.005183816101634875
Success Count: 1897 Tweet ID:  674739953134403584 Time: 0.02857310068793595
Success Count: 1898 Tweet ID:  674737130913071104 Time: -0.02566874396870844
Success Count: 1899 Tweet ID:  674690135443775488 Time: 0.005778506922069937
Success Count: 1900 Tweet ID:  674670581682434048 Time: 0.003756935679120943

Success Count: 1901 Tweet ID:  674664755118911488 Time: 0.01844334483030252
Success Count: 1902 Tweet ID:  674646392044941312 Time: -0.013545735506340861
Success Count: 1903 Tweet ID:  674644256330530816 Time: 0.014536886883433908
Success Count: 1904 Tweet ID:  674638615994089473 Time: -0.009336079616332427
Success Count: 1905 Tweet ID:  674632714662858753 Time: 0.0011123550357297063
Success Count: 1906 Tweet ID:  674606911342424069 Time: 0.014336768712382764
Success Count: 1907 Tweet ID:  674468880899788800 Time: 0.014437205361900851
Success Count: 1908 Tweet ID:  674447403907457024 Time: -0.0053189902391750365
Success Count: 1909 Tweet ID:  674436901579923456 Time: 0.007797435100656003
Success Count: 1910 Tweet ID:  674422304705744896 Time: -0.017528464930364862
Success Count: 1911 Tweet ID:  674416750885273600 Time: 0.0020189281494822353
Success Count: 1912 Tweet ID:  674410619106390016 Time: 0.002734067471465096
Success Count: 1913 Tweet ID:  674394782723014656 Time: -0.0004168499435763806
Success Count: 1914 Tweet ID:  674372068062928900 Time: -0.0009114816784858704
Success Count: 1915 Tweet ID:  674330906434379776 Time: 0.0027355777856428176
Success Count: 1916 Tweet ID:  674318007229923329 Time: 0.01664794492535293
Success Count: 1917 Tweet ID:  674307341513269249 Time: 0.0006169681437313557
Success Count: 1918 Tweet ID:  674291837063053312 Time: -0.0039276025199797004
Success Count: 1919 Tweet ID:  674271431610523648 Time: 0.016110268916236237
Success Count: 1920 Tweet ID:  674269164442398721 Time: 0.009404421842191368
Success Count: 1921 Tweet ID:  674265582246694913 Time: -0.00984883526689373
Success Count: 1922 Tweet ID:  674262580978937856 Time: 0.015491790429223329
Success Count: 1923 Tweet ID:  674255168825880576 Time: -0.013765865500317886
Success Count: 1924 Tweet ID:  674082852460433408 Time: -0.003677643573610112
Success Count: 1925 Tweet ID:  674075285688614912 Time: 0.039035505877109244
Success Count: 1926 Tweet ID:  674063288070742018 Time: -0.020162473287200555
Success Count: 1927 Tweet ID:  674053186244734976 Time: 0.025435021030716598
Success Count: 1928 Tweet ID:  674051556661161984 Time: -0.03957582495058887
Success Count: 1929 Tweet ID:  674045139690631169 Time: 0.01573230983922258
Success Count: 1930 Tweet ID:  674042553264685056 Time: 0.001954739331267774
Success Count: 1931 Tweet ID:  674038233588723717 Time: 0.0023538429231848568
Success Count: 1932 Tweet ID:  674036086168010753 Time: -0.0010545850382186472
Success Count: 1933 Tweet ID:  674024893172875264 Time: 0.01658866461366415
Success Count: 1934 Tweet ID:  674019345211760640 Time: -0.008041352703003213
Success Count: 1935 Tweet ID:  674014384960745472 Time: 0.021377152937930077
Success Count: 1936 Tweet ID:  674008982932058114 Time: 0.025154478033073246
Success Count: 1937 Tweet ID:  673956914389192708 Time: -0.020761317515280098
Success Count: 1938 Tweet ID:  673919437611909120 Time: 0.01161667171982117
Success Count: 1939 Tweet ID:  673906403526995968 Time: -0.006418885139282793
Success Count: 1940 Tweet ID:  673887867907739649 Time: -0.009667973761679605
Success Count: 1941 Tweet ID:  673716320723169284 Time: 0.0005203072796575725
Success Count: 1942 Tweet ID:  673715861853720576 Time: -0.017915108328452334
Success Count: 1943 Tweet ID:  673711475735838725 Time: 0.054767815716331825
Success Count: 1944 Tweet ID:  673709992831262724 Time: -0.007309222215553746
Success Count: 1945 Tweet ID:  673708611235921920 Time: -0.0003156581078656018
Success Count: 1946 Tweet ID:  673707060090052608 Time: -0.0015035294636618346
Success Count: 1947 Tweet ID:  673705679337693185 Time: 0.00010836587171070278
Success Count: 1948 Tweet ID:  673700254269775872 Time: -0.005200429703108966
Success Count: 1949 Tweet ID:  673697980713705472 Time: 0.012614997162017971
Success Count: 1950 Tweet ID:  673689733134946305 Time: 0.010863396688364446
Success Count: 1951 Tweet ID:  673688752737402881 Time: 4.87080542370677e-05
Success Count: 1952 Tweet ID:  673686845050527744 Time: 0.0008729683759156615
Success Count: 1953 Tweet ID:  673680198160809984 Time: 0.00816029089037329
Success Count: 1954 Tweet ID:  673662677122719744 Time: 0.006039415748091415
Success Count: 1955 Tweet ID:  673656262056419329 Time: 0.025516578636597842
Success Count: 1956 Tweet ID:  673636718965334016 Time: -0.018615144421346486
Success Count: 1957 Tweet ID:  673612854080196609 Time: -0.00010496765025891364
Success Count: 1958 Tweet ID:  673583129559498752 Time: 0.033291358849965036
Success Count: 1959 Tweet ID:  673580926094458881 Time: 0.0013536296028178185
Success Count: 1960 Tweet ID:  673576835670777856 Time: 0.030095509224338457
Success Count: 1961 Tweet ID:  673363615379013632 Time: 0.008687772206030786
Success Count: 1962 Tweet ID:  673359818736984064 Time: 0.02640238479943946
Success Count: 1963 Tweet ID:  673355879178194945 Time: -0.023734394082566723
Success Count: 1964 Tweet ID:  673352124999274496 Time: 0.019583640911150724
Success Count: 1965 Tweet ID:  673350198937153538 Time: -0.006847440090496093
Success Count: 1966 Tweet ID:  673345638550134785 Time: -0.00013404141645878553
Success Count: 1967 Tweet ID:  673343217010679808 Time: 0.001779541518772021
Success Count: 1968 Tweet ID:  673342308415348736 Time: 0.008494828070979565
Success Count: 1969 Tweet ID:  673320132811366400 Time: 0.026808284892467782
Success Count: 1970 Tweet ID:  673317986296586240 Time: 0.020101305097341537
Success Count: 1971 Tweet ID:  673295268553605120 Time: 0.02099088704562746
Success Count: 1972 Tweet ID:  673270968295534593 Time: 0.020925187913235277
Success Count: 1973 Tweet ID:  673240798075449344 Time: -0.0023761202464811504
Success Count: 1974 Tweet ID:  673213039743795200 Time: -0.0015511046804022044
Success Count: 1975 Tweet ID:  673148804208660480 Time: 0.008692680770764127
Success Count: 1976 Tweet ID:  672997845381865473 Time: 0.018390483455732465
Success Count: 1977 Tweet ID:  672995267319328768 Time: 0.0011754111328627914
Success Count: 1978 Tweet ID:  672988786805112832 Time: -0.00440222246106714
Success Count: 1979 Tweet ID:  672984142909456390 Time: 0.0012494170805439353
Success Count: 1980 Tweet ID:  672980819271634944 Time: -0.0002499589463695884
Success Count: 1981 Tweet ID:  672975131468300288 Time: 0.0012788684689439833
Success Count: 1982 Tweet ID:  672970152493887488 Time: 0.0038887116534169763
Success Count: 1983 Tweet ID:  672968025906282496 Time: 0.013193074380978942
Success Count: 1984 Tweet ID:  672964561327235073 Time: 0.0004481891810428351
Success Count: 1985 Tweet ID:  672902681409806336 Time: -0.012918950262246653
Success Count: 1986 Tweet ID:  672898206762672129 Time: 0.01026568523957394
Success Count: 1987 Tweet ID:  672884426393653248 Time: -0.001202596991788596
Success Count: 1988 Tweet ID:  672877615439593473 Time: 0.019506614306010306
Success Count: 1989 Tweet ID:  672834301050937345 Time: 0.008273187762824818
Success Count: 1990 Tweet ID:  672828477930868736 Time: -0.011449403129518032
Success Count: 1991 Tweet ID:  672640509974827008 Time: 0.0006992809067014605
Success Count: 1992 Tweet ID:  672622327801233409 Time: -0.0004806611977983266
Success Count: 1993 Tweet ID:  672614745925664768 Time: 0.0013120956136845052
Success Count: 1994 Tweet ID:  672609152938721280 Time: 0.01517839782172814
Success Count: 1995 Tweet ID:  672604026190569472 Time: 0.012106017326004803
Success Count: 1996 Tweet ID:  672594978741354496 Time: 0.013840249070199206
Success Count: 1997 Tweet ID:  672591762242805761 Time: 0.015550693147815764
Success Count: 1998 Tweet ID:  672591271085670400 Time: -0.007275239884620532
Success Count: 1999 Tweet ID:  672538107540070400 Time: 0.01402790701831691
Success Count: 2000 Tweet ID:  672523490734551040 Time: 0.009875265968730673
Success Count: 2001 Tweet ID:  672488522314567680 Time: 0.009603784885257483
Success Count: 2002 Tweet ID:  672482722825261057 Time: -0.005605574639048427
Success Count: 2003 Tweet ID:  672481316919734272 Time: 0.00263514113612473
Success Count: 2004 Tweet ID:  672475084225949696 Time: -0.0033246048842556775
Success Count: 2005 Tweet ID:  672466075045466113 Time: 0.0072325732035096735
Success Count: 2006 Tweet ID:  672272411274932228 Time: 0.018042730866000056

Success Count: 2007 Tweet ID:  672267570918129665 Time: -0.004714482318377122
Success Count: 2008 Tweet ID:  672264251789176834 Time: 0.03935154157807119
Success Count: 2009 Tweet ID:  672256522047614977 Time: -0.04195836407598108
Success Count: 2010 Tweet ID:  672254177670729728 Time: -0.001266408246010542
Success Count: 2011 Tweet ID:  672248013293752320 Time: 0.000680401804856956
Success Count: 2012 Tweet ID:  672245253877968896 Time: 0.01095665933098644
Success Count: 2013 Tweet ID:  672239279297454080 Time: 0.013099434174364433
Success Count: 2014 Tweet ID:  672231046314901505 Time: 0.0036863279819954187
Success Count: 2015 Tweet ID:  672222792075620352 Time: 0.025111056165769696
Success Count: 2016 Tweet ID:  672205392827572224 Time: 0.0031467640365008265
Success Count: 2017 Tweet ID:  672169685991993344 Time: -0.021553861035499722
Success Count: 2018 Tweet ID:  672160042234327040 Time: 0.014760792691959068
Success Count: 2019 Tweet ID:  672139350159835138 Time: -0.007070590771036223
Success Count: 2020 Tweet ID:  672125275208069120 Time: -0.00022315065143629909
Success Count: 2021 Tweet ID:  672095186491711488 Time: 0.020183617860311642
Success Count: 2022 Tweet ID:  672082170312290304 Time: 0.019176608067937195
Success Count: 2023 Tweet ID:  672068090318987265 Time: 0.019810567377135158
Success Count: 2024 Tweet ID:  671896809300709376 Time: -0.003093525068834424
Success Count: 2025 Tweet ID:  671891728106971137 Time: -0.01328935768106021
Success Count: 2026 Tweet ID:  671882082306625538 Time: 0.040462008677423
Success Count: 2027 Tweet ID:  671879137494245376 Time: 0.02995731440023519
Success Count: 2028 Tweet ID:  671874878652489728 Time: 0.00979370836284943
Success Count: 2029 Tweet ID:  671866342182637568 Time: -0.008608480100519955
Success Count: 2030 Tweet ID:  671855973984772097 Time: 0.008963406697148457
Success Count: 2031 Tweet ID:  671789708968640512 Time: -0.01564055753988214
Success Count: 2032 Tweet ID:  671768281401958400 Time: 0.01683447018149309
Success Count: 2033 Tweet ID:  671763349865160704 Time: -0.032049870962509885
Success Count: 2034 Tweet ID:  671744970634719232 Time: 0.03113121521892026
Success Count: 2035 Tweet ID:  671743150407421952 Time: 0.006042813969543204
Success Count: 2036 Tweet ID:  671735591348891648 Time: -0.005697704502381384
Success Count: 2037 Tweet ID:  671729906628341761 Time: 0.015373607398942113
Success Count: 2038 Tweet ID:  671561002136281088 Time: -0.002514315041480586
Success Count: 2039 Tweet ID:  671550332464455680 Time: 0.002649489208124578
Success Count: 2040 Tweet ID:  671547767500775424 Time: -0.00018728041322901845
Success Count: 2041 Tweet ID:  671544874165002241 Time: -0.012876283522928134
Success Count: 2042 Tweet ID:  671542985629241344 Time: -0.0024486158799845725
Success Count: 2043 Tweet ID:  671538301157904385 Time: -0.00039683812065050006
Success Count: 2044 Tweet ID:  671536543010570240 Time: -0.0009866204054560512
Success Count: 2045 Tweet ID:  671533943490011136 Time: 0.00822372458060272
Success Count: 2046 Tweet ID:  671528761649688577 Time: 0.01694132573902607
Success Count: 2047 Tweet ID:  671520732782923777 Time: -0.002738976036198437
Success Count: 2048 Tweet ID:  671518598289059840 Time: 0.009900941513478756
Success Count: 2049 Tweet ID:  671511350426865664 Time: 0.0228682222077623
Success Count: 2050 Tweet ID:  671504605491109889 Time: -0.004736759641673416
Success Count: 2051 Tweet ID:  671497587707535361 Time: 0.011346700979629532
Success Count: 2052 Tweet ID:  671488513339211776 Time: -0.011892306210938841
Success Count: 2053 Tweet ID:  671486386088865792 Time: -0.0005240830651018769
Success Count: 2054 Tweet ID:  671485057807351808 Time: 0.01874352211598307
Success Count: 2055 Tweet ID:  671390180817915904 Time: -0.008500114228809252
Success Count: 2056 Tweet ID:  671362598324076544 Time: 0.0072650451911613345
Success Count: 2057 Tweet ID:  671357843010908160 Time: 0.014759659970877692
Success Count: 2058 Tweet ID:  671355857343524864 Time: -0.011314606555970386
Success Count: 2059 Tweet ID:  671347597085433856 Time: -0.001322290307143703
Success Count: 2060 Tweet ID:  671186162933985280 Time: 0.030441373877692968
Success Count: 2061 Tweet ID:  671182547775299584 Time: -0.005542518512811512
Success Count: 2062 Tweet ID:  671166507850801152 Time: 0.00858053908450529
Success Count: 2063 Tweet ID:  671163268581498880 Time: -0.0035409590927883983
Success Count: 2064 Tweet ID:  671159727754231808 Time: 0.00633808269049041
Success Count: 2065 Tweet ID:  671154572044468225 Time: 0.018007993407081813
Success Count: 2066 Tweet ID:  671151324042559489 Time: 0.0010179596429225057
Success Count: 2067 Tweet ID:  671147085991960577 Time: 0.019394850154640153
Success Count: 2068 Tweet ID:  671141549288370177 Time: -0.013482679380103946
Success Count: 2069 Tweet ID:  671138694582165504 Time: -0.010962323023704812
Success Count: 2070 Tweet ID:  671134062904504320 Time: 0.01980528121930547
Success Count: 2071 Tweet ID:  671122204919246848 Time: -0.0007680007256567478
Success Count: 2072 Tweet ID:  671115716440031232 Time: 0.034849637624574825
Success Count: 2073 Tweet ID:  671109016219725825 Time: -0.013538183848140761
Success Count: 2074 Tweet ID:  670995969505435648 Time: -0.009729519515531138
Success Count: 2075 Tweet ID:  670842764863651840 Time: 0.003125619434285909
Success Count: 2076 Tweet ID:  670840546554966016 Time: 0.00474393370677717
Success Count: 2077 Tweet ID:  670838202509447168 Time: -6.267853314056993e-05
Success Count: 2078 Tweet ID:  670833812859932673 Time: -0.005273302929708734
Success Count: 2079 Tweet ID:  670832455012716544 Time: 0.0007189151365309954
Success Count: 2080 Tweet ID:  670826280409919488 Time: -0.00033718024496920407
Success Count: 2081 Tweet ID:  670823764196741120 Time: 0.011301391205051914
Success Count: 2082 Tweet ID:  670822709593571328 Time: 0.004185868252534419
Success Count: 2083 Tweet ID:  670815497391357952 Time: 0.0018996123981196433
Success Count: 2084 Tweet ID:  670811965569282048 Time: 0.01195083133643493
Success Count: 2085 Tweet ID:  670807719151067136 Time: -0.001556768431328237
Success Count: 2086 Tweet ID:  670804601705242624 Time: 0.0009390451305080205
Success Count: 2087 Tweet ID:  670803562457407488 Time: 0.0038592602941207588
Success Count: 2088 Tweet ID:  670797304698376195 Time: -0.035372587968595326
Success Count: 2089 Tweet ID:  670792680469889025 Time: -0.0021121907921042293
Success Count: 2090 Tweet ID:  670789397210615808 Time: 0.024488801864208654
Success Count: 2091 Tweet ID:  670786190031921152 Time: 0.01412230241112411
Success Count: 2092 Tweet ID:  670783437142401025 Time: -0.009308516164310277
Success Count: 2093 Tweet ID:  670782429121134593 Time: 0.0009722722752485424
Success Count: 2094 Tweet ID:  670780561024270336 Time: 0.010826771263964474
Success Count: 2095 Tweet ID:  670778058496974848 Time: 0.01150301966117695
Success Count: 2096 Tweet ID:  670764103623966721 Time: 0.0010972517484333366
Success Count: 2097 Tweet ID:  670755717859713024 Time: -0.016374198312405497
Success Count: 2098 Tweet ID:  670733412878163972 Time: 0.022417767468141392
Success Count: 2099 Tweet ID:  670727704916926465 Time: 0.008703630621312186
Success Count: 2100 Tweet ID:  670717338665226240 Time: 0.021770970401121303
Success Count: 2101 Tweet ID:  670704688707301377 Time: 0.010332139529054984
Success Count: 2102 Tweet ID:  670691627984359425 Time: 0.0307577871135436
Success Count: 2103 Tweet ID:  670679630144274432 Time: -0.004805101896636188
Success Count: 2104 Tweet ID:  670676092097810432 Time: 0.013832697470206767
Success Count: 2105 Tweet ID:  670668383499735048 Time: -0.01761795170023106
Success Count: 2106 Tweet ID:  670474236058800128 Time: 0.0256947971356567
Success Count: 2107 Tweet ID:  670468609693655041 Time: 0.016050988604547456
Success Count: 2108 Tweet ID:  670465786746662913 Time: 0.01716107813990675
Success Count: 2109 Tweet ID:  670452855871037440 Time: -0.02868335449602455
Success Count: 2110 Tweet ID:  670449342516494336 Time: -0.0034106934908777475
Success Count: 2111 Tweet ID:  670444955656130560 Time: -0.0029149290057830513
Success Count: 2112 Tweet ID:  670442337873600512 Time: -0.005391108337789774

Success Count: 2113 Tweet ID:  670435821946826752 Time: 0.00034926284570246935
Success Count: 2114 Tweet ID:  670434127938719744 Time: 0.0011599302815739065
Success Count: 2115 Tweet ID:  670433248821026816 Time: -0.0003722953551914543
Success Count: 2116 Tweet ID:  670428280563085312 Time: 0.00712836068123579
Success Count: 2117 Tweet ID:  670427002554466305 Time: 0.02742336509982124
Success Count: 2118 Tweet ID:  670421925039075328 Time: -0.02846511238021776
Success Count: 2119 Tweet ID:  670420569653809152 Time: 0.0010440128098707646
Success Count: 2120 Tweet ID:  670417414769758208 Time: -0.0008869388839229941
Success Count: 2121 Tweet ID:  670411370698022913 Time: -0.006219522096216679
Success Count: 2122 Tweet ID:  670408998013820928 Time: -0.0016757066186983138
Success Count: 2123 Tweet ID:  670403879788544000 Time: -0.0012694289034698159
Success Count: 2124 Tweet ID:  670385711116361728 Time: -0.0030531238298863173
Success Count: 2125 Tweet ID:  670374371102445568 Time: -0.0002967790642287582
Success Count: 2126 Tweet ID:  670361874861563904 Time: -0.004346340399933979
Success Count: 2127 Tweet ID:  670338931251150849 Time: -0.008460468176053837
Success Count: 2128 Tweet ID:  670319130621435904 Time: 0.005192878044908866
Success Count: 2129 Tweet ID:  670303360680108032 Time: -0.01382741125416942
Success Count: 2130 Tweet ID:  670290420111441920 Time: 0.01424765947740525
Success Count: 2131 Tweet ID:  670093938074779648 Time: -0.01090568580548279
Success Count: 2132 Tweet ID:  670086499208155136 Time: 0.03059920293162577
Success Count: 2133 Tweet ID:  670079681849372674 Time: -0.018157515674829483
Success Count: 2134 Tweet ID:  670073503555706880 Time: -0.005226105218753219
Success Count: 2135 Tweet ID:  670069087419133954 Time: 0.0009024197061080486
Success Count: 2136 Tweet ID:  670061506722140161 Time: 1.4725665096193552e-05
Success Count: 2137 Tweet ID:  670055038660800512 Time: 0.02121554804034531
Success Count: 2138 Tweet ID:  670046952931721218 Time: -0.011651409236947075
Success Count: 2139 Tweet ID:  670040295598354432 Time: 0.002377630560658872
Success Count: 2140 Tweet ID:  670037189829525505 Time: -0.0001200708793476224
Success Count: 2141 Tweet ID:  670003130994700288 Time: 0.0031188229913823307
Success Count: 2142 Tweet ID:  669993076832759809 Time: 0.005245739477686584
Success Count: 2143 Tweet ID:  669972011175813120 Time: 0.04040272839483805
Success Count: 2144 Tweet ID:  669970042633789440 Time: -0.008215795358410105
Success Count: 2145 Tweet ID:  669942763794931712 Time: -0.03795373495086096
Success Count: 2146 Tweet ID:  669926384437997569 Time: 0.005340890027582645
Success Count: 2147 Tweet ID:  669923323644657664 Time: -0.005833256262121722
Success Count: 2148 Tweet ID:  669753178989142016 Time: -0.0037977145111653954
Success Count: 2149 Tweet ID:  669749430875258880 Time: 0.002356485987547785
Success Count: 2150 Tweet ID:  669684865554620416 Time: -0.0030572772084269673
Success Count: 2151 Tweet ID:  669683899023405056 Time: -0.0031429882219526917
Success Count: 2152 Tweet ID:  669682095984410625 Time: -0.000962077610893175
Success Count: 2153 Tweet ID:  669680153564442624 Time: 0.003602127282647416
Success Count: 2154 Tweet ID:  669661792646373376 Time: 0.011903633654583246
Success Count: 2155 Tweet ID:  669625907762618368 Time: 0.0076407387387007475
Success Count: 2156 Tweet ID:  669603084620980224 Time: 0.01106275970232673
Success Count: 2157 Tweet ID:  669597912108789760 Time: 0.035480198712321
Success Count: 2158 Tweet ID:  669583744538451968 Time: -0.002997996925842017
Success Count: 2159 Tweet ID:  669573570759163904 Time: -0.031043993891216815
Success Count: 2160 Tweet ID:  669571471778410496 Time: -0.024404978757956997
Success Count: 2161 Tweet ID:  669567591774625800 Time: 0.000552779296413064
Success Count: 2162 Tweet ID:  669564461267722241 Time: 0.0013355057162698358
Success Count: 2163 Tweet ID:  669393256313184256 Time: 0.026379352319054306
Success Count: 2164 Tweet ID:  669375718304980992 Time: -0.027085429697763175
Success Count: 2165 Tweet ID:  669371483794317312 Time: -0.0008774993475526571
Success Count: 2166 Tweet ID:  669367896104181761 Time: -3.7759309634566307e-07
Success Count: 2167 Tweet ID:  669363888236994561 Time: 0.019885328511008993
Success Count: 2168 Tweet ID:  669359674819481600 Time: -0.005904241523239762
Success Count: 2169 Tweet ID:  669354382627049472 Time: 0.015071919828187674
Success Count: 2170 Tweet ID:  669353438988365824 Time: 0.026895506220171228
Success Count: 2171 Tweet ID:  669351434509529089 Time: 0.01451838540378958
Success Count: 2172 Tweet ID:  669328503091937280 Time: -0.0033393305784557015
Success Count: 2173 Tweet ID:  669327207240699904 Time: -0.02725458619534038
Success Count: 2174 Tweet ID:  669324657376567296 Time: 0.02564306845306419
Success Count: 2175 Tweet ID:  669216679721873412 Time: 0.0038033782329875976
Success Count: 2176 Tweet ID:  669214165781868544 Time: -0.0005456052604131401
Success Count: 2177 Tweet ID:  669203728096960512 Time: 0.053897112811682746
Success Count: 2178 Tweet ID:  669037058363662336 Time: 0.018952702230308205
Success Count: 2179 Tweet ID:  669015743032369152 Time: 0.005944642791291699
Success Count: 2180 Tweet ID:  669006782128353280 Time: -0.0009956823487300426
Success Count: 2181 Tweet ID:  669000397445533696 Time: 0.01722375667304732
Success Count: 2182 Tweet ID:  668994913074286592 Time: 0.005268016771879047
Success Count: 2183 Tweet ID:  668992363537309700 Time: 0.01844863098813221
Success Count: 2184 Tweet ID:  668989615043424256 Time: -0.019253634702181444
Success Count: 2185 Tweet ID:  668988183816871936 Time: 0.03414167233859189
Success Count: 2186 Tweet ID:  668986018524233728 Time: 0.00865152437472716
Success Count: 2187 Tweet ID:  668981893510119424 Time: -0.02290749063831754
Success Count: 2188 Tweet ID:  668979806671884288 Time: 0.001438207837054506
Success Count: 2189 Tweet ID:  668975677807423489 Time: 0.0010255112720187753
Success Count: 2190 Tweet ID:  668967877119254528 Time: -0.003002527926582843
Success Count: 2191 Tweet ID:  668960084974809088 Time: -0.001333617779891938
Success Count: 2192 Tweet ID:  668955713004314625 Time: -6.34336902294308e-05
Success Count: 2193 Tweet ID:  668932921458302977 Time: 0.022273908922215924
Success Count: 2194 Tweet ID:  668902994700836864 Time: 0.00767396594164893
Success Count: 2195 Tweet ID:  668892474547511297 Time: 0.0073080894944723696
Success Count: 2196 Tweet ID:  668872652652679168 Time: -0.012945380934979767
Success Count: 2197 Tweet ID:  668852170888998912 Time: 0.005775863857707009
Success Count: 2198 Tweet ID:  668826086256599040 Time: -0.015487637050682679
Success Count: 2199 Tweet ID:  668815180734689280 Time: 0.01612990314606577
Success Count: 2200 Tweet ID:  668779399630725120 Time: -0.019262696645455435
Success Count: 2201 Tweet ID:  668655139528511488 Time: -0.003968381322920322
Success Count: 2202 Tweet ID:  668645506898350081 Time: 0.02289993900922127
Success Count: 2203 Tweet ID:  668643542311546881 Time: -0.03259434347273782
Success Count: 2204 Tweet ID:  668641109086707712 Time: 0.02091499319067225
Success Count: 2205 Tweet ID:  668636665813057536 Time: -0.0042375969351269305
Success Count: 2206 Tweet ID:  668633411083464705 Time: 0.009889991662930697
Success Count: 2207 Tweet ID:  668631377374486528 Time: 0.025207339407643303
Success Count: 2208 Tweet ID:  668627278264475648 Time: 0.03312069200910628
Success Count: 2209 Tweet ID:  668625577880875008 Time: 0.0028518728795461357
Success Count: 2210 Tweet ID:  668623201287675904 Time: 0.023550511890789494
Success Count: 2211 Tweet ID:  668620235289837568 Time: 0.007647535239811987
Success Count: 2212 Tweet ID:  668614819948453888 Time: 0.011877958109835163
Success Count: 2213 Tweet ID:  668587383441514497 Time: -0.008169352833647281
Success Count: 2214 Tweet ID:  668567822092664832 Time: -0.006066979141905904
Success Count: 2215 Tweet ID:  668544745690562560 Time: 0.029660535365110263
Success Count: 2216 Tweet ID:  668542336805281792 Time: -0.017921149672474712
Success Count: 2217 Tweet ID:  668537837512433665 Time: 0.015628474939148873
Success Count: 2218 Tweet ID:  668528771708952576 Time: 0.00460271822521463

Success Count: 2219 Tweet ID:  668507509523615744 Time: -0.017595296842046082
Success Count: 2220 Tweet ID:  668496999348633600 Time: 0.017729338287608698
Success Count: 2221 Tweet ID:  668484198282485761 Time: -0.00655028346227482
Success Count: 2222 Tweet ID:  668480044826800133 Time: 0.01488010844332166
Success Count: 2223 Tweet ID:  668466899341221888 Time: -0.031518613832304254
Success Count: 2224 Tweet ID:  668297328638447616 Time: -0.00017784087685868144
Success Count: 2225 Tweet ID:  668291999406125056 Time: -0.0037418324209284037
Success Count: 2226 Tweet ID:  668286279830867968 Time: 0.0022477425227407366
Success Count: 2227 Tweet ID:  668274247790391296 Time: -0.0006313162157312036
Success Count: 2228 Tweet ID:  668268907921326080 Time: 0.01418913435190916
Success Count: 2229 Tweet ID:  668256321989451776 Time: -0.0027472828223835677
Success Count: 2230 Tweet ID:  668248472370458624 Time: 0.009209967422066256
Success Count: 2231 Tweet ID:  668237644992782336 Time: -0.012865333672380075
Success Count: 2232 Tweet ID:  668226093875376128 Time: 0.00020615948596969247
Success Count: 2233 Tweet ID:  668221241640230912 Time: 0.012668236129684374
Success Count: 2234 Tweet ID:  668204964695683073 Time: -0.016492381342686713
Success Count: 2235 Tweet ID:  668190681446379520 Time: -0.0041945526318158954
Success Count: 2236 Tweet ID:  668171859951755264 Time: 0.016103472444228828
Success Count: 2237 Tweet ID:  668154635664932864 Time: 0.005109432531753555
Success Count: 2238 Tweet ID:  668142349051129856 Time: 0.020308974926592782
Success Count: 2239 Tweet ID:  668113020489474048 Time: -0.012249875871930271
Success Count: 2240 Tweet ID:  667937095915278337 Time: -0.016806529136374593
Success Count: 2241 Tweet ID:  667924896115245057 Time: 0.02011112222680822
Success Count: 2242 Tweet ID:  667915453470232577 Time: 0.023921296931803226
Success Count: 2243 Tweet ID:  667911425562669056 Time: -0.017594919248949736
Success Count: 2244 Tweet ID:  667902449697558528 Time: -0.021408869797596708
Success Count: 2245 Tweet ID:  667886921285246976 Time: 0.014691695309011266
Success Count: 2246 Tweet ID:  667885044254572545 Time: 0.012134335935115814
Success Count: 2247 Tweet ID:  667878741721415682 Time: 0.013809664960717782
Success Count: 2248 Tweet ID:  667873844930215936 Time: 0.030080783559242263
Success Count: 2249 Tweet ID:  667866724293877760 Time: 0.0031335486855823547
Success Count: 2250 Tweet ID:  667861340749471744 Time: 0.013822880282532424
Success Count: 2251 Tweet ID:  667832474953625600 Time: 0.0005697704327758402
Success Count: 2252 Tweet ID:  667806454573760512 Time: -0.020061281480593607
Success Count: 2253 Tweet ID:  667801013445750784 Time: 0.014103423338383436
Success Count: 2254 Tweet ID:  667793409583771648 Time: 0.019742980279261246
Success Count: 2255 Tweet ID:  667782464991965184 Time: -0.004088452231371775
Success Count: 2256 Tweet ID:  667773195014021121 Time: -0.02410971006611362
Success Count: 2257 Tweet ID:  667766675769573376 Time: 0.003410693461773917
Success Count: 2258 Tweet ID:  667728196545200128 Time: -6.645434768870473e-05
Success Count: 2259 Tweet ID:  667724302356258817 Time: -0.001752355630742386
Success Count: 2260 Tweet ID:  667550904950915073 Time: -0.004727320105303079
Success Count: 2261 Tweet ID:  667550882905632768 Time: -0.0025078961916733533
Success Count: 2262 Tweet ID:  667549055577362432 Time: -0.002452769287629053
Success Count: 2263 Tweet ID:  667546741521195010 Time: -3.738058148883283e-05
Success Count: 2264 Tweet ID:  667544320556335104 Time: 0.0025988933339249343
Success Count: 2265 Tweet ID:  667538891197542400 Time: 0.0022787042253185064
Success Count: 2266 Tweet ID:  667534815156183040 Time: -0.0044773611589334905
Success Count: 2267 Tweet ID:  667530908589760512 Time: 0.00042893257341347635
Success Count: 2268 Tweet ID:  667524857454854144 Time: 0.0008276586304418743
Success Count: 2269 Tweet ID:  667517642048163840 Time: 0.001167104346677661
Success Count: 2270 Tweet ID:  667509364010450944 Time: 0.0065385784546379
Success Count: 2271 Tweet ID:  667502640335572993 Time: -0.00632637765374966
Success Count: 2272 Tweet ID:  667495797102141441 Time: -0.0010530747240409255
Success Count: 2273 Tweet ID:  667491009379606528 Time: -0.002308910741703585
Success Count: 2274 Tweet ID:  667470559035432960 Time: 0.0011931574845220894
Success Count: 2275 Tweet ID:  667455448082227200 Time: 0.0014835176116321236
Success Count: 2276 Tweet ID:  667453023279554560 Time: 0.010639868443831801
Success Count: 2277 Tweet ID:  667443425659232256 Time: -0.011509438598295674
Success Count: 2278 Tweet ID:  667437278097252352 Time: 0.013091505010379478
Success Count: 2279 Tweet ID:  667435689202614272 Time: 0.01598453422775492
Success Count: 2280 Tweet ID:  667405339315146752 Time: -0.004715615039458498
Success Count: 2281 Tweet ID:  667393430834667520 Time: 0.011332352907629684
Success Count: 2282 Tweet ID:  667369227918143488 Time: -0.005185703979805112
Success Count: 2283 Tweet ID:  667211855547486208 Time: 0.024655692890519276
Success Count: 2284 Tweet ID:  667200525029539841 Time: 0.00038211242645047605
Success Count: 2285 Tweet ID:  667192066997374976 Time: 0.013603127881651744
Success Count: 2286 Tweet ID:  667188689915760640 Time: -0.00246220882399939
Success Count: 2287 Tweet ID:  667182792070062081 Time: -0.0033238497853744775
Success Count: 2288 Tweet ID:  667177989038297088 Time: 0.01363522230531089
Success Count: 2289 Tweet ID:  667176164155375616 Time: -0.03351337675121613
Success Count: 2290 Tweet ID:  667174963120574464 Time: 0.042744111153297126
Success Count: 2291 Tweet ID:  667171260800061440 Time: -0.03542582696536556
Success Count: 2292 Tweet ID:  667165590075940865 Time: 0.028590847039595246
Success Count: 2293 Tweet ID:  667160273090932737 Time: -0.05273869287339039
Success Count: 2294 Tweet ID:  667152164079423490 Time: 0.01057228137506172
Success Count: 2295 Tweet ID:  667138269671505920 Time: 0.005654660199070349
Success Count: 2296 Tweet ID:  667119796878725120 Time: -0.005979757872410119
Success Count: 2297 Tweet ID:  667090893657276420 Time: -0.0015258067287504673
Success Count: 2298 Tweet ID:  667073648344346624 Time: 0.0017938895907718688
Success Count: 2299 Tweet ID:  667070482143944705 Time: -0.0030501031724270433
Success Count: 2300 Tweet ID:  667065535570550784 Time: 0.018239828408695757
Success Count: 2301 Tweet ID:  667062181243039745 Time: 0.004604228539392352
Success Count: 2302 Tweet ID:  667044094246576128 Time: 0.0031743274885229766
Success Count: 2303 Tweet ID:  667012601033924608 Time: 0.0053401348704937845
Success Count: 2304 Tweet ID:  666996132027977728 Time: 0.004640853934688494
Success Count: 2305 Tweet ID:  666983947667116034 Time: 0.012513427733210847
Success Count: 2306 Tweet ID:  666837028449972224 Time: -0.015685112157370895
Success Count: 2307 Tweet ID:  666835007768551424 Time: -0.0018418424588162452
Success Count: 2308 Tweet ID:  666826780179869698 Time: 0.021201955125434324
Success Count: 2309 Tweet ID:  666817836334096384 Time: -0.01807255981839262
Success Count: 2310 Tweet ID:  666804364988780544 Time: 0.015115341724595055
Success Count: 2311 Tweet ID:  666786068205871104 Time: 0.0011251927935518324
Success Count: 2312 Tweet ID:  666781792255496192 Time: 0.01096836433862336
Success Count: 2313 Tweet ID:  666776908487630848 Time: -0.0008408739231526852
Success Count: 2314 Tweet ID:  666739327293083650 Time: -0.020147370029008016
Success Count: 2315 Tweet ID:  666701168228331520 Time: 0.024819563259370625
Success Count: 2316 Tweet ID:  666691418707132416 Time: -0.027119034435600042
Success Count: 2317 Tweet ID:  666649482315059201 Time: 0.028717714420054108
Success Count: 2318 Tweet ID:  666644823164719104 Time: -0.0043391663348302245
Success Count: 2319 Tweet ID:  666454714377183233 Time: -0.005405456438893452
Success Count: 2320 Tweet ID:  666447344410484738 Time: 0.009047229774296284
Success Count: 2321 Tweet ID:  666437273139982337 Time: 0.011797533283242956
Success Count: 2322 Tweet ID:  666435652385423360 Time: -0.02324580366257578
Success Count: 2323 Tweet ID:  666430724426358785 Time: 0.023237874469486997
Success Count: 2324 Tweet ID:  666428276349472768 Time: 0.001203729712869972

Success Count: 2325 Tweet ID:  666421158376562688 Time: 0.007043782446999103
Success Count: 2326 Tweet ID:  666418789513326592 Time: 0.012755079893395305
Success Count: 2327 Tweet ID:  666411507551481857 Time: 0.024611515837023035
Success Count: 2328 Tweet ID:  666407126856765440 Time: -0.013834585319273174
Success Count: 2329 Tweet ID:  666396247373291520 Time: 0.015478575078304857
Success Count: 2330 Tweet ID:  666373753744588802 Time: -0.0021231406135484576
Success Count: 2331 Tweet ID:  666362758909284353 Time: -0.0013373935944400728
Success Count: 2332 Tweet ID:  666353288456101888 Time: -0.0027329347212798893
Success Count: 2333 Tweet ID:  666345417576210432 Time: -0.0035141508269589394
Success Count: 2334 Tweet ID:  666337882303524864 Time: -0.000642643659375608
Success Count: 2335 Tweet ID:  666293911632134144 Time: 0.018934200750663877
Success Count: 2336 Tweet ID:  666287406224695296 Time: -0.02075942960800603
Success Count: 2337 Tweet ID:  666273097616637952 Time: 0.011995385953923687
Success Count: 2338 Tweet ID:  666268910803644416 Time: 0.03005170976393856
Success Count: 2339 Tweet ID:  666104133288665088 Time: -0.01022566159372218
Success Count: 2340 Tweet ID:  666102155909144576 Time: 0.027396179269999266
Success Count: 2341 Tweet ID:  666099513787052032 Time: -0.024716105952393264
Success Count: 2342 Tweet ID:  666094000022159362 Time: -0.005092063802294433
Success Count: 2343 Tweet ID:  666082916733198337 Time: 0.026283446612069383
Success Count: 2344 Tweet ID:  666073100786774016 Time: 0.00503467139787972
Success Count: 2345 Tweet ID:  666071193221509120 Time: -0.021950699185254052
Success Count: 2346 Tweet ID:  666063827256086533 Time: -0.011575515381991863
Success Count: 2347 Tweet ID:  666058600524156928 Time: -0.006954295618925244
Success Count: 2348 Tweet ID:  666057090499244032 Time: 0.001475965982535854
Success Count: 2349 Tweet ID:  666055525042405380 Time: 0.015426846424816176
Success Count: 2350 Tweet ID:  666051853826850816 Time: -0.014409641909878701
Success Count: 2351 Tweet ID:  666050758794694657 Time: 0.021503642725292593
Success Count: 2352 Tweet ID:  666049248165822465 Time: -0.022264846949838102
Success Count: 2353 Tweet ID:  666044226329800704 Time: 0.012156990822404623
Success Count: 2354 Tweet ID:  666033412701032449 Time: 0.008921495144022629
Success Count: 2355 Tweet ID:  666029285002620928 Time: 0.015479707857593894
Success Count: 2356 Tweet ID:  666020888022790149 Time: 0.054101006826385856

In [337]:
Failed_Ids = []
for tweetID in failed_tweetIds:
    Failed_Ids.append(tweetID)
print('There are a total of {} twitter IDs that couldn\'t be accessed'.format(len(Failed_Ids)))

There are a total of 15 twitter IDs that couldn't be accessed

In [338]:
# Note: The code used below was used from Randy J's slack post. 
json_tweet_list = [] # empty list to add dictionaries, once filled it will be passed into a dataframe

with open('tweet_json.txt','r') as json_file: 
    line = json_file.readline() # Read line by line of tweet_json.txt file 
    while line: # stops once there is no more lines to be read from the tweet_json.txt file
        json_tweet = json.loads(line) 
        # Create a list of dictionaries 
        json_tweet_list.append({'tweet_id': json_tweet['id'], 
                                'retweet_count': json_tweet['retweet_count'],
                                'favorite_count': json_tweet['favorite_count']})
        line = json_file.readline() # reads the next line

In [339]:
# Construct the dataframe and re-arrange the columns
df_twitterAPI = pd.DataFrame(json_tweet_list)
df_twitterAPI = df_twitterAPI[['tweet_id', 'retweet_count', 'favorite_count']]
df_twitterAPI.head()

             tweet_id  retweet_count  favorite_count
0  892420643555336193           8456           38440
1  892177421306343426           6230           32938
2  891815181378084864           4129           24811
3  891689557279858688           8577           41798
4  891327558926688256           9315           39963

## Assess the data, clean it and test it.

### Assess the twitter-archive-enhanced dataframe

Let's deep dive into the twitter-archive-enhanced dataframe.

In [193]:
# Take a copy of df_enhanced
df_enhanced_clean = df_enhanced.copy()

In [194]:
print('Enhanced Dataframe Shape:', df_enhanced.shape)
print('\n')
df_enhanced_clean.info()

Enhanced Dataframe Shape: (2356, 17)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

Let's perform a visual inspection of the twitter-archive-enhanced dataframe by looking at the head, tail and a random sample.

In [195]:
df_enhanced_clean.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,nan,nan,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU,nan,nan,NaN,https://twitter.com/dog_rates/status/892420643555336193/photo/1,13,10,Phineas,None,None,None,None
1,892177421306343426,nan,nan,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV",nan,nan,NaN,https://twitter.com/dog_rates/status/892177421306343426/photo/1,13,10,Tilly,None,None,None,None
2,891815181378084864,nan,nan,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10 https://t.co/wUnZnhtVJB,nan,nan,NaN,https://twitter.com/dog_rates/status/891815181378084864/photo/1,12,10,Archie,None,None,None,None
3,891689557279858688,nan,nan,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us https://t.co/tD36da7qLQ,nan,nan,NaN,https://twitter.com/dog_rates/status/891689557279858688/photo/1,13,10,Darla,None,None,None,None
4,891327558926688256,nan,nan,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","This is Franklin. He would like you to stop calling him ""cute."" He is a very fierce shark and should be respected as such. 12/10 #BarkWeek https://t.co/AtUZn91f7f",nan,nan,NaN,"https://twitter.com/dog_rates/status/891327558926688256/photo/1,https://twitter.com/dog_rates/status/891327558926688256/photo/1",12,10,Franklin,None,None,None,None

In [196]:
df_enhanced_clean.tail()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
2351,666049248165822465,nan,nan,2015-11-16 00:24:50 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Here we have a 1949 1st generation vulpix. Enjoys sweat tea and Fox News. Cannot be phased. 5/10 https://t.co/4B7cOc1EDq,nan,nan,NaN,https://twitter.com/dog_rates/status/666049248165822465/photo/1,5,10,None,None,None,None,None
2352,666044226329800704,nan,nan,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is a purebred Piers Morgan. Loves to Netflix and chill. Always looks like he forgot to unplug the iron. 6/10 https://t.co/DWnyCjf2mx,nan,nan,NaN,https://twitter.com/dog_rates/status/666044226329800704/photo/1,6,10,a,None,None,None,None
2353,666033412701032449,nan,nan,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af https://t.co/y671yMhoiR,nan,nan,NaN,https://twitter.com/dog_rates/status/666033412701032449/photo/1,9,10,a,None,None,None,None
2354,666029285002620928,nan,nan,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is a western brown Mitsubishi terrier. Upset about leaf. Actually 2 dogs here. 7/10 would walk the shit out of https://t.co/r7mOb2m0UI,nan,nan,NaN,https://twitter.com/dog_rates/status/666029285002620928/photo/1,7,10,a,None,None,None,None
2355,666020888022790149,nan,nan,2015-11-15 22:32:08 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet https://t.co/BLDqew2Ijj,nan,nan,NaN,https://twitter.com/dog_rates/status/666020888022790149/photo/1,8,10,None,None,None,None,None

In [197]:
df_enhanced_clean.sample(10)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
1506,691756958957883396,nan,nan,2016-01-25 22:58:05 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",THE BRITISH ARE COMING\nTHE BRITISH ARE COMING\n10/10 https://t.co/frGWV7IP6J,nan,nan,NaN,https://twitter.com/dog_rates/status/691756958957883396/photo/1,10,10,None,None,None,None,None
881,760521673607086080,nan,nan,2016-08-02 17:04:31 +0000,"<a href=""http://vine.co"" rel=""nofollow"">Vine - Make a Scene</a>","Doggo want what doggo cannot have. Temptation strong, dog stronger. 12/10 https://t.co/IqyTF6qik6",nan,nan,NaN,https://vine.co/v/5ApKetxzmTB,12,10,None,doggo,None,None,None
829,768909767477751808,nan,nan,2016-08-25 20:35:48 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",RT @dog_rates: When it's Janet from accounting's birthday but you can't eat the cake cuz it's chocolate. 10/10 hang in there pupper https:/…,700143752053182464,4196983835,2016-02-18 02:24:13 +0000,https://twitter.com/dog_rates/status/700143752053182464/photo/1,10,10,None,None,None,pupper,None
1325,706166467411222528,nan,nan,2016-03-05 17:16:20 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Dexter. He's a shy pup. Doesn't bark much. Dreadful fetcher. Has rare sun allergy. 7/10 still petable https://t.co/sA7P3JSqiv,nan,nan,NaN,https://twitter.com/dog_rates/status/706166467411222528/photo/1,7,10,Dexter,None,None,None,None
1047,743510151680958465,nan,nan,2016-06-16 18:26:48 +0000,"<a href=""http://twitter.com"" rel=""nofollow"">Twitter Web Client</a>","This is Beya. She doesn't want to swim, so she's not going to. 13/10 nonconforming af (vid by @HappyTailsResor) https://t.co/qGeVjHSUKH",nan,nan,NaN,https://twitter.com/dog_rates/status/743510151680958465/video/1,13,10,Beya,None,None,None,None
1054,742423170473463808,nan,nan,2016-06-13 18:27:32 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Bell. She likes holding hands. 12/10 would definitely pet with other hand https://t.co/BXIuvkQO9b,nan,nan,NaN,https://twitter.com/dog_rates/status/742423170473463808/photo/1,12,10,Bell,None,None,None,None
71,878776093423087618,nan,nan,2017-06-25 00:45:22 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Snoopy. He's a proud #PrideMonthPuppo. Impeccable handwriting for not having thumbs. 13/10 would love back #PrideMonth https://t.co/lNZwgNO4gS,nan,nan,NaN,"https://twitter.com/dog_rates/status/878776093423087618/photo/1,https://twitter.com/dog_rates/status/878776093423087618/photo/1",13,10,Snoopy,None,None,None,puppo
10,890006608113172480,nan,nan,2017-07-26 00:31:25 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Koda. He is a South Australian deckshark. Deceptively deadly. Frighteningly majestic. 13/10 would risk a petting #BarkWeek https://t.co/dVPW0B0Mme,nan,nan,NaN,"https://twitter.com/dog_rates/status/890006608113172480/photo/1,https://twitter.com/dog_rates/status/890006608113172480/photo/1",13,10,Koda,None,None,None,None
301,836677758902222849,nan,nan,2017-02-28 20:41:37 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Say hello to Oliver. He's pretty exotic. Fairly pupset as well. Too many midterms coming pup. 11/10 would pet with extreme caution https://t.co/fGAPAsxjKs,nan,nan,NaN,"https://twitter.com/dog_rates/status/836677758902222849/photo/1,https://twitter.com/dog_rates/status/836677758902222849/photo/1",11,10,Oliver,None,None,None,None
584,800141422401830912,nan,nan,2016-11-20 00:59:15 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Peaches. She's the ultimate selfie sidekick. Super sneaky tongue slip appreciated. 13/10 https://t.co/pbKOesr8Tg,nan,nan,NaN,"https://twitter.com/dog_rates/status/800141422401830912/photo/1,https://twitter.com/dog_rates/status/800141422401830912/photo/1,https://twitter.com/dog_rates/status/800141422401830912/photo/1",13,10,Peaches,None,None,None,None

Overviewing the .info() method as well as the data visually, we can see that some issues clearly stand out: 
1. Missing values exist in some variables. 
2. datatypes are not correct for some columns: 
    timestamp and retweeted_status_timestamp should be datetime objects instead of strings
3. dog stage columns can be converted into one instead of separated. 

Other visual changes to make to the dataframe are changing the pandas settings so that both the text and the floats appear in full instead of truncated.

In [198]:
# Set maximum column width in pandas to a larger value so that full text can be seen
pd.set_option('display.max_colwidth',-1)

# Remove engineering notation from floats
pd.set_option('display.float_format', lambda x: '%.0f' % x)

In [199]:
df_enhanced_clean.sample(5)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
1758,678755239630127104,nan,nan,2015-12-21 01:53:54 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Dash. He didn't think the water would be that cold. Damn it Dash it's December. Think a little. 10/10 https://t.co/NqcOwG8pxW,nan,nan,NaN,https://twitter.com/dog_rates/status/678755239630127104/photo/1,10,10,Dash,None,None,None,None
1849,675781562965868544,nan,nan,2015-12-12 20:57:34 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Say hello to Buddah. He was Waldo for Halloween. 11/10 https://t.co/DVAqAnb624,nan,nan,NaN,https://twitter.com/dog_rates/status/675781562965868544/photo/1,11,10,Buddah,None,None,None,None
154,862096992088072192,nan,nan,2017-05-10 00:08:34 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",We only rate dogs. Please don't send perfectly toasted marshmallows attempting to drive. Thank you... 13/10 https://t.co/nvZyyrp0kd,nan,nan,NaN,"https://twitter.com/dog_rates/status/862096992088072192/photo/1,https://twitter.com/dog_rates/status/862096992088072192/photo/1",13,10,None,None,None,None,None
1464,694356675654983680,670668383499735040,4196983835,2016-02-02 03:08:26 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","This pupper only appears through the hole of a Funyun. Much like Phineas, this one is also mysterious af. 10/10 https://t.co/SQsEBWxPyG",nan,nan,NaN,https://twitter.com/dog_rates/status/694356675654983680/photo/1,10,10,None,None,None,pupper,None
743,780459368902959104,nan,nan,2016-09-26 17:29:48 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","This is Bear. Don't worry, he's not a real bear tho. Contains unreal amounts of squish. 11/10 heteroskedastic af https://t.co/coi4l1T2Sm",nan,nan,NaN,https://twitter.com/dog_rates/status/780459368902959104/photo/1,11,10,Bear,None,None,None,None

Perform a quick check for duplicated tweet_ids

In [200]:
# Are there any duplicated tweet_ids? 
if sum(df_enhanced.tweet_id.duplicated()) == 0: 
    print('No duplicates in twitter_id for twitter-archive-enhanced dataframe')
else: 
    print('There are duplicates in tweet_id for twitter-archive-enhanced dataframe')

No duplicates in twitter_id for twitter-archive-enhanced dataframe

** There are 8 *quality* issues that will be addressed, they are the following:**

**1)** Change the timestamp columns to datetime objects.

**2)** Remove tweets without pictures.

**3)** Remove re-tweets.

**4)** Convert Nones to NaNs in dog stage columns: doggo, fluffer, pupper and puppo.

**5)** Fix the dog names in names column according to the text, if it's not in the text set it to None.

**6)** Fix the values of rating denominator for values greater than 10.

**7)** Shorten source by removing all the link components and keeping only what matters.

**8)** Remove duplicated expanded_urls

** There are 2 *tidiness* issues that will be addressed, they are the following:**

**1)** Create a single dog_stage column. 

**2)** Merge clean dataframes into one.

------------------------------------------------------------------------
### Addressing Quality Issues

**1)** timestamp and retweeted_status_timestamp columns should be datetime objects instead of strings.

In [201]:
# 2) Change timestamps to datetime objects
df_enhanced_clean['timestamp'] = pd.to_datetime(df_enhanced_clean['timestamp'])
df_enhanced_clean['retweeted_status_timestamp'] = pd.to_datetime(df_enhanced_clean['retweeted_status_timestamp'])
print(df_enhanced_clean['timestamp'].dtypes)
print(df_enhanced_clean['retweeted_status_timestamp'].dtypes)

datetime64[ns]
datetime64[ns]

**2)** Remove tweets without pictures (nulls in expanded_urls)

In [202]:
# 3) Remove Tweets with no images in expanded_urls
df_noImages=df_enhanced_clean[df_enhanced_clean.expanded_urls.isnull()]
noImages_indexList = df_noImages.index.tolist()
df_enhanced_clean.drop(noImages_indexList,inplace = True)
df_enhanced_clean.reset_index(drop = True,inplace = True)
print('{} rows were dropped due to no images'.format(len(df_noImages)))

59 rows were dropped due to no images

**3)** Remove rows that are re-tweets

In [203]:
print('# of rows before removing re-tweets: ',len(df_enhanced_clean))
print('Removing {} re-tweets'.format(len(df_enhanced_clean[df_enhanced_clean['retweeted_status_id'].notnull()])))
df_enhanced_clean = df_enhanced_clean[df_enhanced_clean['retweeted_status_id'].isnull()]
print('# of rows after removing re-tweets: ',len(df_enhanced_clean))
df_enhanced_clean.reset_index(drop = True, inplace = True)

# of rows before removing re-tweets:  2297
Removing 180 re-tweets
# of rows after removing re-tweets:  2117

**4)** Convert Nones to NaNs in dog stage columns

In [204]:
dog_stage_columns = ['doggo','floofer','pupper','puppo']
df_enhanced_clean[dog_stage_columns] = df_enhanced_clean[dog_stage_columns].replace('None',np.NaN)
df_enhanced_clean[dog_stage_columns].head(10)

   doggo floofer pupper puppo
0  NaN    NaN     NaN    NaN
1  NaN    NaN     NaN    NaN
2  NaN    NaN     NaN    NaN
3  NaN    NaN     NaN    NaN
4  NaN    NaN     NaN    NaN
5  NaN    NaN     NaN    NaN
6  NaN    NaN     NaN    NaN
7  NaN    NaN     NaN    NaN
8  NaN    NaN     NaN    NaN
9  doggo  NaN     NaN    NaN

**5)** Fix names in name column

In [205]:
# 4) Find incorrect names in name column. 
# Exploring the data it was found that there are several names with None as name, names that don't containg proper nouns and
# one name where only the first letter is captured. Find out the count and clean this mess!
print('# of Names with None: ', sum(df_enhanced_clean.name[df_enhanced_clean.name.str.contains('(None)')].value_counts())) 
print('# of Names with lowercase: ',sum(df_enhanced_clean.name[df_enhanced_clean.name.str.contains('^[a-z]')].value_counts()))
print('# of Names with only one uppercase: ', sum(df_enhanced_clean.name[df_enhanced_clean.name.str.contains('(^O$)')].value_counts()))
print('# of Names in good condition: ',sum(df_enhanced_clean.name[df_enhanced_clean.name.str.contains('[^(None)]') &
                       df_enhanced_clean.name.str.contains('[^a-z]') & 
                       df_enhanced_clean.name.str.contains('[^(^O$)]')].value_counts()))

# of Names with None:  622
# of Names with lowercase:  104
# of Names with only one uppercase:  1
# of Names in good condition:  1390

C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  after removing the cwd from sys.path.
C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

In [206]:
# Change the single O to O'Malley as described in the text
print(df_enhanced_clean.name[df_enhanced_clean.name.str.contains('(^O$)')])
df_enhanced_clean.name[df_enhanced_clean.name.str.contains('(^O$)')].replace('O','O\'Malley',inplace = True)
df_enhanced_clean.name[df_enhanced_clean.name.str.contains('(^O$)')] = 'O\'Malley'

596    O
Name: name, dtype: object

C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  after removing the cwd from sys.path.
C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [207]:
if df_enhanced_clean.name[df_enhanced_clean.name.str.contains('(^O$)')].empty: 
    print('O has been replaced with O\'Malley')

O has been replaced with O'Malley

C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

In [317]:
# Find out why there are None values 
NoNames = df_enhanced_clean[df_enhanced_clean.name.str.contains('(None)')].index.tolist()

df_enhanced_clean.iloc[NoNames]



# Create a dictionary where the key is the index value and the value is a list of capital words
# for word in words: 
#     if word[0].isupper():
#         list

# for i in range(len(NoNames)): 
#     text = re.findall(r"^[A-Z]",df_enhanced_clean.text[NoNames[i]])
#     print(df_enhanced_clean.text[NoNames[i]])
#     print(text)

C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
5,891087950875897856,nan,nan,2017-07-29 00:08:17,Twitter for iPhone,Here we have a majestic great white breaching off South Africa's coast. Absolutely h*ckin breathtaking. 13/10 (IG: tucker_marlo) #BarkWeek https://t.co/kQ04fDDRmh,nan,nan,NaT,https://twitter.com/dog_rates/status/891087950875897856/photo/1,13,10,None,NaN,NaN,NaN,NaN
7,890729181411237888,nan,nan,2017-07-28 00:22:40,Twitter for iPhone,When you watch your owner call another dog a good boy but then they turn back to you and say you're a great boy. 13/10 https://t.co/v0nONBcwxq,nan,nan,NaT,https://twitter.com/dog_rates/status/890729181411237888/photo/1,13,10,None,NaN,NaN,NaN,NaN
12,889665388333682689,nan,nan,2017-07-25 01:55:32,Twitter for iPhone,Here's a puppo that seems to be on the fence about something haha no but seriously someone help her. 13/10 https://t.co/BxvuXk0UCm,nan,nan,NaT,https://twitter.com/dog_rates/status/889665388333682689/photo/1,13,10,None,NaN,NaN,NaN,puppo
23,887343217045368832,nan,nan,2017-07-18 16:08:03,Twitter for iPhone,You may not have known you needed to see this today. 13/10 please enjoy (IG: emmylouroo) https://t.co/WZqNqygEyV,nan,nan,NaT,https://twitter.com/dog_rates/status/887343217045368832/video/1,13,10,None,NaN,NaN,NaN,NaN
24,887101392804085760,nan,nan,2017-07-18 00:07:08,Twitter for iPhone,This... is a Jubilant Antarctic House Bear. We only rate dogs. Please only send dogs. Thank you... 12/10 would suffocate in floof https://t.co/4Ad1jzJSdp,nan,nan,NaT,https://twitter.com/dog_rates/status/887101392804085760/photo/1,12,10,None,NaN,NaN,NaN,NaN
32,885518971528720385,nan,nan,2017-07-13 15:19:09,Twitter for iPhone,I have a new hero and his name is Howard. 14/10 https://t.co/gzLHboL7Sk,nan,nan,NaT,https://twitter.com/4bonds2carbon/status/885517367337512960,14,10,None,NaN,NaN,NaN,NaN
33,885167619883638784,nan,nan,2017-07-12 16:03:00,Twitter for iPhone,Here we have a corgi undercover as a malamute. Pawbably doing important investigative work. Zero control over tongue happenings. 13/10 https://t.co/44ItaMubBf,nan,nan,NaT,https://twitter.com/dog_rates/status/885167619883638784/photo/1,13,10,None,NaN,NaN,NaN,NaN
37,884441805382717440,nan,nan,2017-07-10 15:58:53,Twitter for iPhone,"I present to you, Pup in Hat. Pup in Hat is great for all occasions. Extremely versatile. Compact as h*ck. 14/10 (IG: itselizabethgales) https://t.co/vvBOcC2VdC",nan,nan,NaT,https://twitter.com/dog_rates/status/884441805382717440/photo/1,14,10,None,NaN,NaN,NaN,NaN
38,884247878851493888,nan,nan,2017-07-10 03:08:17,Twitter for iPhone,OMG HE DIDN'T MEAN TO HE WAS JUST TRYING A LITTLE BARKOUR HE'S SUPER SORRY 13/10 WOULD FORGIVE IMMEDIATE https://t.co/uF3pQ8Wubj,nan,nan,NaT,https://twitter.com/kaijohnson_19/status/883965650754039809,13,10,None,NaN,NaN,NaN,NaN
43,883117836046086144,nan,nan,2017-07-07 00:17:54,Twitter for iPhone,"Please only send dogs. We don't rate mechanics, no matter how h*ckin good. Thank you... 13/10 would sneak a pat https://t.co/Se5fZ9wp5E",nan,nan,NaT,https://twitter.com/dog_rates/status/883117836046086144/photo/1,13,10,None,NaN,NaN,NaN,NaN
54,880872448815771648,nan,nan,2017-06-30 19:35:32,Twitter for iPhone,Ugh not again. We only rate dogs. Please don't send in well-dressed floppy-tongued street penguins. Dogs only please. Thank you... 12/10 https://t.co/WiAMbTkDPf,nan,nan,NaT,https://twitter.com/dog_rates/status/880872448815771648/photo/1,12,10,None,NaN,NaN,NaN,NaN
57,880095782870896641,nan,nan,2017-06-28 16:09:20,Twitter for iPhone,Please don't send in photos without dogs in them. We're not @porch_rates. Insubordinate and churlish. Pretty good porch tho 11/10 https://t.co/HauE8M3Bu4,nan,nan,NaT,https://twitter.com/dog_rates/status/880095782870896641/photo/1,11,10,None,NaN,NaN,NaN,NaN
65,878604707211726852,nan,nan,2017-06-24 13:24:20,Twitter for iPhone,Martha is stunning how h*ckin dare you. 13/10 https://t.co/9uABQXgjwa,nan,nan,NaT,https://twitter.com/bbcworld/status/878599868507402241,13,10,None,NaN,NaN,NaN,NaN
73,876537666061221889,nan,nan,2017-06-18 20:30:39,Twitter for iPhone,I can say with the pupmost confidence that the doggos who assisted with this search are heroic as h*ck. 14/10 for all https://t.co/8yoc1CNTsu,nan,nan,NaT,https://twitter.com/mpstowerham/status/876162994446753793,14,10,None,NaN,NaN,NaN,NaN
78,875097192612077568,nan,nan,2017-06-14 21:06:43,Twitter for iPhone,You'll get your package when that precious man is done appreciating the pups. 13/10 for everyone https://t.co/PFp4MghzBW,nan,nan,NaT,https://twitter.com/drboondoc/status/874413398133547008,13,10,None,NaN,NaN,NaN,NaN
79,875021211251597312,nan,nan,2017-06-14 16:04:48,Twitter for iPhone,Guys please stop sending pictures without any dogs in th- oh never mind hello excuse me sir. 12/10 stealthy as h*ck https://t.co/brCQoqc8AW,nan,nan,NaT,https://twitter.com/dog_rates/status/875021211251597312/photo/1,12,10,None,NaN,NaN,NaN,NaN
82,874057562936811520,nan,nan,2017-06-12 00:15:36,Twitter for iPhone,"I can't believe this keeps happening. This, is a birb taking a bath. We only rate dogs. Please only send dogs. Thank you... 12/10 https://t.co/pwY9PQhtP2",nan,nan,NaT,https://twitter.com/dog_rates/status/874057562936811520/photo/1,12,10,None,NaN,NaN,NaN,NaN
84,873580283840344065,nan,nan,2017-06-10 16:39:04,Twitter for iPhone,"We usually don't rate Deck-bound Saskatoon Black Bears, but this one is h*ckin flawless. Sneaky tongue slip too. 13/10 would hug firmly https://t.co/mNuMH9400n",nan,nan,NaT,https://twitter.com/dog_rates/status/873580283840344065/photo/1,13,10,None,NaN,NaN,NaN,NaN
86,872967104147763200,nan,nan,2017-06-09 00:02:31,Twitter for iPhone,Here's a very large dog. He has a date later. Politely asked this water person to check if his breath is bad. 12/10 good to go doggo https://t.co/EMYIdoblMR,nan,nan,NaT,https://twitter.com/dog_rates/status/872967104147763200/photo/1,12,10,None,doggo,NaN,NaN,NaN
87,872820683541237760,nan,nan,2017-06-08 14:20:41,Twitter for iPhone,Here are my favorite #dogsatpollingstations \nMost voted for a more consistent walking schedule and to increase daily pats tenfold. All 13/10 https://t.co/17FVMl4VZ5,nan,nan,NaT,https://twitter.com/dog_rates/status/872820683541237760/photo/1,13,10,None,NaN,NaN,NaN,NaN
89,872486979161796608,nan,nan,2017-06-07 16:14:40,Twitter for iPhone,We. Only. Rate. Dogs. Do not send in other things like this fluffy floor shark clearly ready to attack. Get it together guys... 12/10 https://t.co/BZHiKx3FpQ,nan,nan,NaT,https://twitter.com/dog_rates/status/872486979161796608/photo/1,12,10,None,NaN,NaN,NaN,NaN
95,871102520638267392,nan,nan,2017-06-03 20:33:19,Twitter for iPhone,Never doubt a doggo 14/10 https://t.co/AbBLh2FZCH,nan,nan,NaT,https://twitter.com/animalcog/status/871075758080503809,14,10,None,doggo,NaN,NaN,NaN
97,870804317367881728,nan,nan,2017-06-03 00:48:22,Twitter for iPhone,Real funny guys. Sending in a pic without a dog in it. Hilarious. We'll rate the rug tho because it's giving off a very good vibe. 11/10 https://t.co/GCD1JccCyi,nan,nan,NaT,https://twitter.com/dog_rates/status/870804317367881728/photo/1,11,10,None,NaN,NaN,NaN,NaN
107,868622495443632128,nan,nan,2017-05-28 00:18:35,Twitter for iPhone,Here's a h*ckin peaceful boy. Unbothered by the comings and goings. 13/10 please reveal your wise ways https://t.co/yeaH8Ej5eM,nan,nan,NaT,https://twitter.com/dog_rates/status/868622495443632128/photo/1,13,10,None,NaN,NaN,NaN,NaN
109,867900495410671616,nan,nan,2017-05-26 00:29:37,Twitter for iPhone,"Unbelievable. We only rate dogs. Please don't send in non-canines like the ""I"" from Pixar's opening credits. Thank you... 12/10 https://t.co/JMhDNv5wXZ",nan,nan,NaT,https://twitter.com/dog_rates/status/867900495410671616/photo/1,12,10,None,NaN,NaN,NaN,NaN
112,867051520902168576,nan,nan,2017-05-23 16:16:06,Twitter for iPhone,"Oh my this spooked me up. We only rate dogs, not happy ghosts. Please send dogs only. It's a very simple premise. Thank you... 13/10 https://t.co/M5Rz0R8SIQ",nan,nan,NaT,https://twitter.com/dog_rates/status/867051520902168576/photo/1,13,10,None,NaN,NaN,NaN,NaN
113,866720684873056260,nan,nan,2017-05-22 18:21:28,Twitter for iPhone,He was providing for his family 13/10 how dare you https://t.co/Q8mVwWN3f4,nan,nan,NaT,https://twitter.com/nbcnews/status/866458718883467265,13,10,None,NaN,NaN,NaN,NaN
120,864873206498414592,nan,nan,2017-05-17 16:00:15,Twitter for iPhone,We only rate dogs. Please don't send in Jesus. We're trying to remain professional and legitimate. Thank you... 14/10 https://t.co/wr3xsjeCIR,nan,nan,NaT,https://twitter.com/dog_rates/status/864873206498414592/photo/1,14,10,None,NaN,NaN,NaN,NaN
126,863079547188785154,667152164079423488,4196983835,2017-05-12 17:12:53,Twitter for iPhone,"Ladies and gentlemen... I found Pipsy. He may have changed his name to Pablo, but he never changed his love for the sea. Pupgraded to 14/10 https://t.co/lVU5GyNFen",nan,nan,NaT,https://twitter.com/dog_rates/status/863079547188785154/photo/1,14,10,None,NaN,NaN,NaN,NaN
131,862096992088072192,nan,nan,2017-05-10 00:08:34,Twitter for iPhone,We only rate dogs. Please don't send perfectly toasted marshmallows attempting to drive. Thank you... 13/10 https://t.co/nvZyyrp0kd,nan,nan,NaT,https://twitter.com/dog_rates/status/862096992088072192/photo/1,13,10,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2050,667176164155375616,nan,nan,2015-11-19 03:02:47,Twitter for iPhone,These are strange dogs. All have toupees. Long neck for dogs. In a shed of sorts? Work in groups? 4/10 still petable https://t.co/PZxSarAfSN,nan,nan,NaT,https://twitter.com/dog_rates/status/667176164155375616/photo/1,4,10,None,NaN,NaN,NaN,NaN
2056,667138269671505920,nan,nan,2015-11-19 00:32:12,Twitter for iPhone,Extremely intelligent dog here. Has learned to walk like human. Even has his own dog. Very impressive 10/10 https://t.co/0DvHAMdA4V,nan,nan,NaT,https://twitter.com/dog_rates/status/667138269671505920/photo/1,10,10,None,NaN,NaN,NaN,NaN
2060,667065535570550784,nan,nan,2015-11-18 19:43:11,Twitter for iPhone,Here we have a Hufflepuff. Loves vest. Eyes wide af. Flaccid tail. Matches carpet. Always a little blurry. 8/10 https://t.co/7JdgVqDnvR,nan,nan,NaT,https://twitter.com/dog_rates/status/667065535570550784/photo/1,8,10,None,NaN,NaN,NaN,NaN
2062,667044094246576128,nan,nan,2015-11-18 18:17:59,Twitter for iPhone,12/10 gimme now https://t.co/QZAnwgnOMB,nan,nan,NaT,https://twitter.com/dog_rates/status/667044094246576128/photo/1,12,10,None,NaN,NaN,NaN,NaN
2066,666837028449972224,nan,nan,2015-11-18 04:35:11,Twitter for iPhone,My goodness. Very rare dog here. Large. Tail dangerous. Kinda fat. Only eats leaves. Doesn't come when called 3/10 https://t.co/xYGdBrMS9h,nan,nan,NaT,https://twitter.com/dog_rates/status/666837028449972224/photo/1,3,10,None,NaN,NaN,NaN,NaN
2067,666835007768551424,nan,nan,2015-11-18 04:27:09,Twitter for iPhone,These are Peruvian Feldspars. Their names are Cupit and Prencer. Both resemble Rand Paul. Sick outfits 10/10 &amp; 10/10 https://t.co/ZnEMHBsAs1,nan,nan,NaT,https://twitter.com/dog_rates/status/666835007768551424/photo/1,10,10,None,NaN,NaN,NaN,NaN
2068,666826780179869698,nan,nan,2015-11-18 03:54:28,Twitter for iPhone,12/10 simply brilliant pup https://t.co/V6ZzG45zzG,nan,nan,NaT,https://twitter.com/dog_rates/status/666826780179869698/photo/1,12,10,None,NaN,NaN,NaN,NaN
2071,666786068205871104,nan,nan,2015-11-18 01:12:41,Twitter for iPhone,Unfamiliar with this breed. Ears pointy af. Won't let go of seashell. Won't eat kibble. Not very fast. Bad dog 2/10 https://t.co/EIn5kElY1S,nan,nan,NaT,https://twitter.com/dog_rates/status/666786068205871104/photo/1,2,10,None,NaN,NaN,NaN,NaN
2077,666649482315059201,nan,nan,2015-11-17 16:09:56,Twitter for iPhone,Cool dog. Enjoys couch. Low monotone bark. Very nice kicks. Pisses milk (must be rare). Can't go down stairs. 4/10 https://t.co/vXMKrJC81s,nan,nan,NaT,https://twitter.com/dog_rates/status/666649482315059201/photo/1,4,10,None,NaN,NaN,NaN,NaN
2081,666437273139982337,nan,nan,2015-11-17 02:06:42,Twitter for iPhone,Here we see a lone northeastern Cumberbatch. Half ladybug. Only builds with bricks. Very confident with body. 7/10 https://t.co/7LtjBS0GPK,nan,nan,NaT,https://twitter.com/dog_rates/status/666437273139982337/photo/1,7,10,None,NaN,NaN,NaN,NaN
2082,666435652385423360,nan,nan,2015-11-17 02:00:15,Twitter for iPhone,"""Can you behave? You're ruining my wedding day""\nDOG: idgaf this flashlight tastes good as hell\n\n10/10 https://t.co/GlFZPzqcEU",nan,nan,NaT,https://twitter.com/dog_rates/status/666435652385423360/photo/1,10,10,None,NaN,NaN,NaN,NaN
2083,666430724426358785,nan,nan,2015-11-17 01:40:41,Twitter for iPhone,Oh boy what a pup! Sunglasses take this one to the next level. Weirdly folds front legs. Pretty big. 6/10 https://t.co/yECbFrSArM,nan,nan,NaT,https://twitter.com/dog_rates/status/666430724426358785/photo/1,6,10,None,NaN,NaN,NaN,NaN
2084,666428276349472768,nan,nan,2015-11-17 01:30:57,Twitter for iPhone,Here we have an Austrian Pulitzer. Collectors edition. Levitates (?). 7/10 would garden with https://t.co/NMQq6HIglK,nan,nan,NaT,https://twitter.com/dog_rates/status/666428276349472768/photo/1,7,10,None,NaN,NaN,NaN,NaN
2085,666421158376562688,nan,nan,2015-11-17 01:02:40,Twitter for iPhone,*internally screaming* 12/10 https://t.co/YMcrXC2Y6R,nan,nan,NaT,https://twitter.com/dog_rates/status/666421158376562688/photo/1,12,10,None,NaN,NaN,NaN,NaN
2089,666396247373291520,nan,nan,2015-11-16 23:23:41,Twitter for iPhone,Oh goodness. A super rare northeast Qdoba kangaroo mix. Massive feet. No pouch (disappointing). Seems alert. 9/10 https://t.co/Dc7b0E8qFE,nan,nan,NaT,https://twitter.com/dog_rates/status/666396247373291520/photo/1,9,10,None,NaN,NaN,NaN,NaN
2090,666373753744588802,nan,nan,2015-11-16 21:54:18,Twitter for iPhone,Those are sunglasses and a jean jacket. 11/10 dog cool af https://t.co/uHXrPkUEyl,nan,nan,NaT,https://twitter.com/dog_rates/status/666373753744588802/photo/1,11,10,None,NaN,NaN,NaN,NaN
2091,666362758909284353,nan,nan,2015-11-16 21:10:36,Twitter for iPhone,Unique dog here. Very small. Lives in container of Frosted Flakes (?). Short legs. Must be rare 6/10 would still pet https://t.co/XMD9CwjEnM,nan,nan,NaT,https://twitter.com/dog_rates/status/666362758909284353/photo/1,6,10,None,NaN,NaN,NaN,NaN
2092,666353288456101888,nan,nan,2015-11-16 20:32:58,Twitter for iPhone,Here we have a mixed Asiago from the Galápagos Islands. Only one ear working. Big fan of marijuana carpet. 8/10 https://t.co/tltQ5w9aUO,nan,nan,NaT,https://twitter.com/dog_rates/status/666353288456101888/photo/1,8,10,None,NaN,NaN,NaN,NaN
2093,666345417576210432,nan,nan,2015-11-16 20:01:42,Twitter for iPhone,Look at this jokester thinking seat belt laws don't apply to him. Great tongue tho 10/10 https://t.co/VFKG1vxGjB,nan,nan,NaT,https://twitter.com/dog_rates/status/666345417576210432/photo/1,10,10,None,NaN,NaN,NaN,NaN
2097,666273097616637952,nan,nan,2015-11-16 15:14:19,Twitter for iPhone,Can take selfies 11/10 https://t.co/ws2AMaNwPW,nan,nan,NaT,https://twitter.com/dog_rates/status/666273097616637952/photo/1,11,10,None,NaN,NaN,NaN,NaN
2098,666268910803644416,nan,nan,2015-11-16 14:57:41,Twitter for iPhone,Very concerned about fellow dog trapped in computer. 10/10 https://t.co/0yxApIikpk,nan,nan,NaT,https://twitter.com/dog_rates/status/666268910803644416/photo/1,10,10,None,NaN,NaN,NaN,NaN
2099,666104133288665088,nan,nan,2015-11-16 04:02:55,Twitter for iPhone,Not familiar with this breed. No tail (weird). Only 2 legs. Doesn't bark. Surprisingly quick. Shits eggs. 1/10 https://t.co/Asgdc6kuLX,nan,nan,NaT,https://twitter.com/dog_rates/status/666104133288665088/photo/1,1,10,None,NaN,NaN,NaN,NaN
2100,666102155909144576,nan,nan,2015-11-16 03:55:04,Twitter for iPhone,Oh my. Here you are seeing an Adobe Setter giving birth to twins!!! The world is an amazing place. 11/10 https://t.co/11LvqN4WLq,nan,nan,NaT,https://twitter.com/dog_rates/status/666102155909144576/photo/1,11,10,None,NaN,NaN,NaN,NaN
2101,666099513787052032,nan,nan,2015-11-16 03:44:34,Twitter for iPhone,Can stand on stump for what seems like a while. Built that birdhouse? Impressive. Made friends with a squirrel. 8/10 https://t.co/Ri4nMTLq5C,nan,nan,NaT,https://twitter.com/dog_rates/status/666099513787052032/photo/1,8,10,None,NaN,NaN,NaN,NaN
2102,666094000022159362,nan,nan,2015-11-16 03:22:39,Twitter for iPhone,This appears to be a Mongolian Presbyterian mix. Very tired. Tongue slip confirmed. 9/10 would lie down with https://t.co/mnioXo3IfP,nan,nan,NaT,https://twitter.com/dog_rates/status/666094000022159362/photo/1,9,10,None,NaN,NaN,NaN,NaN
2103,666082916733198337,nan,nan,2015-11-16 02:38:37,Twitter for iPhone,Here we have a well-established sunblockerspaniel. Lost his other flip-flop. 6/10 not very waterproof https://t.co/3RU6x0vHB7,nan,nan,NaT,https://twitter.com/dog_rates/status/666082916733198337/photo/1,6,10,None,NaN,NaN,NaN,NaN
2104,666073100786774016,nan,nan,2015-11-16 01:59:36,Twitter for iPhone,Let's hope this flight isn't Malaysian (lol). What a dog! Almost completely camouflaged. 10/10 I trust this pilot https://t.co/Yk6GHE9tOY,nan,nan,NaT,https://twitter.com/dog_rates/status/666073100786774016/photo/1,10,10,None,NaN,NaN,NaN,NaN
2105,666071193221509120,nan,nan,2015-11-16 01:52:02,Twitter for iPhone,Here we have a northern speckled Rhododendron. Much sass. Gives 0 fucks. Good tongue. 9/10 would caress sensually https://t.co/ZoL8kq2XFx,nan,nan,NaT,https://twitter.com/dog_rates/status/666071193221509120/photo/1,9,10,None,NaN,NaN,NaN,NaN
2112,666049248165822465,nan,nan,2015-11-16 00:24:50,Twitter for iPhone,Here we have a 1949 1st generation vulpix. Enjoys sweat tea and Fox News. Cannot be phased. 5/10 https://t.co/4B7cOc1EDq,nan,nan,NaT,https://twitter.com/dog_rates/status/666049248165822465/photo/1,5,10,None,NaN,NaN,NaN,NaN
2116,666020888022790149,nan,nan,2015-11-15 22:32:08,Twitter for iPhone,Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet https://t.co/BLDqew2Ijj,nan,nan,NaT,https://twitter.com/dog_rates/status/666020888022790149/photo/1,8,10,None,NaN,NaN,NaN,NaN

**6)** Fix the values of rating_denominator that are not equal to 10

In [209]:
# Find denominators that are not equal to 10, find out why and fix those. 
print(df_enhanced_clean.rating_denominator.value_counts().to_dict(),'\n')

print('Amount of ratings with denominators greater than 10: ',len(df_enhanced_clean[df_enhanced_clean.rating_denominator != 10]))
print('\n')

{10: 2099, 50: 3, 11: 2, 80: 2, 7: 1, 170: 1, 150: 1, 130: 1, 120: 1, 110: 1, 90: 1, 70: 1, 40: 1, 20: 1, 2: 1}

Amount of ratings with denominators greater than 10:  18

In [297]:
# Capture the indices of rating_denominator that are not 10. 
large_denoms = df_enhanced_clean[df_enhanced_clean.rating_denominator != 10].index.tolist()
print('There is a total of {} rows that need to be fixed'.format(len(large_denoms)))

There is a total of 18 rows that need to be fixed

In [307]:
# Find ratios(number/number) in text for the cases where there is not a 10 as a rating_denominator
for i in range(len(large_denoms)): 
    ratios = re.findall(r"\d+/\d+",df_enhanced_clean.text[large_denoms[i]])
    if len(ratios) > 1: 
        df_enhanced_clean.rating_numerator[large_denoms[i]] = int(ratios[1].split('/')[0])
        df_enhanced_clean.rating_denominator[large_denoms[i]] = int(ratios[1].split('/')[1])
    else: 
        if int(ratios[0].split('/')[1]) % 10 == 0:
            den = int(ratios[0].split('/')[1])
            num = int(ratios[0].split('/')[0])/(den/10)
            df_enhanced_clean.rating_denominator[large_denoms[i]] = 10
            df_enhanced_clean.rating_numerator[large_denoms[i]] = num
        else: 
            df_enhanced_clean.rating_numerator[large_denoms[i]] = None
            df_enhanced_clean.rating_denominator[large_denoms[i]] = None

C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [312]:
df_enhanced_clean.rating_denominator.value_counts(dropna= False)

10     2116
nan    1
Name: rating_denominator, dtype: int64

**7)** Change the source column to a categorical variable by extracting the last part of the link

In [213]:
unique_sources = df_enhanced_clean['source'].unique()
unique_sources

array([ '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       '<a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>',
       '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>'], dtype=object)

In [214]:
df_enhanced_clean.source.value_counts()

<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>     1985
<a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>                        91
<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>                     30
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>    11
Name: source, dtype: int64

In [215]:
# Replace source, although this violates the DRY principle. 
df_enhanced_clean['source'] = df_enhanced_clean.source.str.replace(unique_sources[0], 'Twitter for iPhone')
df_enhanced_clean['source'] = df_enhanced_clean.source.str.replace(unique_sources[1], 'Vine')
df_enhanced_clean['source'] = df_enhanced_clean.source.str.replace(unique_sources[2], 'Twitter for Web Client')
df_enhanced_clean['source'] = df_enhanced_clean.source.str.replace(unique_sources[3], 'TweetDeck')

df_enhanced_clean.source.value_counts()

Twitter for iPhone        1985
Twitter for Web Client    91
Vine                      30
TweetDeck                 11
Name: source, dtype: int64

In [216]:
df_enhanced_clean.source = df_enhanced_clean.source.astype('category')

In [217]:
df_enhanced_clean.source.dtype

category

**8)** Remove duplicated expanded_urls

In [218]:
# Split the items in expanded_urls column by column. split() method outputs a list of each row split into a list
url_split = df_enhanced_clean.expanded_urls.str.split(',')

# Find if there are any duplicates in the url_split list that contains more than 1 item.
for item in range(0,len(url_split)): 
    df_enhanced_clean.expanded_urls[item] =  list(set(url_split[item])) # convert to set back into a list

C:\Users\raju8901\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [219]:
# Convert each list in expanded_urls column to a string
df_enhanced_clean.expanded_urls = df_enhanced_clean.expanded_urls.map(lambda x: str(x))

# Remove quotes and square brackets to keep only the unique urls
df_enhanced_clean.expanded_urls = df_enhanced_clean.expanded_urls.map(lambda x: x[2:-2])

In [220]:
df_enhanced_clean.expanded_urls.sample(10)

816    https://twitter.com/dog_rates/status/746131877086527488/photo/1
685    https://twitter.com/dog_rates/status/760290219849637889/video/1
320    https://twitter.com/dog_rates/status/824297048279236611/photo/1
175    https://twitter.com/dog_rates/status/851224888060895234/photo/1
848    https://twitter.com/dog_rates/status/741743634094141440/photo/1
635    https://twitter.com/dog_rates/status/770293558247038976/photo/1
208    https://twitter.com/brianstack153/status/796796054100471809
119    https://twitter.com/dog_rates/status/865006731092295680/photo/1
351    https://twitter.com/dog_rates/status/819006400881917954/photo/1
468    https://twitter.com/dog_rates/status/796484825502875648/photo/1
Name: expanded_urls, dtype: object

### Assess the predictions dataframe

In [221]:
print('Predictions Dataframe Shape:', df_predictions.shape)
print('\n')
df_predictions.info()

Predictions Dataframe Shape: (2075, 12)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null int64
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB

In [222]:
df_predictions.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0,True,collie,0,True,Shetland_sheepdog,0,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,1,True,miniature_pinscher,0,True,Rhodesian_ridgeback,0,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,1,True,malinois,0,True,bloodhound,0,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0,True,redbone,0,True,miniature_pinscher,0,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,1,True,Rottweiler,0,True,Doberman,0,True

In [223]:
df_predictions.tail()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
2070,891327558926688256,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,2,basset,1,True,English_springer,0,True,German_short-haired_pointer,0,True
2071,891689557279858688,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,1,paper_towel,0,False,Labrador_retriever,0,True,spatula,0,False
2072,891815181378084864,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,1,Chihuahua,1,True,malamute,0,True,kelpie,0,True
2073,892177421306343426,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,1,Chihuahua,0,True,Pekinese,0,True,papillon,0,True
2074,892420643555336193,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,1,orange,0,False,bagel,0,False,banana,0,False

In [224]:
df_predictions.sample(10)

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
1747,823322678127919110,https://pbs.twimg.com/media/C20HmaKWgAQ6-6X.jpg,2,cowboy_boot,1,False,Chihuahua,0,True,papillon,0,True
2039,884925521741709313,https://pbs.twimg.com/media/DEfjEaNXkAAtPlj.jpg,1,Italian_greyhound,0,True,American_Staffordshire_terrier,0,True,Staffordshire_bullterrier,0,True
1667,812781120811126785,https://pbs.twimg.com/media/C0eUHfWUAAANEYr.jpg,1,bull_mastiff,1,True,boxer,0,True,French_bulldog,0,True
422,674051556661161984,https://pbs.twimg.com/media/CVq2UHwWEAAduMw.jpg,1,Shih-Tzu,0,True,badger,0,False,three-toed_sloth,0,False
372,672984142909456390,https://pbs.twimg.com/media/CVbrcZyVAAA5Wpq.jpg,1,wombat,1,False,beaver,0,False,wallaby,0,False
1127,727644517743104000,https://pbs.twimg.com/media/Chkc1BQUoAAa96R.jpg,2,Great_Pyrenees,0,True,kuvasz,0,True,Labrador_retriever,0,True
1263,749036806121881602,https://pbs.twimg.com/media/CmUciKgWIAA97sH.jpg,1,sulphur-crested_cockatoo,1,False,West_Highland_white_terrier,0,True,Samoyed,0,True
311,671544874165002241,https://pbs.twimg.com/media/CVHOgDvU4AAfrXD.jpg,1,feather_boa,0,False,wig,0,False,wool,0,False
1583,796865951799083009,https://pbs.twimg.com/media/Cw8JWZ2UsAAJOZ6.jpg,1,Cardigan,1,True,Boston_bull,0,True,Pembroke,0,True
1410,770655142660169732,https://pbs.twimg.com/media/CrHqwjWXgAAgJSe.jpg,1,Madagascar_cat,0,False,skunk,0,False,paper_towel,0,False

In [225]:
sum(df_predictions.tweet_id.duplicated())

0